### ISSUE TITLE
Sorting Using Statements

### ISSUE THREAD

**Issue by kevingy** [codecadwallader/codemaid#101]
Using v 0.7.6 beta, when CodeMaid sorts usings, it alphabetizes all of them, including the System.* usings. This violates StyleCop rule 1208:

SA1208 : CSharp.Ordering : System using directives must be placed before all other using directives.

It would be nice to either change the sorting or have an setting to change the sorting to sort using statements with all System usings alphabetized first followed by all alphabetized non-System usings.

**Comment by codecadwallader** [comment]
This is a Visual Studio setting that Microsoft changed starting in VS2012.  Please see #75 for more details.

**Comment by kevingy** [comment]
I didn't know that option existed. Thanks!

**Comment by codecadwallader** [comment]
You're welcome :)
