### ISSUE TITLE
Deleting #endregion statement in C# code causes incorrect region re-creation in future

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#102]
I have found the case, that might be by design, but looks strange.

I reorganized code, and planned to move public methods `#endregion` statement to another line. That region was created by `CodeMaid` previously. I've cut symbols, and planned to paste it on correct line. At this moment I have remembered that actually I have `CodeMaid` to do the dirty work — correct region recreation... And I started document clean up.

As result new regions were created but unmatched starting `#region Public Methods` still exists in the file.

I thought that `CodeMaid` completely recreates all regions it created... And it actually makes sense to keep these regions consistent.

What's your official position on this topic? 

Many thanks in advance!

**Comment by codecadwallader** [comment]
So a starting region with no matching endregion is invalid code and won't compile.  In general, we do the best we can but don't make any guarantees about behavior with code in an invalid state.  As you can imagine trying to handle all of the possible scenarios quickly becomes unmanageable.

FWIW:  With the Roslyn compiler in VS2015, we will be able to more proactively detect if the code is in a valid state or not.  We've been considering having some features disable (or require user override) when that is detected.

Hope it helps.  Please feel free to comment further and I'll see it, but closing the issue for now.
