### ISSUE TITLE
The keyword `file` will be changed to `internal`.

### ISSUE THREAD

**Issue by emako** [codecadwallader/codemaid#1023]
### Environment
- Visual Studio version: [example 2022 Community]
- CodeMaid version: [12.0]
- Code language: [C#11]

### Description
Replace this text with a short description and code sample.
![image](https://github.com/codecadwallader/codemaid/assets/24737061/cbbfa46f-9442-421e-ba1b-f3d63123b2c3)
Any switch to disable this func?

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong.
The keyword `file` will be changed to `internal`.

### Expected behavior
Explain what it should be doing after it's fixed.
Keep `file` keyword.

**Comment by emako** [comment]
Code sample:
```c#
file static class BitmapExtension
{
}
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  There is a known issue with the VS2022 SDK that has not been resolved which is causing issues with some declarations.  The recommendation is to disable the insertion of explicit access modifiers in CodeMaid's configuration to bypass the issue for now.  Please see #879 for more details.
