### ISSUE TITLE
Formatting Removes `file` and `required` keywords

### ISSUE THREAD

**Issue by Mike-Logit** [codecadwallader/codemaid#1030]
### Environment
- Visual Studio version: 2022 Professional, 17.8.1
- CodeMaid version: [example 12.0]
- Code language: C# 12

### Description
When I run the CodeMaid Format Document command, it removes the newer keywords. I have seen some issues raised about the removal of the `required` keyword but for me it also removes the `file` keyword (the newer access modifier). This seems like a problem with reverting to older C# language levels by avoiding these newer keywords.

### Steps to recreate
1. Set your C# language level to 12
2. Add this code in any C# project:

```csharp
file class Test
{
    public required string Name { get; set; }
}
```

3. Run the CodeMaid formatter

### Current behavior

CodeMaid removes the `file` keyword for `internal`, and also strips out the `required` keyword after formatting:

BEFORE FORMATTING:
![image](https://github.com/codecadwallader/codemaid/assets/41903446/78bf0c4c-1d4f-4382-8409-dbd1881494fe)

AFTER FORMATTING:
![image](https://github.com/codecadwallader/codemaid/assets/41903446/7be40e11-cc88-4aa7-8b5f-626e4ab51c31)

### Expected behavior
I want to use the newer `file` access modifier to scope classes by file instead of scoping them by project, like the internal access modifier does. I also want to maintain the `required` keyword.

**Comment by Mike-Logit** [comment]
Sorry, I found another issue that covers this for `file`: https://github.com/codecadwallader/codemaid/issues/1023
I'm sure I've seen one for `required` as well so I can close this issue.

**Comment by Mike-Logit** [comment]
In case anyone lands on this page, the workaround worked for me:
https://github.com/codecadwallader/codemaid/issues/879#issuecomment-1381429250

**Comment by ashrafsabrym** [comment]
Why is this issue closed? The problem still occurs
