### ISSUE TITLE
Documentation link broken?

### ISSUE THREAD

**Issue by asvrada** [codecadwallader/codemaid#1049]
https://www.codemaid.net/documentation/#cleaning
Redirects to 
https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid#cleaning

**Comment by mdell-seradex** [comment]
Yes, the entire codemaid.net site redirects to the marketplace.  I was just going to create an issue for that.
Maybe it can be hosted directly from github?

**Comment by asvrada** [comment]
Close as duplicate with #1038
