### ISSUE TITLE
"Find in solution explorer" not working since VS2022 17.10.0

### ISSUE THREAD

**Issue by pedrodel99** [codecadwallader/codemaid#1055]
### Environment
- Visual Studio version: 2022 Community 17.10.0
- CodeMaid version: 12.0.300
- Code language: C# + all files

### Description
Since VS2022 17.10.0 update, function "Find in solution explorer" is not working anymore...

### Steps to recreate
1. Install VS2022 Community 17.10.0
2. Create a project with more than 2 files
3. Try shortcut Ctrl+M,F or using contextual menu

### Current behavior
Solution explorer is not opened, and the current file was not targeted.

### Expected behavior
"Find in solution explorer" was supposed to work... but it's not!

### Update
According with @huwilly, changing keyboard shortcut resolve it...

**Comment by xyseb** [comment]
Context menu works for me from a right click on a file tab. But doesn't work from the shortcut
I tried on VS  2022 Professionnal 17.10.1

**Comment by huwilly** [comment]
The command 'Cpp.QuickInfo.SearchOnline' has the same shortcut (in Text Editor).
In the Options menu (Environment / Keyboard), if you remove the shortcut for this command, it will be solved.

**Comment by triynko** [comment]
The Search box in solution explorer VS 2022 just stops working.  Trust me. I've been coding for 30+ years and have used VS for every day for 3/4 of my life. This this is BROKE AF.  I should be able to type in the box and see matching files. It just freezes and turns up nothing.  Breaks consistently within a few minutes of using VS. Was working fine in VS 2019.
