### ISSUE TITLE
Enable Cleanup Code tool for NTVS projects

### ISSUE THREAD

**Issue by fmoliveira** [codecadwallader/codemaid#107]
Every feature about CodeMaid is great, but Cleanup Code is a big fish for me because I really hate dirty and bad indented code (well, who doesn't?). I work a lot with both ASP.NET and Node.js projects, and the tool works very well for C# (code cleanup and auto indent), JavaScript, CSS and Sass files (only auto indent for the latter 3).

However, the Code Cleanup tool is disabled for NTVS projects, perhaps because it's a custom project type from extension [Node.js Tools for Visual Studio](https://github.com/Microsoft/nodejstools) and this project type might not be handled by CodeMaid yet.

I'm aware I won't have code cleanup tools for Node.js code because CodeMaid wasn't designed for that. But CodeMaid's auto indent is awesome and I'd love to be able to use that feature in my NTVS projects.

So, I'd like to ask @codecadwallader : Is it any interesting for CodeMaid to enable Auto Indent for NTVS projects? If agreed, I could contribute with this task. I don't have any experience playing around with CodeMaid source code anyway, so I'll accept any tips that might help me on the way.

Thanks in advance.

**Comment by codecadwallader** [comment]
Absolutely.  If they are JavaScript files, the trick is just associating the document language and project type GUIDs.

Away for the weekend, but three things to check:

1.  Turn on diagnostics mode within CodeMaids configuration.  When you have a file open it will report out the document language type if it is not recognized.  If you right click on a file in the solution explorer it will report out the project type GUID.   These will be shown in the Visual Studio Output tool window.

2.  Look at CodeCleanupAvailabilityLogic.cs for switch statements that handle document language and project item type detection.  Follow that pattern.  CodeCleanupManager also has a mapping of code language to clean ups performed.

3.  Check out http://www.codemaid.net/contribute for some tips on compiling and debugging.

Hope it helps, and thanks for offering to contribute. :)

**Comment by fmoliveira** [comment]
Hello @codecadwallader ! 

Thanks for the answer and for the valuable tips! They'll be of great help of course.

I'll follow your checklist and send a PR as soon as I'm ready. :wink:

**Comment by fmoliveira** [comment]
### Enabling code cleanup for Node.js files was successful

Just adding the "Node.js" value to switch case in `IsDocumentLanguageIncludedByOptions` method at `CodeCleanupAvailabilityLogic.cs` and in `FindCodeCleanupMethod` method at `CodeCleanupManager.cs` was enough to enable code cleanup in JS files from NTVS projects. That's the document language I've had from VS output window. I've tested this in the VS experimental instance and it works.

**Here is my commit if you want to check:** https://github.com/fmoliveira/codemaid/commit/9596ccd0aeba8678a1578fff667183ba7f491e61

### Can't find project type GUID, is that a problem?

I was unable to find any project type GUID by right clicking files in my solution, I'm not sure if this will impact anything. However, the method `IsProjectItemLanguageIncludedByOptions` at `CodeCleanupAvailabilityLogic.cs` will return `Cleaning_IncludeJavaScript` for all files with extension JS despite of its GUID to avoid confusion with the HTML language service. So, it seems like we don't have to take care of its GUID then?

### Things have gotten weird here

Ok then, but now I'm having a weird issue with `IsParentCodeGeneratorExcludedByOptions` method at `CodeCleanupAvailabilityLogic.cs`.

When I open a JS file from the root folder of my project, the method runs fine and I can do the code cleanup. But when I open a JS file from any subfolder, I've got a `InvalidOperationException` in the `Collection` property of `projectItem` just after opening the file. Take a look the image in the link below:

http://s15.postimg.org/ur7vbcp0r/nodejstools_exception.png

### Guessing what might be the problem

I've made a dumb test: If I wrap this if inside a try...catch block returning false on exception catch, it's enough to make the code cleanup work, but it'll prompt me about cleaning files external from solution, which is not correct because the file I'm trying to cleanup is included in my project.

I've seen you've wrapped a similar if block inside try...catch in `IsExternal` method at `ProjectItemExtensions.cs`, did you have any issues with this `Collection` property in the past?

### Perhaps we've got a NTVS project issue here

I'll keep trying to find out what's the root cause of this issue. One thing I suspect it's an issue with the NTVS project type, something like it's not returning the correct list of files included in the project. But I have no idea how a custom project file works, so, this is just a guess yet.

If this is a NTVS project bug, I think we might just wrap the `Collection` property inside a try...catch block so we don't get any crashes due to a NTVS project issue. But I'll check this out first.

**Comment by codecadwallader** [comment]
Cool, looks like a great start.  I replicated your changes to play with it and saw pretty much the same things you ran into.

In regards to the Node.JS language service GUID, I saw it reported the same as one of the existing JavaScript GUIDs (71d6... to be specific) - so no concerns there.

We've ran into other project types not having full support for the VS API.  In particular, the try/catch blocks in ProjectItemExtensions were originally workarounds for WiX project types.  It didn't have a problem with the Collection object, but it did have problems with the Kind property.

Following along on your suggestions, I made a GetParentProjectItem extension method.  That gets past the parent code generator check as you saw, but the test if a file is external to the solution is based upon looking at the container for the project item (i.e. the Collection) so that will require some further investigation.  I don't know much about NTVS, but perhaps it would be helpful to look at it from their side to see how they expect it to work, or if it's just not covered.

I published my edits to a new 'ntvs' branch here so we could collaborate: https://github.com/codecadwallader/codemaid/tree/ntvs

**Comment by codecadwallader** [comment]
And apologies for not just submitting a pull request to your fork.. that would have made more sense in retrospect.

**Comment by fmoliveira** [comment]
Oh, I see. Those are very valuable info!

Your new extension method is a more elegant way to avoid this exception, I agree that it's very plausible. So CodeMaid is doing the best job possible here. Perhaps that's enough for the CodeMaid side.

I'll have a look in NTVS side to investigate further on. They might need a patch too.

Don't worry about the pull request, that's just fine.

Thanks very much for helping, I'll keep you up to date as soon as I discover anything new!

**Comment by codecadwallader** [comment]
I'm working on adding support for PowerShell, and running into the exact same exception - so it does not appear to be unique to NTVS.  I still suspect it is an incomplete implementation of the API, but it looks like something CodeMaid will need to work around in order to add additional language support.

**Comment by fmoliveira** [comment]
I see. Just curious, are you using another custom project? Or just PowerShell scripts inside a default VS project?

Sorry for being so much away, I'll put some more effort on trying to help investigate it.

**Comment by codecadwallader** [comment]
There's an option to create PowerShell projects within Visual Studio, which is what I'm using.  I have published my changes to another branch (aptly called powershell).

No worries on being away, whenever you can help is wonderful.  Same goes for me, I can't be at this all the time! :)

I did find some old issues where we were having similar problems with PHP.  For that language, the PHPTools authors made updates to support it.  I don't think we'll have the same luck with PowerShell.

I'll keep you posted if I make any more headway, please do the same when/if you do any more investigation. :)

**Comment by fmoliveira** [comment]
So, it really looks like incomplete implementation of the API. Good to know the PHPTools authors were able to offer support it. Thanks for sharing this info. :smiley: 

I believe we can get that running in NTVS too, I'll let you know as soon as I get to analyse their code.

Oh I see, the default PowerShell projects, I think I've seen them before. Well, although Microsoft is diving deeper into Open Source, the obstacle would be getting that update to all the existing setups. We could get contact with the [.NET Foundation](https://github.com/dotnet)'s Team, but the process will probably delay for some long time.

If we're able to work on something to work around this issue it'd be great of course. :+1:

**Comment by codecadwallader** [comment]
Node.JS is now supported based on @fmoliveira 's original work.  See #175.

**Comment by codecadwallader** [comment]
This is present in the latest release, https://github.com/codecadwallader/codemaid/releases/tag/v0.8.8-alpha.  If you have the chance to test it and comment that would be greatly appreciated!
