### ISSUE TITLE
Reorganizing removes blank line between members

### ISSUE THREAD

**Issue by Daviziu** [codecadwallader/codemaid#108]
Hi
I regularly use CodeMaid's Reorganization tool, but there is a little bug that annoys me. After reorganizing my code, CodeMaid sometimes deletes a blank line that was there before. This is especially annoying because StyleCop marks the result as faulty.

I'm not exactly sure under which conditions this happens, but I made a quick example that reproduces this bug.

Before:
```csharp
      public string Source { get; private set; }

      public int? Line { get; private set; }

      public override string ToString()
      { [...]
```
After:
```csharp
      public int? Line { get; private set; }

      public string Source { get; private set; }
      public override string ToString()
      { [...]
```

I would really appreciate if you could change this in a future release.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  There is an existing card in the backlog to further refine the blank line logic around reorganization events here: https://trello.com/c/gryVGCYz

A very easy workaround in the interim is to run a code cleanup after reorganization, which will straighten up blank line padding.

Hope it helps.
