### ISSUE TITLE
Not Showing Regions for VB

### ISSUE THREAD

**Issue by ayseff** [codecadwallader/codemaid#112]
Hi.  This is a great tool!  Recently though, regions are no longer showing for VB, even though they once did.  Am I missing something?  I'm using VS 2013.  TY

**Comment by codecadwallader** [comment]
I'm away for the holidays so will take a look next weekend.  Do you know what version of CodeMaid you have now, and what version of CodeMaid you previously had where it worked as expected?  Also does it apply to all files, or is there a specific file where it is occurring?

**Comment by codecadwallader** [comment]
I took a look into this, and the syntax for VB regions differs from C#.  We haven't ever had support for VB regions.  I've added it to the backlog, please vote/comment further there: https://trello.com/c/7nuA0veH
