### ISSUE TITLE
Cleanup adds spaces in multidimensional array types

### ISSUE THREAD

**Issue by Daviziu** [codecadwallader/codemaid#114]
Hello,

The Cleanup function adds unnecessary spaces between the inner commas of a multidimensional array type. Afterwards StyleCop marks these as faulty.
Maybe this could be added as a new option in the 'Cleaning>Insert' configuration menu.

Before:
```csharp
   object[,,] a;
   object[,,,,] b;
```

After:
```csharp
   object[, ,] a;
   object[, , , ,] b;
```

**Comment by codecadwallader** [comment]
I believe that formatting comes from Visual Studioms formatting, which CodeMaid invokes and extends.  If you run Edit->Advanced->Format Document, do you see the same behavior?  If so you will want to look into Visual Studio's Tools->Options->Text Editor for settings to modify.

**Comment by Daviziu** [comment]
You're correct it is the way Visual Studio formats it.

I looked at the Spacing options (Tools>Options>Text Editor>C#>Formatting>Spacing), but I couldn't find an option that would change the behaviour I mentioned. There is an option called 'Insert space after comma', but it didn't fix my problem either. I am using Visual Studio 2012 by the way, not sure if it has been changed in newer versions.

**Comment by codecadwallader** [comment]
The behavior is the same in VS2013.  I also looked for some configuration options that would influence the behavior, but didn't see any obvious ones.  I would recommend raising a question on the MSDN forums to see if there are any suggestions: https://social.msdn.microsoft.com/forums/vstudio/
