### ISSUE TITLE
Space in operator overloading

### ISSUE THREAD

**Issue by Jaex** [codecadwallader/codemaid#119]
![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/ArC85VqlF8.png)

After "uint" VS2015 adds space and I can't find any setting in VS2015 code formatting or CodeMaid settings to not add space. Is CodeMaid can do something about it?

I think it can be bug in VS2015 because other overloading don't have this problem:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/07/he7fG29D5p.png)

**Comment by codecadwallader** [comment]
This space is being introduced by Visual Studio's formatting, which CodeMaid internally invokes.  You can see the same behavior by directly going to Edit->Advanced->Format Document.

I didn't see an obvious option for that spacing, looking at Tools->Options->Text Editor->C#->Formatting->Spacing.

I would recommend opening an issue on Microsoft Connect to see if they can offer any assistance about what (if any) configuration setting in Visual Studio would change that behavior.  If you have older versions of Visual Studio, it would be helpful to let them know if this behavior changed with VS2015 or it has been that way with previous versions as well.

Microsoft Connect link: https://connect.microsoft.com/VisualStudio

**Comment by Jaex** [comment]
This problem not exists in VS2013. I reported it using VS feedback tool now.

**Comment by Jaex** [comment]
They fixed it: https://github.com/dotnet/roslyn/issues/4240

**Comment by codecadwallader** [comment]
Cool, thanks for updating the thread for anybody else looking.
