### ISSUE TITLE
Solution-specific settings are not saved

### ISSUE THREAD

**Issue by dg9ngf** [codecadwallader/codemaid#120]
I just tried the new version 0.8 to use solution-specific settings. So I copied the CodeMaid.config file from AppData\Local next to the .sln file and also added it to the Solution Items virtual folder. The CodeMaid options dialog now starts in solution-specific mode. I can make changes and click the Save button (the dialog closes then) but my changes are not saved. When I open the dialog again, everything is like before.

What do I need to do to use solution-specific settings?

Also, I exported the settings after upgrading to 0.8 to compare my saved settings from 0.7. The file contents have changed greatly, there are much fewer entries. It seems that now only non-default values are serialised. Is this true? The order of items has changed so I can't compare the two files.

**Comment by dg9ngf** [comment]
More info: When I first switch to user settings, then change things and save, it is saved correctly, but only in the user settings. These changes then also apply to the solution-specific settings although they have not changed.

I have the impression that the solution-specific file is a NUL file. It is neither read nor written to.

**Comment by codecadwallader** [comment]
CodeMaid will create the solution-specific settings file for you.  Since you've manually created it, the file hasn't actually been loaded or detected (the check happens at solution open) - which is why you're seeing the odd behavior.  I believe if you were to close and re-open your solution, things would start behaving as expected.

Normally, to create solution-specific settings, simply go into CodeMaid->Options and click the "Switch to solution-specific settings" button in the header.  This will cause the file to be created once a setting has been saved and CodeMaid will be aware of its presence and work as expected.

And yes, we now only save the changed/delta values into the settings files.  The rationale behind that is so you can only put those settings that need to be overridden within a solution-specific settings file and all other settings will naturally inherit from your user settings.

**Comment by codecadwallader** [comment]
Hope that helps.  Closing the issue for now but please comment further to reopen if you have additional questions.

**Comment by dg9ngf** [comment]
Ehm, okay, so I need to keep my user settings as defaults for the solution-specific file to actually contain anything. Other people will have other user settings, so the diff writing doesn't lead to reliable results if they're not complete. And if the UI only writes a diff, I can't get a complete list of all settings that I care about. Seems non-functional for now.

**Comment by dg9ngf** [comment]
I do understand how the effective value is computed given the built-in defaults, the per-user, and the per-solution levels. The problem is that the per-solution settings are probably something that a team agrees on or a team leader requires to be used. This file must make sure that all regulated options are set to the defined value, no matter whether it's the built-in default. If this value is not included in the solution file, its effective value is influenced by whatever a particular user has chosen to use for their other projects in the per-user settings.

I noticed that the diff writing only seems to affect the initial conversion from pre-0.8. After that, every change is written to the file. So I went though all relevant settings, inverted them, saved, changed back, and saved again. This gave me a config file with all values that must be the same for everyone who works with this particular solution. Other settings like UI theming is not included as it does not affect the produced code.

To make things clearer, I think an additional override indicator might be useful. So the solution-specific settings would not only show the effective value and have it serialised to the solution-specific file on every change (which by the way cannot be reverted again afterwards), but instead two controls: A CheckBox that declares the override status of this setting, and the setting itself. If the override checkbox is not checked, the value control is disabled or read-only and shows the per-user value. If the override checkbox is checked, the effective value is always written to the file and doesn't need to be reversed twice first.

Do you know the TortoiseGit user config dialog? It has a selection for the config layer, the input text boxes, and an override/inherit checkbox for each text box. That makes it obvious what data is coming from where.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  There are about 160 different settings, so I'm not sure what a UI would look like if every one of those settings had multiple UI elements associated with it.  Do you have a screenshot of TortoiseGit?

**Comment by dg9ngf** [comment]
Here's a combined screenshot of the different levels selected:

![tortoisegitconfiglevels](https://cloud.githubusercontent.com/assets/868315/8823255/a2267e68-306b-11e5-9500-3c02008d483d.png)
