### ISSUE TITLE
Comment formatting, element line splitting

### ISSUE THREAD

**Issue by dg9ngf** [codecadwallader/codemaid#122]
Just tried the comment formatting and it gave me mixed and unexpected results. I have the following XML comments schemes for methods or multi-line members, and for short enum values:

    /// <summary>
    /// Description of the method.
    /// </summary>
    /// <param name="a">Description of parameter a.</param>
    /// <param name="b">Description of parameter b.</param>
    /// <returns>Some more text.</returns>
    public void ExampleMethod(int a, int b)

    public enum EnumType
    {
        /// <summary>This means XYZ.</summary>
        Xyz,
        /// <summary>This means ABC.</summary>
        Abc,
        /// <summary>This means F12.</summary>
        F12,
    }

I wasn't able to keep those with CodeMaid. With the option "Always split `<summary>` tags onto multiple lines" disabled, most (not all) `summary` elements were collapsed to a single line. Especially those in longer comment blocks were still on multiple lines. With that option enabled, all elements were expanded to multiple lines like so:

    /// <summary>
    /// Description of the method.
    /// </summary>
    /// <param name="a">
    /// Description of parameter a.
    /// </param>
    /// <param name="b">
    /// Description of parameter b.
    /// </param>
    ...

So the option seems to affect other elements than advertised. I'd wish for a set of options like this:

* Split `<summary>` tags onto multiple lines for multi-line members<br>
  This should only split them if they're not split, but never combine them in a single line if unset.
* (not sure what other options would be helpful to complement this)

I have no idea what "Keep XML tags together" is supposed to do. It doesn't change the preview in any way. I can't try it out because the multi-line option already changes everything and makes my diff very long.

**Comment by codecadwallader** [comment]
I'm not sure I follow everything you're trying to report.  Parts of it sound similar to #113 so please take a look at that if it helps answer some of your questions.

**Comment by dg9ngf** [comment]
Now I know what "Keep XML tags together" is for. But it's not relevant here.

I have comments like in my first code sample above. I want to keep them as-is. What CodeMaid options will give me that? I've tried some but I always get things like in my second code sample above.

**Comment by codecadwallader** [comment]
I'm still not sure I follow.  If the 'Always split summary tags onto multiple lines' option is enabled (default), then it will always split them up.  If that option is disabled, then the formatting logic allows summary tags to be consolidated like all other tags.  Perhaps you could generate a new feature request on the backlog restating the additional option(s) you want?

**Comment by dg9ngf** [comment]
Could you please re-read my initial comment? I discovered that GitHub was eating up some XML tags in it so I marked them as code to keep them visible. Maybe this is what you were missing.

**Comment by codecadwallader** [comment]
It sounds like you want additional configuration options around the comment formatting logic so that it formats summary (and other?) tags in a specific way based on the number of lines of code on the member that it is decorating.  We do not currently have any comment formatting options that are member size specific, so that would be a new feature request which is welcome on the public backlog here: https://trello.com/b/VVxVhbQv/backlog  Perhaps it could be called something like "Different comment formatting options for single-line vs. multi-line members"
