### ISSUE TITLE
No blank line padding before single line comment for C++

### ISSUE THREAD

**Issue by yedey** [codecadwallader/codemaid#123]
Even when checking "single-line comments" under "insert blank line before", on cleanup of a C++ source file there is no blank line inserted. (VS2015)

**Comment by codecadwallader** [comment]
This functionality currently only works with C#, but I think it could be easily extended to cover C++ and other similar languages.  I'll take a look into extending it.

**Comment by yedey** [comment]
Thanks

**Comment by codecadwallader** [comment]
Yep, it was pretty straight-forward.  This will be present in the next release.  Thanks again for reporting.
