### ISSUE TITLE
An exception occures during navigation via CodeMaid Spade

### ISSUE THREAD

**Issue by Deffiss** [codecadwallader/codemaid#124]
Hello,
I've got an Exception when use CodeMaid Spade for navigation purposes "The parameter is incorrect". Steps to reproduce:
1. Open a *.cs file
2. Open CodeMaid Spade
3. Choose one of the members and do "Find references" for it
4. In "Find symbol results" click once on the concrete usage of the member from the other file. This switches the active document but CodeMaid Spade still shows the information about the previous one.
5. Try to do "Find references" again to get the Exception:
![untitled](https://cloud.githubusercontent.com/assets/9148895/8822144/fc7c8650-306b-11e5-9a1e-46e270d2fdad.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have reproduced it.  When a preview window is active, it doesn't trigger an update to Spade which is still displaying the actual document that is opened.  By following your steps, I see the exception dialog and then a refresh is triggered within Spade.

It seems to me like we need to better capture IDE events reporting that a preview window has taken active focus.  I'll look into it.

**Comment by Deffiss** [comment]
Actually, I think it could be better to keep the same behavior for this. I mean not to refresh  CodeMaid Spade right after clicking and keep the list of members for the source class. In this case it would be a nice tool for investigation of concrete class. Of cause, with the ability to do "Find references" again and without errors :)

**Comment by codecadwallader** [comment]
That makes sense, and it was pretty easy to just update the find references logic to re-activate the document being displayed by Spade.  This fix will be present in the next release.  Thanks again for reporting it.
