### ISSUE TITLE
Remove unused usings Inserts blank line in usings since upgrading to v0.8.0 (VS2013 C# code)

### ISSUE THREAD

**Issue by nodsi** [codecadwallader/codemaid#125]
I have CodeMaid setup to re-insert the following usings:
using System;
using System.Collections.Generic;
using System.Linq;
and to remove unused using statements. I also have the insert blank line padding before & after "using statement blocks" crossed out.
Yet since upgrading to v0.8.0 when saving the following in a file:
using System;
using System.Collections.Generic;
using System.Linq;

namespace ...
It saves it as:
using System;
using System.Collections.Generic;

using System.Linq;

namespace ...
If I move System.Linq above using System.Collections.Generic; it correctly re-orders them and doesn't insert a blank line before the last using statement.

Screen shots of relevant settings attached.
Thanks for any help on this issue.

![image](https://cloud.githubusercontent.com/assets/13449488/8822578/59e4bbea-305e-11e5-9838-707a2535b3db.png)
![image](https://cloud.githubusercontent.com/assets/13449488/8822590/6bd87bf2-305e-11e5-9502-2b4c78142a8a.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I believe this is a consequence of the fixes made for v0.8.0 to handle a scenario reported in #87.  At the time I wasn't able to find a clean way to prevent an extra new line from getting inserted under certain scenarios, but it was an improvement over a potential scenario where a using statement would incorrectly be added twice.  I'll look into it again.

**Comment by codecadwallader** [comment]
I don't have anything new for this issue, I believe it's something that should be revisited in the future with Roslyn as mentioned on #87.  Closing for now.
