### ISSUE TITLE
VS 2015 Error Dialog Shows When Selecting CodeMaid Tab

### ISSUE THREAD

**Issue by tomdbarker** [codecadwallader/codemaid#128]
Hi,
in VS2015, When selecting the CodeMaid tab to view the contents list of a file for the first time I am shown an error dialog, which directs me to a log file xml file in AppData folder. The error in the log file is always the same:

"System.InvalidOperationException: Unexpected false&#x000D;&#x000A;   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource'1.GetTagIntervalTreeForBuffer(ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Shared.Tagging.AsynchronousTagger'1.GetTags(NormalizedSnapshotSpanCollection requestedSpans)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator'1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()"

Hope you can get this fixed :)

Thanks.

**Comment by codecadwallader** [comment]
Thanks for reporting.  We did start seeing this with the RC and were hoping it would be resolved in the RTM last week, but it is still present.  We're tracking this under #118
