### ISSUE TITLE
Extra line between method head and body

### ISSUE THREAD

**Issue by dg9ngf** [codecadwallader/codemaid#130]
This

```csharp
void Method() { x = 5; }
```

Becomes this

```csharp
private void Method()

{
    x = 5;
}
```

The additional line between the method head and its body is not supposed to be there. It only seems to appear when a method both

1. is in one line which will be expanded, and
2. does not have an access modifier which will be added.

I don't write code like the first sample but I've just run CodeMaid on external code and noticed this strange formatting.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have reproduced it and will take a look.

**Comment by codecadwallader** [comment]
A cached value was being used for determining if the method was on a single line.  When the access modifier is added, the method body is automatically moved to the following line by Visual Studio.

The code will no longer introduce a blank line, so the end result will be:

```c#
private void Method()
{ x = 5; }
```

It would be a nice enhancement if the method body being on a separate line than the method signature still triggered the update single line methods logic.  Card added to backlog: https://trello.com/c/BnKxckdO
