### ISSUE TITLE
Cleaning up Code removes breakpoints

### ISSUE THREAD

**Issue by TonyValenti** [codecadwallader/codemaid#132]
Please preserve breakpoints when code is cleaned up.

Thanks!

**Comment by codecadwallader** [comment]
Breakpoints are generally tied to lines of code, so depending on the type of code change that is being applied, breakpoints can be lost.  The same behavior happens natively with Visual Studio, for example if you cut and paste a line of code, the breakpoint will be lost.  Trying to know where the breakpoint should be re-applied would be very scenario specific.

If you have a specific code scenario in mind, please feel free to open a specific request with a code sample on Trello here: https://trello.com/b/VVxVhbQv/backlog
