### ISSUE TITLE
VS 2010 click once install build failes

### ISSUE THREAD

**Issue by DavidLen** [codecadwallader/codemaid#134]
VS 2010

After installing codemaid, creating a new install kit (click once) using the 'publish now' button fails, the error is that 'build failed'

However, building the project manually does not fail.

Disabling codemaid allows the install kit to be created.

**Comment by codecadwallader** [comment]
If you re-enable CodeMaid, and turn on diagnostics - do you see any meaningful error messages?  Diagnostics can be turned on at CodeMaid->Options->"Diagnostics mode" and will push messages to the Output window.

**Comment by DavidLen** [comment]
Odd, did just that and this time no problem, the only difference was that there were no code changes (I just created a new installer), and so no compilation.

I'll keep CdeMaid on and see what happens next time I release an upgrade.

**Comment by codecadwallader** [comment]
Glad to hear it is working for you now.  I will close this issue out, but if it resurfaces feel free to comment and we can reopen it.

As a heads up, we are planning to cease support of VS2010 going forwards with the next major release (v0.9.0).  The CodeMaid v0.8.x series will continue to be available for VS2010 though.
