### ISSUE TITLE
CodeMaid gets stuck on WSDL reference.cs when running "Clean up all Code"

### ISSUE THREAD

**Issue by joshbouganim** [codecadwallader/codemaid#135]
Hello,

I ran "clean up all code"  and it got stuck on WSDL reference file (reference.cs).  I tried clicking cancel  which changed the button text to "canceling..."  but nothing happened.  eventually VS crashed.

i am running latest version of vs 2015 with the latest version of your plugin.

screenshot:

http://snag.gy/rZnMP.jpg

just checked, its a 40000 line file.  Might have something to do with it :).  but the cancel button should work properly...

**Comment by codecadwallader** [comment]
The cancel button marks a batch operation to stop at the end of the current file, but will not abort during the middle of the processing of an individual file as that could leave the code in a bad state.

The highest file size we've tested with is ~10,000 lines, and that usually takes 2-3 minutes to resolve.  I suspect with a 40,000 line file, it would probably take at least 10 minutes to process the file.

I'd highly recommend adding that file to your exclusions list.  We have it on our backlog to try to detect more auto-generated files like that so they are ignored from cleanup: https://trello.com/c/WTkal55t

**Comment by joshbouganim** [comment]
thanks i added reference.cs to the exclusion list.  can i vote on the card or only contributors?

**Comment by codecadwallader** [comment]
It's a public backlog and open source project - please feel free to vote, comment, fork, etc!
