### ISSUE TITLE
Clean All Code error

### ISSUE THREAD

**Issue by AlkindiX** [codecadwallader/codemaid#137]
Hi Steve,
There are a problem when I click Clean All Code. An error message said that
Could not load file or assembly 'Microsoft.VisualStudio.Package.LanguageService.10.0' version=10.0.0.0 ...' then The system cannot find the file specified
I checked the Diagnostics mode on and there are no faulty massage on the output. I am using Visual Studio 2013 in C# project

**Comment by codecadwallader** [comment]
Which version of CodeMaid are you using?

**Comment by AlkindiX** [comment]
I'm using the latest version of CodeMaid v0.8.0.1 beta

**Comment by codecadwallader** [comment]
Was this previously working with CodeMaid v0.8.0?  Do you see the same behavior if you upgrade to CodeMaid v0.8.1 (functionally equivalent to the beta you have installed)?  Do you have any versions of the Visual Studio SDK installed?

**Comment by AlkindiX** [comment]
Yes the same problem on the previous one on v0.8.0

**Comment by codecadwallader** [comment]
Starting with v0.8.1 we are using VS2015 to build the installer.  It has started explicitly including that DLL you referenced within the installer, which was not present in earlier versions (e.g. v0.8.0).  If this feature was working with you with older versions, then I was suspicious that might be the source of the problem.  However, if it was not working before either then I don't think that is the case.  Has that functionality ever worked for you in a previous version of CodeMaid?

**Comment by codecadwallader** [comment]
FWIW: I'm testing against VS2013 Update 5 (12.0.40629.00 Update 5)

**Comment by AlkindiX** [comment]
Hi Steve
I will try to install previous version of CodeMaid and see if it worked probably

**Comment by AlkindiX** [comment]
Hi Steve
I've installed CodeMaid 0.7.5. The Clean up all code not worked. And the same problem with latest release 
![untitled](https://cloud.githubusercontent.com/assets/6407635/9232150/0d4b57cc-413d-11e5-8615-ce695b57ae04.png)

Moreover, I performed repair for Visual Studio 2013 ,reset all Visual Studio setting, uninstall Visual Studio 2013 SDK and uninstall unnecessary plugins.

CodeMaid diagnostic output:

`[CodeMaid Diagnostic 09:59:39 م] CleanupAllCodeCommand.OnExecute invoked`

## I have an idea

When turn on diagnostic mode, you can handle First chance Exceptions and draw them in the output

**Comment by codecadwallader** [comment]
Thanks for the screenshot, that helps.  This reminds me of a bug that occurred when VS2013 was first released.  Microsoft addressed it in Update 2, so please be sure that is installed.

More details here: https://bitbucket.org/s_cadwallader/codemaid/issues/220/vs2013-cleanup-all-code-shows-error

**Comment by AlkindiX** [comment]
Hi @codecadwallader 
 Thank you for your advise. I never update Visual Studio 2013. I will update Visual studio if I have unlimited internet  bandwidth
