### ISSUE TITLE
switching doesn't work for cpp/h files when they are not in the same folder

### ISSUE THREAD

**Issue by jonygli** [codecadwallader/codemaid#140]
switching doesn't work for cpp/h files when they are not in the same folder

**Comment by codecadwallader** [comment]
Correct, the files are required to be in the same folder for the switching feature to work.  The code base is open if you would like to work on adding support for files in separate folders, or you may request a feature on the public backlog to see if anybody else takes it up here: https://trello.com/b/VVxVhbQv/backlog
