### ISSUE TITLE
Reorganize solution

### ISSUE THREAD

**Issue by ShadowDancer** [codecadwallader/codemaid#144]
Hello,
is there any good reason for absence of "reorganize solution" button?

**Comment by codecadwallader** [comment]
There's an option to "Run reorganize during cleanup".  If you enable that, then you can run "Cleanup All Code" to reorganize the solution.

**Comment by ShadowDancer** [comment]
Thanks, I am happy that it's possible, however IMO it would be more intuitive to enable this button in solution explorer.

**Comment by codecadwallader** [comment]
Understandable, but there's also been other users requesting to remove buttons altogether from the solution explorer toolbar, so it's a tough balance to strike.  We've also discussed adding more configuration options to control which buttons are visible, but that wasn't a very popular option so it hasn't gone any further.

More details can be seen on the public backlog in Trello here: https://trello.com/b/VVxVhbQv/backlog  You can also request new features there as well, such as adding that button, to see how much support there is from the community.
