### ISSUE TITLE
Visual Studio 2015 crashes on renaming when Automatic Cleanup On Save is on

### ISSUE THREAD

**Issue by horsedrowner** [codecadwallader/codemaid#145]
**Steps to reproduce:**

1. Turn on CodeMaid > Automatic Cleanup On Save 
2. Rename a method or other member using the Rename/F2 function and hit Apply

Visual Studio will show a "Updating files..." dialog, and the status bar will rapidly flash "CodeMaid is reorganizing <file>" before crashing with a "Visual Studio 2015 has stopped working" message. The affected files are not saved.

Turning off "Automatic Cleanup On Save" will cause the rename function to behave properly.

I'm using Visual Studio Community 2015, version 14.0.23107.0 D14REL, CodeMaid version 0.8.1. This has happened to me in various C# projects. I have not tried any other languages.

I don't if there are any log files or where they would be, or what other details would be relevant. Please let me know if you need more information.

**Comment by codecadwallader** [comment]
Please take a look at #142 as this sounds very familiar.  If that doesn't resolve your issue, can you please reopen this with a copy of your settings.
