### ISSUE TITLE
Existing Regionerate-Regions are not removed

### ISSUE THREAD

**Issue by casiosmu** [codecadwallader/codemaid#147]
Previous I used Regionerate, which inserts a 'magic' invisible char after the `#region` tag and the region name.
Here the hex-View:
![unbenannt](https://cloud.githubusercontent.com/assets/5816476/9518361/7970f8c4-4cb6-11e5-9f8e-4881c4b64735.PNG)

I have set that the regions should be removed and recreated, but instead CodeMaid wraps another region around or inside the existing one.
If I insert a space after `#region` it works as expected.

I use CodeMaid 0.8.1 on VS2010Prof

**Comment by codecadwallader** [comment]
I think having a non-space character after the `#region` tag causes it to be invalid syntax, at least from the way I read the C# language spec.  I would suggest doing a global find/replace of those characters and turning them into spaces.  Is there any reason to keep them in that non-space character if you are no longer using regionerate?

**Comment by casiosmu** [comment]
hmm, for VisualStudio it seems valid.
Regionerate used them for recognizing their 'own' regions (see http://www.rauchy.net/regionerate/docs/2007/11/what-are-symbols.html )
For me there is no reason to keep them, but find/replace may be a problem
first because the character ist not visible in VS, and second it had to be done for every single project.

**Comment by casiosmu** [comment]
Ok, I think I'm fine with the find/replace solution.
But still, it would be nice, if CodeMaid could cope with that.
Thanks a lot for your work.

**Comment by codecadwallader** [comment]
You're welcome, thank you for saying that.

I'm glad to hear the find/replace solution will work for you.  I agree it would be nice to handle, but the backlog is pretty deep so it probably wouldn't get prioritized very soon.
