### ISSUE TITLE
CodeMaid settings location

### ISSUE THREAD

**Issue by AeroClassics** [codecadwallader/codemaid#148]
I am using CodeMaid for clean up, StyleCop and Codeit-Right for standards analysis. I would like to have the setting for CodeMaid portable with the solution so everyone is running from the same settings. Is this possible? And where would I fins the CodeMaid settings file so I can put in the solution root folder?

Thanks!
Doug

**Comment by codecadwallader** [comment]
Yes, as of CodeMaid v0.8.0 we now support solution-specific options.  To turn them on, simply go into CodeMaid->Options and click the "Switch to Solution-Specific Options" button in the header.  From that point on, any changes you make will be captured within a Solution-Specific file called "CodeMaid.config" within the same directory as your solution so it can be persisted in source control.

Please note: only the delta settings are captured (i.e. only those things you chose to override).  If you really want to enforce every single setting is identical then you can get a full export of the settings from here: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/app.config

Hope it helps.  Please comment if you have any further questions.

**Comment by AeroClassics** [comment]
Thanks! Perfect!

Best Regards, 
Doug





 
Douglas R. Jones
Sr. Software Eng./AdVISE Product Mgr.
Rohde & Schwarz USA, Inc.
1500 Lakeside Pkwy.
Suite 100
Flower Mound, TX 75238
, 
Mobile: +1 214-601-3301
Office: +1 469-713-5344
E-Mail: Doug.Jones@rsa.rohde-schwarz.com
Website: http://www.rohde-schwarz.com/
