### ISSUE TITLE
On cleanup (project, solution, selected) Javascript does not run "format document"

### ISSUE THREAD

**Issue by jolsa** [codecadwallader/codemaid#155]
Just downloaded this and mostly love it.  But one thing I needed was to run "format document" on all of my Javascript files.  Running cleanup on the currently open Javascript file does this, but I need the whole project.

Is this a bug, oversight, or am I doing something wrong?

**Comment by codecadwallader** [comment]
Glad to hear you mostly love it. :)

You can right click on a project within the solution explorer and choose "Cleanup Selected Code" to cleanup all files within the project.  If you only want JavaScript files (e.g. do not want HTML/CSS files to be modified) then you can change that within CodeMaid->Options->File Types.

Hope it helps.  More details here: http://www.codemaid.net/documentation/#cleaning

**Comment by jolsa** [comment]
I found that feature, but it doesn't solve my problem.  We have some sloppy code files (many, many of them) and we were looking for a tool that could open each file and execute the "format document" command on each file without writing our own.  Code maid does that, but for some reason not on Javascript files.  It is opening them and doing all of the cool extra things "cleanup" is configured to do, except "format document".  It's formatting the C# files, HTML, and XML files as well as the other nice features Code Maid offers, but it's not formatting the Javascript.  However, if I open a single file and execute "Cleanup" it does reformat the document.

**Comment by codecadwallader** [comment]
Continued on #156
