### ISSUE TITLE
Support for formatting doxygen comments

### ISSUE THREAD

**Issue by elementalest** [codecadwallader/codemaid#157]
It would be good to have basic support for doxygen comments. Currently when you format doxygen comments, it simply creates a paragraph chunk. For example this:

/// Ouput stream operator overload. Outputs the Point in the format "(x,y)" without
/// quotations.
///
/// @param out
///   Output stream.
/// @param pt
///   Point to output.
/// @returns Output stream \p out.

becomes:

/// Ouput stream operator overload. Outputs the Point in the format "(x,y)" without
/// quotations. /// @param out Output stream. @param pt Point to output. @returns
/// Output stream \p out.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  We accept feature requests on our backlog, which is hosted on Trello as it supports voting.  I've created a card for your suggestion here: https://trello.com/c/PPmvUlXm
