### ISSUE TITLE
Cleanup should insert additional empty line between groups of same type/access

### ISSUE THREAD

**Issue by epsitec** [codecadwallader/codemaid#159]
In my current (manual) source code layout, I visually group items which have the same type and access, like this:

```c#
public string GetFoo()
{
    return "foo";
}

public int GetBar()
{
    return 1;
}


public static string GetGlobalFoo()
{
    return "global";
}


private System.DateTime GetDate()
{
    throw new System.NotImplementedException ();
}
```

Notice the additional empty line between the group of public methods and the group of public static methods. And then also between the group of public static methods and the group of private methods.

I suppose that there is currently no setting which enables this feature. Would this be something you'd be ready to work on?

**Comment by codecadwallader** [comment]
You're right, there are not currently any settings to customize the number of blank lines between groups.  We have a pretty large public backlog, which you're welcome to contribute to here: https://trello.com/b/VVxVhbQv/backlog  It is also, of course, an open source project and contributions are welcome.
