### ISSUE TITLE
Align fields and property names

### ISSUE THREAD

**Issue by epsitec** [codecadwallader/codemaid#160]
I try to keep my fields and my properties aligned, so that I can better read my soure code:

```c#
private int             age;
private double          weight;
```

When cleaning up a source file, these extra spaces get removed.

Is there some option I overlooked, which would allow me to tell CodeMaid not to touch these spaces?

Better yet, would you consider adding a feature to align the fields and properties at a given column?

**Comment by codecadwallader** [comment]
The removal of white spaces comes from Visual Studio's formatting, which CodeMaid invokes.  If you disabled CodeMaid's invocation of Visual Studio formatting that would no longer occur, but you would lose all of the other formatting that Visual Studio provides as well.

I believe you can change the following property to cause Visual Studio to ignore those spaces: Tools->Options->Text Editor->C#->Formatting->Spacing->"Ignore spaces in declaration statements".

To go further and automatically cause alignment, again a card would be welcome in the backlog as I don't think we have an existing one: https://trello.com/b/VVxVhbQv/backlog
