### ISSUE TITLE
Customize how C# using statements are grouped

### ISSUE THREAD

**Issue by epsitec** [codecadwallader/codemaid#161]
I have been trying to group using statements together, based on their first namespace component (e.g. `Epsitec`, `Microsoft`, `System`, etc.), like this:

```c#
using Epsitec.Lydia.Data.Queries;
using Epsitec.Lydia.Host.Services.HubProxies;
using Epsitec.Lydia.Json;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
```

CodeMaid cleans up and scrubs also my empty lines. Can I configure it to keep the empty lines?

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I believe there is an existing card on the backlog here: https://trello.com/c/AXK4SaJN
