### ISSUE TITLE
CodeMaid Spade window is empty for js file

### ISSUE THREAD

**Issue by paulFPF** [codecadwallader/codemaid#167]
I am looking for a tool to give me a list of functions and properties declared in my Javascript file (.js).
I heard CodeMaid would do this.
But the CodeMaid panel on the right is empty when a js file is the selected editor window.
Is there something that needs to be configured or does CodeMaid not work with js files?

**Comment by codecadwallader** [comment]
CodeMaid does support JavaScript cleanup and other operations, but the Visual Studio API does not expose a list of members for JavaScript which is how CodeMaid presents a list of members for C#, VB and C++.  So no, unfortunately CodeMaid will not currently give you a list of members for JavaScript files.
