### ISSUE TITLE
Move Types into Matching Files

### ISSUE THREAD

**Issue by GustavoAmerico** [codecadwallader/codemaid#169]
creates dedicated files for each of  types, in same file, and moves them there.

**Comment by codecadwallader** [comment]
This sounds like a new feature request.  We accept those on Trello.  I think yours may already exist, but it could use some more description as I'm not exactly sure what you're requesting.

Please take a look at this card: https://trello.com/c/c9iNMuaK  and if that isn't what you're asking please add some more details on the main card: https://trello.com/c/1IQl1f7t
