### ISSUE TITLE
Add option to automatically tabify/untabify on Cleanup/Save

### ISSUE THREAD

**Issue by d0ru** [codecadwallader/codemaid#171]
Some (old) files contain tabs, but the (current) Visual Studio global setting is to replace tabs with spaces(2). CodeMaid correctly catches this and offers to "Untabify" the files when opened.  :+1: 

... but automatic "Cleanup all code.." doesn't!

**Comment by codecadwallader** [comment]
> offers to "Untabity" the files when opened.
I think this is a different extension, such as the Productivity Power Tools.  That isn't a CodeMaid feature.

We do have a backlog card to replace tabs with spaces.  Several languages (e.g. C#) do this automatically but some other (e.g. XAML) do not.  You can see/vote for that card here: https://trello.com/c/lpsRHlQa
