### ISSUE TITLE
Format Comment isn't supported for F# files

### ISSUE THREAD

**Issue by dmich2** [codecadwallader/codemaid#173]
For formatting F# `//` or `///` comments it looks like all you'd need to do is change:
https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Helpers/CodeCommentHelper.cs#L119-L120
to add "FSharp" case.
That wouldn't handle `(* ... *)` style comments but *would* handle the typical case of function/member/class documentation comments.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have reproduced it.  You're right the comment prefix mappings are out of date, I will get that updated.

Spade support for F# (in your original title) is dependent on a code model exposed by Visual Studio.  Currently only C#, VB and C++ expose functional code models so those are the supported languages.  You may add a card to the public backlog on Trello (https://trello.com/b/VVxVhbQv/backlog) but without the underlying data being exposed from VS we won't have a good way to implement it.

I'm tweaking the title of the card to represent the primary thing you mentioned, comment formatting, which will be addressed.

**Comment by codecadwallader** [comment]
This has been addressed - thanks again for reporting it!

**Comment by codecadwallader** [comment]
This is present in the latest release, https://github.com/codecadwallader/codemaid/releases/tag/v0.8.8-alpha.  If you have the chance to test it and comment that would be greatly appreciated!
