### ISSUE TITLE
PowerShell Format Comment Block support

### ISSUE THREAD

**Issue by bcdady** [codecadwallader/codemaid#177]
Enhance Format Comment functionality to handle comment blocks in PowerShell files

example
<#
     this is a comment
            block that should be reformatted
line 3 of comment
   #>

The following is how I like a function/script's help comment block to look. This one was generated using the New-CommentHelp function (part of the PowerShell ISE add-on 'ISEScriptingGeek' by @JeffHicks), then formatted/intended for my preferred readability.

    <#
        .SYNOPSIS
            Synopsis of Function-Name. Think of it as the Executive Summary, or Abstract of the following full Description.
        .DESCRIPTION
            Detailed Description.
            This is often a 
            multi-line 
            or even multi-paragraph 
            text/string block
        .PARAMETER param1
            First Paramater
        .PARAMETER param2
            Second Parameter
        .EXAMPLE
            PS C:\> Example 1, ideally with command line sample
            After the example, explain how, why this example works.
        .NOTES
            NAME        :  Function-Name
            VERSION     :  0.1.0.0   
            LAST UPDATED:  11/1/2015
            AUTHOR      :  Author's Name
        .LINKS
            None
        .INPUTS
            None
        .OUTPUTS
            None
    #>

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  We do have a card for block comment support in our backlog which you can vote up/comment on here: https://trello.com/c/Xlz1eilj

We currently track all new feature requests over on Trello (since it supports voting and has a nicer visual display) and all bugs here on GitHub.
