### ISSUE TITLE
List XML comment tags option for new line formatting

### ISSUE THREAD

**Issue by isaacllopisaracil** [codecadwallader/codemaid#179]
There is no new line option formatting per tag, therefore CodeMaid either allows for _every_ xml tag to be in new lines or _none_. When formatting lists this is counter productive.

```
/// <summary>
/// Look at this list:
/// <list type="bullet">
///    <item><description>My description.</description></item>
///    <item><description>Other description.</description></item>
/// </list>
```
Is transformed into
```
/// <summary>
/// Look at this list: <list type="bullet"><item><description>My
/// description.</description></item><item><description>Other description.</description></item></list>
/// </summary>
```

My suggestion is that in CodeMaid Options > Formattings, we can split _certain_ tags always into multiple lines, selecting the ones that should be split (in this case, **list** and **item**, but not **description**, for example).

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  We do have a card on the backlog to support XML list tags.  Please take a look, vote/comment further here: https://trello.com/c/8PjGOadD
