### ISSUE TITLE
Cyclomatic complexity is not calculated correctly

### ISSUE THREAD

**Issue by iac249** [codecadwallader/codemaid#189]
Example: A method containing only an if-else statement should have a complexity of 2, but CodeMaid calculates it as 3.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, and you're correct.  CodeMaid's complexity calculation is very much a rough approximation, not a true calculation.  We added it several years ago and it's largely based on counting control keywords.  You can see the actual implementation here: https://github.com/codecadwallader/codemaid/blob/125dfc83fb1173025ef87fc5baa1690cb86e4fed/CodeMaid/Helpers/CodeElementHelper.cs#L31-L67

We do have an existing card in our backlog to look at rewriting the calculation, especially if there's anything newly available in Roslyn that we can utilize vs. trying to calculate it ourselves.  Please vote up and comment further on that code here: https://trello.com/c/wlC1l3RB
