### ISSUE TITLE
Synchronize outlining feature doesn't work in VS 2015 Community

### ISSUE THREAD

**Issue by hinst** [codecadwallader/codemaid#195]
It appears that "Synchronize outlining with the code file" feature does not work with VS 2015 Community.
Unless I am mistaken in thinking that "Synchronize outlining" is supposed to select class member according to caret position. Right now it seems like it does nothing. When I move caret, selection in the Outline panel remains unchanged

**Comment by codecadwallader** [comment]
Outlining refers to the expanded/collapsed state of regions.  Sorry for any confusion, that's the terminology within the Visual Studio API.

There is a card on our backlog for having the current member in Spade be auto-updated based on the cursor location, which is what I think you were expecting.  You can vote up that card here: https://trello.com/c/j7DTRXsy
