### ISSUE TITLE
Collapsed Branch in Spade should stay Collapsed 

### ISSUE THREAD

**Issue by JeffStuy** [codecadwallader/codemaid#196]
Just an opinion but, in Spade, when sort by type is on, if I collapse, for example, fields, it should stay collapsed until I un-collapse it.  Now, anything that causes a re-fresh of Spade, automatically un-collapses all of the branches.  This is quite annoying as it pushes methods way to the bottom or out-of-view.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  When sorting by file order, we offer code outlining synchronization which maintains collapsed/expanded state by synchronizing it with the editor window.  When providing custom sort orders (by type, by name) we don't currently have any approach to persist the state.

I've added a card to our backlog for this feature.  Please vote/comment further there: https://trello.com/c/8Onm40SO
