### ISSUE TITLE
Unwanted (blank) line keeps reappearing

### ISSUE THREAD

**Issue by Clockwork-Muse** [codecadwallader/codemaid#197]
For some reason, I can't get rid of a blank line in one of my source files.  It just keeps coming back.  I'm not seeing any likely culprits in the settings, and VS doesn't add the line if CodeMaid is off.

Specifically:
```
// Internal field references to verify internal exceptions are actually handled.
private static readonly FieldInfo m_contingentPropertiesField = typeof(Task).GetField("m_contingentProperties", BindingFlags.NonPublic | BindingFlags.Instance);
// This line is really blank, keeps coming back
private static readonly FieldInfo m_exceptionsHolderField = m_contingentPropertiesField.FieldType.GetField("m_exceptionsHolder", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
private static readonly FieldInfo m_isHandledField = m_exceptionsHolderField.FieldType.GetField("m_isHandled", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
```

I'm mystified.  Swapping lines doesn't seem to make a difference (even though doing so would yield a compiler error).  Strangely, the blank line can be swapped to just after the first comment, and the 3 fields will stay together.  My line endings appear to all by CRLF, and attempting to make them conform seems to have no effect.

**Comment by codecadwallader** [comment]
By default, blank line padding is inserted before and after multi-line fields.  In the code sample above, when a comment directly precedes a field it is considered a part of the field so it is counted as a multi-line field - similar to what would happen if the initializers were placed on following lines.

You can disable those two settings (both before and after) under CodeMaid->Options->Cleaning->Insert.

Hope it helps, please comment if you have any follow-on questions.
