### ISSUE TITLE
Reordganize code not enabled when source file contains pragma's

### ISSUE THREAD

**Issue by Gordon-Beeming** [codecadwallader/codemaid#200]
Hi

I have code like this one of my classes (yes it's bad code but) when I remove this the reorganize is enabled and then is able to execute as part of my clean up. Is there any technical reason why this is like this?

#if DEBUG
        protected string currentUser = "Bob";
#else
        public string currentUser = HttpContext.Current.User.Identity.Name;
#endif

Thanks =D

**Comment by codecadwallader** [comment]
Yes, starting in v0.7.5 we began deliberately checking for preprocessor directives and disabling reorganization when they are present.  The reason for this is that the code model we are currently using does not expose preprocessor directive information.  Without that check, CodeMaid would move members in/out of preprocessor directive blocks - for example it would move your public string string above the private string, invalidating the code.

The code and related card with more details:

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/CodeReorganizationAvailabilityLogic.cs#L90

https://trello.com/c/Qqd0GLqI

Hope it helps. :)  I'll close the card for now but please free to comment further and we can reopen.
