### ISSUE TITLE
Add unspecified access modifiers

### ISSUE THREAD

**Issue by sebas77** [codecadwallader/codemaid#203]
Hi,

How can I remove this feature? Actually I want the opposite! I want codemaid to remove the redundant access modifiers. Please help me.

**Comment by sebas77** [comment]
Ok sorry, I found out how to disable the features, still I'd love to see the remove redundant option available.

**Comment by codecadwallader** [comment]
Ok, that's a new request we haven't heard before.  New feature suggestions are welcome on our backlog here: https://trello.com/b/VVxVhbQv/backlog

**Comment by sebas77** [comment]
it seems like I can only comment tasks, but not adding new ones?

**Comment by codecadwallader** [comment]
Correct, unfortunately there isn't a permission level where people can add cards without making the board entirely read/write to the world (e.g. delete cards too).

The first card on the board is titled "You can add comments on this card to request new cards to be created." - so our convention is to add comments to that card that can be converted by an admin.
