### ISSUE TITLE
Combine Indexers with Properties in Single Region During Cleanup

### ISSUE THREAD

**Issue by phil000** [codecadwallader/codemaid#205]
How do you combine properties and indexers into a single region during cleanup?

When I do a cleanup I get 2 regions - #region Indexers and #region Properties.

Using CodeMaid 0.9.0

**Comment by codecadwallader** [comment]
You can group them together at CodeMaid->Options->Reorganizing->Types.  Drag Indexers onto Properties (or vice versa).

Hope it helps.  If not please comment and we can re-open this issue.
