### ISSUE TITLE
Plugins for CodeMaid

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#206]
It would be nice if `CodeMaid` will support plugins with simple interface, so functionality could be extended. 

This will help other developers easily extend `CodeMaid` functionality without bloating it's core.

**Comment by codecadwallader** [comment]
Cool idea, but probably not trivial to build and would elicit a number of questions.  Do you have any specific examples in mind?

It would be preferable to start this conversation on the Trello backlog: https://trello.com/b/VVxVhbQv/backlog
