### ISSUE TITLE
Unable to clean SCSS files

### ISSUE THREAD

**Issue by john-cheesman** [codecadwallader/codemaid#207]
When running a cleanup of all code, `.scss` files appear to be excluded and I'm not able to run a cleanup on an individual file either. I've checked the settings and all file types are enabled and the exclude list contains only the default values. I'm using Visual Studio 2012, which doesn't have native support for `.scss` files but I wouldn't expect this to be a problem.

**Comment by codecadwallader** [comment]
I haven't been able to reproduce it in VS2015 (will try VS2012 later).  Some other questions in the meantime:

- If you right click on the open document, is the cleanup command disabled?
- If you right click on the file within the solution explorer, is the cleanup command disabled?
- If you enable Diagnostics mode (in CodeMaid->Options), does the output window show anything about "Unrecognized language" when you try to select those files?  If so, what are the details of those messages?

**Comment by john-cheesman** [comment]
Both of the cleanup commands are disabled for the individual files as well as the cleanup selected code command for the folders.

Looking at the diagnostics output I'm getting this error when selecting `.scss` files in the solution explorer:

```
[CodeMaid Diagnostic 12:39:10 PM] CodeCleanupAvailabilityLogic.IsDocumentLanguageIncludedByOptions picked up an unrecognized document language 'Plain Text'
```

**Comment by codecadwallader** [comment]
Ok, that makes a lot of sense if VS2012 doesn't recognize SCSS files at all like you mentioned.  That's the same behavior you would get if you had a random text file (eg. MyFile.xyz).

Are you running the latest service pack within VS2012 to check if they happened to add support later?

We do rely on the Visual Studio API to tell us what kind of file we're working with so we know what kind of cleanups are appropriate.  Several languages have multiple file extensions that map to them so relying on the API is more accurate than a file extension matcher.

We do have a card in the backlog to support basic cleanup of any file type https://trello.com/c/iCcJhX85   With this implemented it would work in your scenario, but you wouldn't get any of the SCSS specific cleanups (e.g. removing blank lines after opening braces or before closing braces).

**Comment by john-cheesman** [comment]
Thanks for looking into it. I'm stuck using VS2012 at work, hopefully they'll upgrade to 2015 at some point. I think they started introducing support in 2013. Basic text file cleanup is a definitely a good idea as having consistent white space and blank line formatting is something other IDEs have built in.

**Comment by codecadwallader** [comment]
Thanks for reporting it, and sorry that you're stuck on VS2012.  I've pulled that card in for investigation within the next minor release to hopefully help out.
