### ISSUE TITLE
C# Class w/ Many Nested Classes Hangs Visual Studio 2015

### ISSUE THREAD

**Issue by GameDaddy** [codecadwallader/codemaid#208]
The API I ported over to Windows has a class with 45 nested classes.  Editing the class (with Spade open) slows down with each edit till the UI becomes unresponsive.  Process Explorer says the devenv.exe process is still "Running" (has not changed to "Not Responsive") but Visual Studio will not respond.  Windows reboots without complaining that Visual Studio is stopping the reboot (so I guess this verifies that devenv.exe is still "Running").
Turning off the McCabe item complexity seems to resolve this hang.  Class editing still can be stalled as Spade updates over a number of seconds.

**Comment by GameDaddy** [comment]
The classes are all with static elements.  Most only have one private variable and two one liner functions.  A few have as much as 10 lines of code.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  In the past we've tested up to 10,000 lines of code in a single file and as would be expected the larger the file, the higher the processing demands.  All work that can be done on a background thread (such as calculating complexity) should be running in the background to reduce UI thread demands (i.e. hanging Visual Studio).  Additionally the TreeView control that Spade uses is virtualized to prevent rendering of code elements beyond the visible region.  So we've tuned what we can to support massive files, but there is an inevitable performance impact relative to the size of the file.

Some questions that would help:
- How many overall lines of code does the file contain?
- When you say nested, do you mean they're recursively nested (45 levels deep) or there's 45 classes that are 1 level deep?
- Can you provide that class file, or even better the whole project, so we can try to reproduce the issue?

**Comment by GameDaddy** [comment]
This is a behemoth 1666 lines.  (I have seen longer in the Windows C code base.)
All are nested 1 level deep.  (LOL No recursive nesting of 45 levels!  I'll have to save that trick for later.)
Unfortunately the code is internal to the company, I hope you can make reasonable inferences from the statistics.
Thanks for the quick response.

**Comment by GameDaddy** [comment]
Thought of another important environment issue.  I have a number of VS Extensions running that are also doing things in the background.  I just turned off "PowerMode" a totally non-essential explosive cursor doodad that does a lot of particle effects while you type.  Other more essential extensions that seemed to conflict with Code Maid are many of the "Roslyn" enhancements.

**Comment by codecadwallader** [comment]
If you disable all of the extensions, is the issue still exhibited?  Do you have a list of all of those extensions?

**Comment by codecadwallader** [comment]
We've got more traction/progress on the similar issue #212 so I'm closing this one in favor of merging these two together.
