### ISSUE TITLE
inline with statements in vb.net

### ISSUE THREAD

**Issue by jeremysimmons** [codecadwallader/codemaid#211]
Can I remove/inline a With...End With Statement statement?
https://msdn.microsoft.com/en-us/library/wc500chb.aspx

```
With theCustomer
        .Name = "Coho Vineyard"
        .URL = "http://www.cohovineyard.com/"
        .City = "Redmond"
End With
```

becomes

```
theCustomer.Name = "Coho Vineyard"
theCustomer.URL = "http://www.cohovineyard.com/"
theCustomer.City = "Redmond"
```

DevExpress has had this for some time.
https://community.devexpress.com/blogs/markmiller/archive/2009/06/25/coderush-xpress-for-c-and-visual-basic-2008.aspx

**Comment by codecadwallader** [comment]
We do not currently have this feature.  You're welcome to suggest it on the backlog (https://trello.com/b/VVxVhbQv/backlog) or take a crack at implementing it (http://www.codemaid.net/contribute/).  To be honest we haven't had a lot of user demand for VB support so it may languish in the backlog without some active contributions.
