### ISSUE TITLE
Nested regions only partly deleted

### ISSUE THREAD

**Issue by aschwab** [codecadwallader/codemaid#213]
Hello, nice tool that you've created here! Its very useful!

I found a bug in formatting regions, as you can see, he does'nt remove the "#region ImAnUnknownRegion":

Before Refactoring:
![beforerefactoring](https://cloud.githubusercontent.com/assets/736468/12815245/7bfd9e68-cb45-11e5-818e-cfa12a6dcbe6.PNG)

After Refactoring:
![afterrefactoring](https://cloud.githubusercontent.com/assets/736468/12815246/7bfdbde4-cb45-11e5-9899-e4230c2d37dd.PNG)

Used Config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="SteveCadwallader.CodeMaid.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <SteveCadwallader.CodeMaid.Properties.Settings>
            <setting name="Reorganizing_MemberTypeConstructors" serializeAs="String">
                <value>Constructors||2||Instantiation</value>
            </setting>
            <setting name="Reorganizing_RegionsInsertNewRegions" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Reorganizing_RegionsRemoveExistingRegions" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Reorganizing_MemberTypeFields" serializeAs="String">
                <value>Fields||1||Members</value>
            </setting>
            <setting name="Reorganizing_RunAtStartOfCleanup" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Cleaning_UpdateEndRegionDirectives" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="Cleaning_InsertBlankLinePaddingBeforePropertiesSingleLine"
                serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Switching_RelatedFileExtensionsExpression" serializeAs="String">
                <value>.cpp .h||.xml .xsd||.ascx .ascx.cs||.aspx .aspx.cs||.master .master.cs||ViewModel.cs View.xaml</value>
            </setting>
        </SteveCadwallader.CodeMaid.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, as well as the kind comments and all the necessary details.  I have reproduced the issue you're seeing with removal of nested regions.  We do have logic in place to try and handle the removal of nested regions (see https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/CodeReorganizationManager.cs#L431-L456) but I agree it isn't working in the code sample you've provided.  I suspect it's an issue with the pointers to region statements not being updated after the outer region has been removed.

**Comment by codecadwallader** [comment]
I have a proposed fix for this based on doing some character offsets similar to what is in place here: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Reorganizing/GenerateRegionLogic.cs#L144-L150

It worked in the scenario above, but needs some additional regression testing before I check it in.

**Comment by codecadwallader** [comment]
The fix looks good through the integration tests.  Committed and will be present in the next release.  Thanks again for identifying it.

**Comment by codecadwallader** [comment]
This fix is now available in the latest beta here: https://github.com/codecadwallader/codemaid/releases/tag/v0.9.0.2-beta

If anyone has a chance to test and confirm the fix it would be greatly appreciated.  If there are any issues please comment and we'll reopen the issue.
