### ISSUE TITLE
Latest beta is losing the indentation of the first line during comment formatting

### ISSUE THREAD

**Issue by codecadwallader** [codecadwallader/codemaid#215]
In the v0.9.0.1 BETA, I've noticed that when you run a comment formatting command (e.g. on an XML summary) the first line of the comment is losing its indentation and moving to the first column.

Before:
```csharp
    /// <summary>
    /// An implementation of <see cref="IConfigurationSectionHandler"/> that simply returns the provided XML.
    /// </summary>
```

After:
```csharp
/// <summary>
    /// An implementation of <see cref="IConfigurationSectionHandler"/> that simply returns the
    /// provided XML.
    /// </summary>
    ///
```

I'm not sure if this could be tied to changes made for #141?

If you have an opportunity @willemduncan can you please take a look?  If not I can dig in too.

**Comment by codecadwallader** [comment]
I see some of the unit tests are failed as well:

- FormatStandardComments_FormatsAsExpected
- FormatStyleCopHeaderComments_FormatsAsExpected
- FormatXMLComments_FormatAsExpected

**Comment by willemengel** [comment]
That is strange, all unit tests run correct on my fork, and there are no changes. Is this a problem just in the beta or does it also happen when you run the latest code?

**Comment by willemduncan** [comment]
That is strange, all unit tests run correct on my fork, and there are no changes. Is this a problem just in the beta or does it also happen when you run the latest code?

**Comment by codecadwallader** [comment]
That is strange, glad to hear you have a bead on it though - thanks! :)

**Comment by codecadwallader** [comment]
As v0.9.1 is now released, closing this issue.
