### ISSUE TITLE
Sorting properties can change their behaviour

### ISSUE THREAD

**Issue by jakubsuchybio** [codecadwallader/codemaid#216]
Hi,
today I was fixing bug, which was done by codemaid.
Basically it comes to this:
```c#
static int CA = 5;
static int BA = 2 * CA;
```
after sorting propeties it reverses into:
```c#
static int BA = 2 * CA;
static int CA = 5;
```
In the first there is CA=5 and BA=10
In the second CA=5 and BA=0, because initialization of the class and class properties goes from top to bottom.

I think you should adress this. When you detect, that there are dependencies in properties to other properties you shouldn't sort them.

**Comment by codecadwallader** [comment]
Thanks for referencing the issue.  The current API we use does not provide dependency information, so to really address this item requires a broader rewrite to the Roslyn compiler.  This is a known item listed on our backlog here: https://trello.com/c/nSWn8FAF where we're collecting information/votes.
