### ISSUE TITLE
Cleaning static readonly fields

### ISSUE THREAD

**Issue by aetaylor** [codecadwallader/codemaid#218]
We have discovered a bug that has been introduced into our code due to a cleanup:

`public static readonly double Spacing = 37.0`
`public static readonly double Adjustment = Spacing / 2;`

When cleaned, the lines are switched. There is no compiler error but the code obviously no longer works.

see: https://msdn.microsoft.com/en-us/library/aa645757%28v=vs.71%29.aspx
specifically the part '... in textual order'

**Comment by codecadwallader** [comment]
This is a known limitation with how reorganization currently works.  Please see #216 for more details.

**Comment by aetaylor** [comment]
Hi Steve,

I must have missed this when skimming through the issues.

Would it be possible to add a short-term work-around by allowing, say, a named region (like "#region DO_NOT_MOVE") to be added around blocks of code that you don't want re-ordered?

Regards,
Alan

Date: Wed, 24 Feb 2016 06:50:21 -0800

**Comment by codecadwallader** [comment]
Here's a couple alternate approaches that have been proposed in the past:

https://trello.com/c/yOlkhznB
https://trello.com/c/jGCT68cv
https://trello.com/c/uLb0ccFt

Thoughts?  Alternatively feel free to propose your recommendation or a variation of it here: https://trello.com/c/1IQl1f7t
