### ISSUE TITLE
Visual Studio hangs when renaming if "Automatic Cleanup On Save" is enabled

### ISSUE THREAD

**Issue by Tan90909090** [codecadwallader/codemaid#223]
I think this issue is same as #153. However, it still occurs.
If I turn off automatic cleanup, renaming works perfectly.
If I turn on automatic cleanup, any kind of renaming (I've seen it with local variables, fields, method parameters, methods, classes, and namespaces) always makes Visual Studio hangs.

Visual Studio version: Community 2015 (v14.0.23107.156)
CodeMaid version: 0.9.0
CodeMaid user settings: [CodeMaid.config.txt](https://github.com/codecadwallader/codemaid/files/160222/CodeMaid.config.txt)
How to reproduce:
1. Create a C# Console Application Project;
2. Open the Program.cs;
3. Turn on "Automatic Cleanup on Save";
4. Move caret to "Program", which is class name;
5. Press F2 key to rename mode;
6. Input a new class name;
7. Press enter key to apply;
8. Visual Studio's status bar displays "CodeMaid is cleaning `Program.cs'..." and hangs.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have been able to reproduce it.

Within your settings, the option to "Skip during automatic cleanup on save" has been disabled for undo transactions.  This setting is normally on by default, and I recommend to re-enable it for your scenario with using Visual Studio refactoring features.  When that setting is enabled the issue goes away and an infinite loop does not occur.  There is some more detail about that setting and what happens in the other issue you referenced.

Hope it helps.

**Comment by Tan90909090** [comment]
When I enable "Skip during automatic cleanup on save" check box, which is under "Use undo transactions" check box  in "Miscellaneous" group box in "General" tab, the issue goes away!

Thank you for your quick reply!

**Comment by codecadwallader** [comment]
You're welcome, glad I could help. :)

**Comment by BrainSlugs83** [comment]
Pardon me... but ... why do you have an option that literally crashes Visual Studio when out-of-the-box functionality is used?  This still repros today, and I'm just wondering -- why can't CodeMaid detect that this is happening and ignore the option? (or why hasn't the option been removed?)

**Comment by codecadwallader** [comment]
If I recall correctly this would only happen if users opted out of the "Skip during automatic cleanup on save" safety net that is on by default.  Not all users were affected by this infinite loop so the option was left in for those who were able to run without the safety net.

I agree I don't like having options that can be dangerous in some circumstances (e.g. when combined with other extensions), but I also understand that unaffected users want the ability to opt in.
