### ISSUE TITLE
Reorganizing fails when code contains conditionals

### ISSUE THREAD

**Issue by HermanCordes** [codecadwallader/codemaid#225]
I've recently discovered that CodeMaid 0.9 fails to reorganize a class when conditional directies are used in a method. For example like this:

```
#if net35
         return TaskEx.Run(() =>
#else
            return Task.Run(() =>
#endif
```

When pressing Ctrl+M+Z, CodeMaid displays a message in the status bar of Visual Studio (2015.1):

> The key combination (Ctrl+M, Ctrl+Z) is bound to command (Reorganize Code) which is not currently available.

Anyone else encountered this behavior?

Thanks

**Comment by codecadwallader** [comment]
Thanks for cleanly reporting the issue.  Yes, we deliberately disable reorganization in the presence of `#pragma` statements as they can really alter the context of the file and moving members may break the intended logic.  There is some more information on #200 including a link to the backlog card with a possible path forward to add support for files with conditionals.
