### ISSUE TITLE
Spade method body regions

### ISSUE THREAD

**Issue by beyaz** [codecadwallader/codemaid#228]
How can I disable in spade items for regions in method body ? 
because I have a lot of region/endregion scopes in mey methods and I don't want to see these regions in CodeMaid Spade window.

İs there any config ?

**Comment by codecadwallader** [comment]
We don't currently have a configuration option for it, but it is on our backlog.  There hasn't been a lot of push for it, but contributions are always welcome!  https://trello.com/c/Zs99tcZL
