### ISSUE TITLE
Hangup and crash on a big file cleanup

### ISSUE THREAD

**Issue by kirillkovalenko** [codecadwallader/codemaid#229]
I have a project that includes [relatively big .cs file](https://onedrive.live.com/redir?resid=9844FDC23B276A96!3028&authkey=!AOB-9mbBMM8WJUI&ithint=file%2ccs) which is generated from a MS CRM system using CrmSvcUtil.exe. The file size is ~10 mb. Today I ran 'Code Cleanup' command on the whole solution and while processing this big file the visual studio hang for about 30 min and finally crashed.

**Comment by codecadwallader** [comment]
Holy.Moly.  That file is 250k lines!  We've stress tested up to 10k lines which was painful but technically passed.  I strongly recommend adding that file to your exclusions list under Cleaning->File Types->Exclude as we have an in-memory model that would be staggering in size for that kind of file.

**Comment by kirillkovalenko** [comment]
yep, the file is pretty big. I've already excluded it of course as it re-generated anyway. I just thought devs might want to know that such edge cases exist or/and use it for optimization efforts.

**Comment by codecadwallader** [comment]
Sounds good, thanks.  I'll keep this in mind if I need a new stress tester.. although seems like we might have some work to do before we could even attempt to use it. ;)  Marking issue as closed.
