### ISSUE TITLE
No downloadable artifacts from AppVeyor builds?

### ISSUE THREAD

**Issue by jhorv** [codecadwallader/codemaid#230]
I wanted to run a bleeding-edge version of CM but found all the AppVeyor builds were without artifacts?

**Comment by codecadwallader** [comment]
Correct, currently we don't have them.  It is in our backlog (https://trello.com/c/r4yNw8Nq) but back when we originally setup with AppVeyor they weren't able to support generating VSIX files.  I know they support NuGet packages.. do you know anything about support for VSIX outputs?

And as a short-term spoiler.. we just released v0.9.1 tonight.  So bleeding-edge == published.. at least for a couple days. ;)

**Comment by jhorv** [comment]
Afraid I can't help with the AppVeyor VSIX output, except to say that another project I follow closely is [Visual F# Power Tools](https://github.com/fsprojects/VisualFSharpPowerTools) and they do AppVeyor with VSIX output.  They've a [gitter channel](https://gitter.im/fsprojects/VisualFSharpPowerTools?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) too, maybe someone in there could help?

Meanwhile, thanks for the bits!  :)

**Comment by codecadwallader** [comment]
That's super helpful to know it's possible.. I've pulled the backlog card into investigation in the next release and we'll continue forwards with this investigation there.  Thanks!

**Comment by codecadwallader** [comment]
We're having awesome success with this.. :) As a reminder to anybody who finds this go to https://trello.com/c/r4yNw8Nq for more.
