### ISSUE TITLE
VB: Moving functions around in Spade doesn't include XML comments.

### ISSUE THREAD

**Issue by earlymeadow** [codecadwallader/codemaid#231]
In a VB 2015 project I'm moving around my Subs and Functions in a more logical way in the spade window, so that the function or sub moves in the code file as well. If a function has XML comments, however, these are not moved, causing the comments to precede code block that don't match.

Probably a Visual Basic thing, I have no idea if this funcionality is available in C#. For now I'm moving the comments by hand in the code editor, just thought you'd like to know.

It's an awsome tool by the way. Many thanks...

**Comment by codecadwallader** [comment]
Thanks for reporting the issue and the compliment. :)

We did encounter this issue when trying to support full reorganization for VB.  See https://trello.com/c/TD0jaAab for some more details.  In short, the VS API for VB doesn't report XML comments like it does for C#, even though they have the same code constructs and interfaces.  Unfortunately not the only time we've found discrepancies between VB and C# support within the VS API.

We did end up later adding some logic to workaround leading comments (specifically non-XML comments).. but that's C# specific.  I think a fix may be as simple as modifying https://github.com/codecadwallader/codemaid/blob/490fb624d48fb928a08ff7401c7b0ffa1a3a8ce3/CodeMaid/Model/CodeItems/BaseCodeItemElement.cs#L177 to not just look for C-style comments but to look for language-specific comment prefixes as used here https://github.com/codecadwallader/codemaid/blob/490fb624d48fb928a08ff7401c7b0ffa1a3a8ce3/CodeMaid/Helpers/CodeCommentHelper.cs#L108

**Comment by earlymeadow** [comment]
I'm more that willing to test it (in binary form), but I'm an "old" VB6 / VBA programmer, moving from VB6 to VB 2015 this year so I doubt I'll be able to checkout, change, recompile and test the maid (at this time).

**Comment by codecadwallader** [comment]
The code notes and help wanted tag are to help make this easier for other people that may want to pick it up as well and speed it along - no obligation back on you.

But don't sell yourself short if you ever feel adventurous I'm sure you could learn it. :)

**Comment by codecadwallader** [comment]
The fix mentioned above worked out as expected.  We just started a new CI channel this morning.. so if you want to test a build with the fix - you can install the latest from here: http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/

Note:  We're doing a lot of other work as part of standing up the CI channel, so if you encounter other issues please let me know.  If you would like to revert to a stable version, just uninstall CodeMaid then re-install it through the standard means.

Hope it helps!

**Comment by earlymeadow** [comment]
Many, many thanks for this quick fix - it works like a charm.

**Comment by codecadwallader** [comment]
Great, thanks for confirming. :)

**Comment by codecadwallader** [comment]
Reopening issue until it is fully released.
