### ISSUE TITLE
cannot find type name or missing namespace when I use codemaid and resharper together

### ISSUE THREAD

**Issue by xucongli1989** [codecadwallader/codemaid#237]
### Environment
- Visual Studio version: 2013
- CodeMaid version: 0.9.1
- Code language: c#

### Description
vs tips 'cannot find type name or missing namespace' under a part of class name when I install resharper ,because I want to use resharper together. so I disabled codemaid,the error tips is disappear.
when I uninstall resharper ,the error is not disappear too until I disable codemaid.
note: the error tips are not real error,vs can build it success.it's display message error only.

### Steps to recreate

![1](https://cloud.githubusercontent.com/assets/9961428/14096507/ec719cc8-f59b-11e5-854d-6014f5b98e4f.jpg)
![2](https://cloud.githubusercontent.com/assets/9961428/14096522/094c649a-f59c-11e5-80d5-9d3710bebb24.jpg)
![3](https://cloud.githubusercontent.com/assets/9961428/14096532/23b0edc4-f59c-11e5-935f-197f097301e7.jpg)

### Current behavior
see discription

### Expected behavior
It should be display success when I uninstall resharper

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  This does not seem like something that would be related to CodeMaid as we do not interact at runtime with type resolution, so we'll need to try some generic approaches to see what may be happening.

- If you re-install ReSharper (leaving CodeMaid disabled) does the issue continue to exist?
- If you install CodeMaid (leaving ReSharper uninstalled) does the issue continue to exist?

**Comment by xucongli1989** [comment]
Thanks for your reply.Maybe my Resharper version(10.0.2) is wrong,because my friend's pc is ok when I install an old version Resharper(8.2.3) and this codemaid 0.9.1.
Have a good time.
thx a lot.

**Comment by codecadwallader** [comment]
Ok, thanks for providing the update.  Good luck finding the issue with ReSharper - I have found them to be helpful in the past and use it too.
