### ISSUE TITLE
CodeMaid keeps getting disabled

### ISSUE THREAD

**Issue by richardlawley** [codecadwallader/codemaid#253]
### Environment
- Visual Studio version: 2015 Enterprise Update 2 (14.0.25123.00)
- CodeMaid version: 10.0.72

### Description
Something keeps disabling this extension.  Upon starting Visual Studio, CodeMaid is not present.  Going to Tools, Extensions I find it has been disabled.  Click Enable, click Restart Now, Codemaid reappears.  Close Visual Studio, reopen it, it's disabled again.  I've noticed that when restarting Visual Studio manually, the "Reading Component Cache" status window appears briefly.

This has been reported before (#82) but since that was a long time ago on a different version of Visual Studio it might not be related.

### Steps to recreate
1. Start Visual Studio (extension appears disabled)
2. Enable Extension and click Restart Now (CodeMaid menu appears)
3. Close Visual Studio
4. Start Visual Studio (extension appears disabled again).

I'm aware this is not an easily reproducible problem - I've got two machines and the other is not affected.  Both machines were updated to Update 2 RC prior to Update 2 RTM, and I noticed the behaviour occasionally on them then, but didn't sit down and look for the pattern (also because I thought it might be RC-related).

On the affected machine, I also note that the "Cloud Explorer for Visual Studio 2015" extension also gets disabled at the same time as CodeMaid.

I do have plenty of extensions installed, including: 
* Azure SDK (with all of the related extensions it installs)
* Bootstrap Snippet Pack
* C# Essentials
* EditorConfig
* GhostDoc
* GitHub
* Glyphfriend
* Indent Guides
* Ncrunch
* Productivity Power Tools 2015
* Ref12
* Refactoring Essentials
* Target Framework Migrator

I don't have time right now to try reinstalling this machine, but I'm happy to try and provide any additional information.  In particular, I'd like to know if there are any logs related to extensions being enabled/disabled that I am unaware of - I couldn't find anything on an initial look.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Yes there is a log file that may be helpful to retrieve, please take a look at https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/ for a little context and how to locate the file.

**Comment by richardlawley** [comment]
I think this turned out to be a Visual Studio issue rather than a CodeMaid, but I'll detail it here in case it helps anyone else.  There were messages in the logfile mentioning duplicate extensions, but I'm not 100% sure these were referring to CodeMaid.  However, I did try removing CodeMaid with the intention of reinstalling it.  After I removed it, CodeMaid was still present in the extensions list, although with an older version (0.9.1).  Trying to uninstall this didn't seem to work either.

Eventually I started Visual Studio as administrator, and uninstalled the extension.  This time it actually disappeared, and on reinstalling it (not as admin), I'm back to expected behaviour and it is not starting up disabled anymore.  I suspect the root cause may have been installing the extension when running VS as administrator, though I don't remember doing this.

**Comment by codecadwallader** [comment]
Thanks for the additional details and capturing them here for anyone else who might run into it as well!

**Comment by stevem26** [comment]
I'm getting this problem with a variety of VS extensions since I upgraded to 2015.

**Comment by codecadwallader** [comment]
Interesting, which other ones?

**Comment by lgmorand** [comment]
Got the same behavior with only two extension Codemaid and IndentGuides

**Comment by tporadowski** [comment]
The same thing started to happen to my VS2015 Community Edition recently. However, I do start it regularly as administrator (to be able to attach to IIS working processes) and as regular user. Solution from @richardlawley did the trick - I had to uninstall CodeMaid twice (once as regular user, second as admin) and then install it again (as regular user). Now everything seems to be back to normal (restarting VS2015 either as regular user or admin still shows up CodeMaid). Even starting 2 instances (regular/admin) at the same time didn't break it, perfect!

**Comment by codecadwallader** [comment]
@tporadowski Awesome, thanks for following up with a workaround for people who may be encountering this issue.

FWIW Visual Studio extensions install into the user profile directory, so perhaps running as a VS administrator is placing the extensions in a separate location causing two copies to be installed.

**Comment by lgmorand** [comment]
The trick worked for me too but I tried to uninstall several times as simple user without success, the extension was still present and disabled. I ran under elevated privileges to successfully installed it

**Comment by Veverke** [comment]
@lgmorand: did the same, only thing is all my unsuccessfull uninstall attempts were as admin. I kept trying and after some 3 or 4 attempts the extension eventually did not show in the installed(disabled) list.

**Comment by richardlawley** [comment]
While there are plenty of suggestions around for uninstalling multiple times (including one from me above), the actual problem here is that there are multiple versions of some extensions installed.  I suspect this relates to having multiple VS instances and some of them auto-updating.

To make it clear, this is *not* an issue with Codemaid, but a Visual Studio problem.

I've now found this tool: https://github.com/remcoros/DuplicateExtensionFinder 

This will list (and optionally automatically delete) the duplicate folders.  Do this with no copies of VS open, then open one, re-enable all of the disabled extensions, restart and you should be good (until it happens again).

**Comment by codecadwallader** [comment]
Thank you for sharing that
