### ISSUE TITLE
Custom regions?

### ISSUE THREAD

**Issue by jhonathanvini** [codecadwallader/codemaid#254]
### Environment
- Visual Studio version: 2015 Professional
- CodeMaid version: latest
- Code language: C#

### Description

Is it possible to customize the way regions are created?
instead of:
#region Public Methods
#endregion Public Methods
be like:
#region -- Public Methods -----------------
#end region -- Public Methods -----------

### Steps to recreate
Auto creating regions

### Current behavior
#region Public Methods
#endregion Public Methods

### Expected behavior
#region -- Public Methods -----------------
#end region -- Public Methods -----------

**Comment by codecadwallader** [comment]
Yes you can, go to CodeMaid->Options->Reorganizing->Types.  You can double click on any of the types to change the name they utilize.

Any questions please just comment and we can reopen the issue.
