### ISSUE TITLE
Installing CodeMaid in Visual Studio 15 Preview causes CSharp package to fail to load

### ISSUE THREAD

**Issue by joelday** [codecadwallader/codemaid#257]
### Environment
- Visual Studio version: [15 Preview]
- CodeMaid version: [10.0.72]
- Code language: [C#]

### Description
VisualStudio fails to load CSharp package after installing CodeMaid.

### Steps to recreate
1. Use Updates and Extensions... to install Code Maid.
2. Restart Visual Studio

### Current behavior
An error message saying that CSharp has failed to load is displayed. C# projects will not open.

### Expected behavior
Projects open successfully and CodeMaid is functional.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Unfortunately I have not been able to reproduce it yet.  Some thoughts:

1.  Do you see the error message during VS startup or when you try to open a C# solution?
2.  Have you confirmed that the error message goes away if you Disable CodeMaid?
3.  I didn't see the issue with the original release, but I saw tonight there was a new update available and installed that as well.  I imagine they will be pushing new updates rapidly.  I'm testing against 15.0.25123.0 PREVIEW.  Can you confirm what version you are using?
4.  Do any other languages work as expected (e.g. C++, VB, F#, JavaScript, etc.)?

**Comment by joelday** [comment]
@codecadwallader Mysteriously no longer getting a repro. Likely an obscure incidental issue. Thank you!

**Comment by codecadwallader** [comment]
Ok, thanks for confirming!
