### ISSUE TITLE
Feature Requests: Minor UI Options

### ISSUE THREAD

**Issue by kgallaha** [codecadwallader/codemaid#259]
### Environment
- Visual Studio version: 2015 Professional
- CodeMaid version: 10.0
- Code language: C#

### Feature Requests
**CodeMAID Spade**
- Command to open additional Spade windows, all displaying the same content - I have 3 x 30" monitors so being able to have one window open on each monitor would help out greatly
- Setting to change the font size - this would make it a bit easier to hunt for members on high resolution screens
- Setting to optionally display field and/or property types next to their names
- Setting to optionally display return types next to methods
- Setting to optionally display a reference count on the far right which could be clicked to behave like the Find References command
- Synchronize the selected item with whatever is currently active in the editor

**Solution Explorer**
- Setting to show/hide the collapse and/or cleanup buttons

**Comment by codecadwallader** [comment]
Thanks for the suggestions.  It would probably make more sense to split these out to separate issues so they can be individually voted upon and potentially implemented by people interested in running with them.  Would you mind breaking them up?

In regards to the font size, there is a trick where you can hold down the Control key and use your mouse-wheel to zoom in and out of the Spade window.  Clicking on the mouse wheel will also reset to 100%.

**Comment by codecadwallader** [comment]
Thanks once again for splitting those out to separate issues.  That will allow us to toggle/vote on them individually.  All great suggestions!
