### ISSUE TITLE
Cleanup: Less - curly brace is added on cursor position 

### ISSUE THREAD

**Issue by CaptainPsycho** [codecadwallader/codemaid#260]
### Environment
- Visual Studio version: 2012 Professional
- CodeMaid version: 10.0
- Code language: less
### Description
When saving a file and cleanup does it's work curly braces are inserted where the cursor is.
This is breaking the code.

### Steps to recreate
1. open lessfile
2. place cursor inside text
3. hit save with cleanup on save enabled

### Current behavior
It is adding an additional "}"
### Expected behavior
Not adding of anything.
![2016-04-07_18h15_29](https://cloud.githubusercontent.com/assets/11962533/14358332/bd00f684-fcec-11e5-88e7-f8889abdb944.png)
![2016-04-07_18h14_30](https://cloud.githubusercontent.com/assets/11962533/14358336/c1f9ed76-fcec-11e5-8ba6-b8de7176402a.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I haven't been able to reproduce it using VS2015, so I'll have to try again later on another machine.

Is that a part of a public solution that you can share a link towards, or can you make a minimal solution that exhibits the issue?

**Comment by CaptainPsycho** [comment]
For me it is not happening in VS2015.

**Comment by codecadwallader** [comment]
See #261
