### ISSUE TITLE
Cleanup: Less - when using variables for selectors cleanup adds linebreaks and breaks the code 

### ISSUE THREAD

**Issue by CaptainPsycho** [codecadwallader/codemaid#261]
### Environment
- Visual Studio version: 2012 Professional
- CodeMaid version: 10.0
- Code language: less

### Description
.@{variable} .class {
...
}

.@{variable} is valid less code and is only working without linebreaks.

Codemaid is breaking this into:

.@ {
    theme;
}

### Steps to recreate
1. open lessfile with this statement
2. hit save with cleanup on save enabled

### Current behavior
It is adding linebreaks
### Expected behavior
For .@{variablename} there must not be added additional linebreaks.
This has to be an exception for less.
![2016-04-07_18h15_29](https://cloud.githubusercontent.com/assets/11962533/14358533/ae2f091a-fced-11e5-8474-3e911d59b7ee.png)
![2016-04-07_18h14_30](https://cloud.githubusercontent.com/assets/11962533/14358539/b3ba9dea-fced-11e5-9149-7e2dc078c01d.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I haven't been able to reproduce it using VS2015, so I'll have to try again later on another machine.

Is that a part of a public solution that you can share a link towards, or can you make a minimal solution that exhibits the issue?

**Comment by CaptainPsycho** [comment]
For me it is not happening in VS2015.

**Comment by codecadwallader** [comment]
If you invoke Visual Studio's native formatting (Edit->Advanced->Format Document) do you see the same behavior?

**Comment by CaptainPsycho** [comment]
Oh yes, VS native formatting is breaking it.

**Comment by codecadwallader** [comment]
Ok, thanks for confirming.  I'd recommend reporting an issue with Microsoft, but I don't know how likely they are to publish fixes for VS2012 anymore.
