### ISSUE TITLE
Change scrollbar position after save cshtml

### ISSUE THREAD

**Issue by petrfleischmann** [codecadwallader/codemaid#267]
### Environment
- Visual Studio version: 2015 Professional
- CodeMaid version: 10.0
- Code language: C# (Razor cshtml file)

### Description
After setup: UserSettings > Cleaning > General > Automatically run cleanup on file save, I save Ctrl+S cshtml razor temaplate. Scrollbar position has been changed. (if file is't modified, must be position same as before save).

### Steps to recreate
1. Setup UserSettings > Cleaning > General > Automatically run cleanup on file save
2. Edit CSHTML file
3. Save file
4. Scrollbar position has been changed

### Current behavior
Scrollbar position is changed

### Expected behavior
Scrollbar position is unchanged.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have reproduced it.

This is a native VS bug.  You can reproduce it without CodeMaid by directly invoking Edit->Advanced->Format Document.  As part of CodeMaid's cleanup, we invoke the native VS cleanup.

This same issue came up with CSS files in the past, so we built a dedicated workaround class https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Helpers/CursorPositionRestorer.cs

It doesn't appear to be working for CSHTML files.. it seems that unlike CSS files there's some latency before the scroll position is reset so when we go to restore the cursor, it hasn't moved yet.

I'll take a longer look into it.  As a workaround you can disable CodeMaid's invocation of VS formatting through the Options.. but you'll of course lose those formatting capabilities.

**Comment by codecadwallader** [comment]
I looked into this a little further, and it's not what I was thinking it was previously.  The cursor position is never being changed, only the scroll window location as you mentioned.  This is standard Visual Studio behavior that applies to all languages (e.g. C#) when you invoke their Format Document command.

I'm not aware of any VS settings that allow for changing this behavior.  I would recommend opening a Microsoft Connect issue or posting to the MSDN forums to see if there is any way to override that behavior.
