### ISSUE TITLE
Add ability to override safety checks

### ISSUE THREAD

**Issue by bjorndavis** [codecadwallader/codemaid#268]
### Environment
- Visual Studio version: 2013
- CodeMaid version: 10.0.72
- Code language: C#

### Description
Currently, CodeMaid disables the re-organize function if the file contains any pre-processor conditionals/directives.  This should be an be an option that is off by default and allows overriding the safety checks.  Thanks!

Related issue:
#239

**Comment by codecadwallader** [comment]
Thanks for splitting this out.

**Comment by bjorndavis** [comment]
No prob - I looked into fixing it myself, but unfortunately I don't think I'll be of much help here.

**Comment by codecadwallader** [comment]
Thanks for taking a look, I appreciate that.  I can see you're pretty passionate about it so I'll knock it out.

**Comment by codecadwallader** [comment]
I've implemented this request as a new option as well as a user prompt when detected.

Can you please test the latest CI build (10.0.81 or higher) available here: http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/

**Comment by bjorndavis** [comment]
Ok I had some time to test this in 10.0.82 - looks like it's working well.  Thanks!

**Comment by codecadwallader** [comment]
Cool, thanks for confirming.
