### ISSUE TITLE
Question regarding sort selection

### ISSUE THREAD

**Issue by logicampbell** [codecadwallader/codemaid#274]
Hello, great extension. I was wondering if the tool supports sorting a selection of functions?

**Comment by codecadwallader** [comment]
Thanks for the compliment.  No unfortunately we don't currently support highlighting a section of code and running reorganization only upon it.  It has been on our backlog in the past but there wasn't a lot of push for that capability so it has remained on the back burners.

**Comment by logicampbell** [comment]
OK; thanks for taking the time to answer my questions - cheers.
