### ISSUE TITLE
ReSharper cleanup command needs updated for ReSharper 2016.1

### ISSUE THREAD

**Issue by jamiehumphries** [codecadwallader/codemaid#276]
ReSharper has just released version 2016.1: http://blog.jetbrains.com/dotnet/2016/04/14/resharper-ultimate-2016-1-is-released/

In this release, the name of the silent cleanup command changes from `ReSharper_SilentCleanupCode` to `ReSharper.ReSharper_SilentCleanupCode`, which breaks the Third Party cleanup integration.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  That will be an easy correction to make and we're planning a release for next weekend.  As a workaround in the meantime you can specify it as a custom command within the "Other cleaning commands" section.

**Comment by jamiehumphries** [comment]
Thanks @codecadwallader, I have been using that workaround :smile:

I have submitted a potential fix as a pull request (#277), but that may not be exactly how you want to do it.
