### ISSUE TITLE
"An unhandled win32 exception occurred in StandardCollector.Service.exe"

### ISSUE THREAD

**Issue by drguildo** [codecadwallader/codemaid#280]
### Environment
- Visual Studio version: Microsoft Visual Studio Community 2015
- CodeMaid version: 10.0.72
- Code language: C++

### Description
When Visual Studio is left running with CodeMaid enabled I will eventually get a dialog box tell me "An unhandled win32 exception occurred in StandardCollector.Service.exe".

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  What is occurring at the time when the exception happens?  Are you actively cleaning, or is Visual Studio sitting idle?  After how long does it occur?

**Comment by drguildo** [comment]
I'm not sure exactly what's happening when the exception is triggered as it always seems to be when I've just left Visual Studio running in the background. It seems to take a while, like 10-15 minutes at a guess.

**Comment by drguildo** [comment]
I managed to get this error if it's any use:

`Unhandled exception at 0x0000000077A4EC12 (ntdll.dll) in StandardCollector.Service.exe: 0xC000000D: An invalid parameter was passed to a service or function.`

**Comment by codecadwallader** [comment]
I've been unable to reproduce the issue by simply leaving a C++ solution open.  Do you have a solution that exhibits the issue that you can share?

**Comment by drguildo** [comment]
[Test.zip](https://github.com/codecadwallader/codemaid/files/232063/Test.zip)

**Comment by codecadwallader** [comment]
I opened that solution, and left it idling for an hour but it simply sat idle as expected.  Do you have any other information to offer that might help explain what's happening?  Have you confirmed that the issue goes away if you disable CodeMaid?  Do you have any specific settings that may be causing the issue?  Do you have any other extensions installed that may be causing a conflict?

**Comment by drguildo** [comment]
Not really. I'm not very familiar with either C++ or Visual Studio (I'm currently learning) so was hoping I could get some pointers about how to go about debugging this. So far I've only had the problem occur when CodeMaid is enabled and never when it is disabled.

**Comment by codecadwallader** [comment]
I did find a Microsoft Connect issue acknowledging a bug with the original release of VS2015.  Have you updated to the latest VS2015 Update 2?

https://connect.microsoft.com/VisualStudio/feedback/details/1630071/visual-studio-standard-collector-unbounded-memory-usage

**Comment by drguildo** [comment]
![image](https://cloud.githubusercontent.com/assets/9282/14798373/3e5775c8-0b2f-11e6-8069-6f0f31cf78a6.png)

**Comment by codecadwallader** [comment]
Thanks for confirming.  Without having a good idea of what may be triggering the issue, here are some broad spectrum things to check:

1.  If you close the CodeMaid Spade tool window.. does the error still happen?
2.  Is there anything that seems to exacerbate the issue or make it occur more rapidly?
3.  Does the error happen while the debugger is running or while in the code editor?
4.  Does the error happen with a brand new C++ solution, or only with a specific solution?
5.  Does the error happen if you simply open the solution and walk away?

**Comment by drguildo** [comment]
Looks like it isn't CodeMaid after all. I've had it disabled and still got the same problem. Sorry for the false alarm.

**Comment by codecadwallader** [comment]
Ok, thanks for following up and confirming the issue is elsewhere.  I recommend StackOverflow as a source for connecting with some C++ experts who may be able to help you get to the root of the problem.  Good luck!

**Comment by sdebussc** [comment]
I am also getting this error. I have Update 2. The error occurs every few minutes when Visual Studio is just idle.

**Comment by codecadwallader** [comment]
The original poster confirmed the issue still occurred when CodeMaid was disabled.  You may want to reach out to him to see if he ever came up with a solution or reported it elsewhere.

**Comment by mitch-besser** [comment]
Same here. Error happens when idle. I can't say it's is Visual Studio causing it, but I never see it when Visual Studio is not running. I also never saw it until I installed VS2015. Update to latest fixes nothing. Very annoying.
