### ISSUE TITLE
Execute Code Maid command programatically

### ISSUE THREAD

**Issue by ameyasubhedar** [codecadwallader/codemaid#285]
### Environment
- Visual Studio version: Visual Studio 2015 Community
- CodeMaid version: 10.1
- Code language: C#

### Description
How to execute Code Maid command pro-grammatically

### Steps to recreate
Would like to use the EnvDTE.ExecuteCommand to call the code maid commands programatically so that they can be integrated within our processes. This gives an ability to add custom behavior on top of Code Maid's formatting.

Would it be possible to have the list of command names and arguments so that EnvDTE.ExecuteCommand can pick it up ?

**Comment by codecadwallader** [comment]
Yes, the easiest way to see a list of commands is to launch the Command Window and type CodeMaid.  That will show you a list of commands that you can feed into ExecuteCommand.  The same trick will apply for any commands, not just CodeMaid's.  Hope it helps!
