### ISSUE TITLE
`Register Assembly` crashes VS 2015 on C++/CLI project

### ISSUE THREAD

**Issue by fubar-coder** [codecadwallader/codemaid#286]
### Environment
- Visual Studio version: 2015 Enterprise (German)
- CodeMaid version: 10.1
- Code language: C++/CLI

### Description
Solution explorer, project context menu, `Register Assembly` crashes VS 2015

### Steps to recreate
1. Create a C++/CLI project
2. Open the project context menu of this project from the solution explorer
3. Click on `Register Assembly`

### Current behavior
VS 2015 crashing

### Expected behavior
VS 2015 not crashing

EDIT: Disabling code maid context menu entries on non-C#/F# projects would be preferrable.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been unable to reproduce it, but I do not have a German machine under which to test it.

The `Register Assembly` command is not related to CodeMaid.  Have you confirmed the behavior does not occur with CodeMaid disabled?

Side note:  We used to more proactively enable/disable context menu items based on the project types.. but the number of times the menu item states can be checked can make that an expensive operation.  We deliberately disabled it in v10.1 to avoid a performance hit from repeatedly checking document details to determine command eligibility.

**Comment by fubar-coder** [comment]
It seems to be a problem with Azure Data Lake ... whatever that is and for what it's good for ...
Sorry for bothering you.

**Comment by codecadwallader** [comment]
No problem, thanks for following up.

**Comment by jlterheide-letsbuildit** [comment]
We have an MVC application that is hosted locally. When I click "register assembly" I must login with my Microsoft account and if I don't VS 2015 crashes. It creates a datalake log folder with this message:
10-5-2016 09:48:07.638  Exception: System.Exception: User does not login.
   at Microsoft.Cosmos.ClientTools.IDECommon.WindowsAzureAuthentication.<Login>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

Version:
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

**Comment by codecadwallader** [comment]
The original poster identified that this issue was not related to CodeMaid.  `Register Assembly` is not a command that CodeMaid interacts with so I think you would have better luck reporting this issue on Microsoft Connect or the MSDN forums.
