### ISSUE TITLE
Add CSHTML to File Types

### ISSUE THREAD

**Issue by chadboettcher** [codecadwallader/codemaid#291]
- Visual Studio version: 2015 Professional
- CodeMaid version: 10.1.93
- Code language: C#

I'd like to see CSHTML added as a file type in the Cleaning > File Types configuration.  Visual Studio still completely mangles CSHTML inline code formatting (See ticket #85) when you run Edit > Advanced > Format Document or when HTML is checked and Run format on save is enabled.  This is a result of VS, not CodeMaid but I just want a way to exclude CSHTML while allowing .HTM or .HTML files to be formatted as normal.

**Comment by codecadwallader** [comment]
Have you considered adding .cshtml to the file exclusion list?

**Comment by chadboettcher** [comment]
Sorry, I didn't even consider that.  It worked great.  Thanks!

**Comment by codecadwallader** [comment]
Cool, glad to hear it. :)
