### ISSUE TITLE
Find in solution needless?

### ISSUE THREAD

**Issue by xmedeko** [codecadwallader/codemaid#292]
### Environment
- Visual Studio version:2015 Community
- CodeMaid version: 10.1
- Code language: C#

### Description
Does the CodeMain `Find in Solution Ctrl + M, F` the same think as Visual Studio `Sync with Active Document Ctrl + [, S`?

### Expected behavior
If both functions are same, then the CodeMaid function may be deleted.

**Comment by codecadwallader** [comment]
These functions are largely similar these days.. ours was originally built before it became a native feature in VS in later editions.

The one extension we have is a custom workaround for finding items within nested solution folders.  If you've never opened the solution folder, the objects won't exist and the native command won't find them.  Our version will.

Hope it helps.
