### ISSUE TITLE
Space Eating Issue With C++ Macro

### ISSUE THREAD

**Issue by kevinemk** [codecadwallader/codemaid#294]
### Environment
-Microsoft Visual Studio Community 2013
-Version 12.0.31101.00 Update 4
-Microsoft .NET Framework
-Version 4.5.50938
-CodeMaid version: [10.1]
-Code language: [C++]

### Description
When saving this c++ file with option [Automatic Clean Up On Save] last two line always
![cplusplus](https://cloud.githubusercontent.com/assets/8066214/15323462/cbe88ea4-1c5f-11e6-9e61-bc3ea4bea1cc.gif)
 create free spaces.
Code sample :
#define CHECK(fn) \
	do {	   \
		if ((n = (fn)) == 0)\
			return 0; \
	else nPrintedChars += n; \
	} while (0)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Indentation is largely handled by the native Visual Studio formatting that CodeMaid invokes as a component of its cleanup.

If you invoke Edit->Advanced->Format Document, do you see the same behavior as you've described above?

**Comment by kevinemk** [comment]
Yes.Sorry for that.I think it should be Visual Studio Issue.

**Comment by codecadwallader** [comment]
Ok, I recommend you try the MSDN forums or Microsoft Connect for some more help.  Good luck!
