### ISSUE TITLE
CodeMaid shouldn't indent braces for case statements

### ISSUE THREAD

**Issue by jschroed** [codecadwallader/codemaid#297]
### Environment
- Visual Studio version: [Professional 2015]
- CodeMaid version: [10.1.9]
- Code language: [C#]

### Description
CodeMaid indents braces within case statements.

Braces can be used within case statements for scope. It would great if CodeMaid could keep the braces at the same level as the statement like how it does for if, for, and other statements.

### Steps to recreate
1. Create a case statement (see current behavior below).
2. Add braces around the code one or more case statements.
3. Run CodeMaid.

### Current behavior
Typically, case statements do not have braces. CodeMaid cleans these just fine like so:
```
switch (state)
{
    case 0:
        println("state 0");
        break;
    default:
        break;
}
```

However, adding braces (i.e. to keep scope for variables) has an undesired effect. Running CodeMaid with braces around the case statement causes the braces to be indented and the code to be indented two levels from the case statement.
```
switch (state)
{
    case 0:
        {
            println("state 0");
            break;
        }
    default:
        {
            break;
        }
}
```

### Expected behavior
The expected behavior is to have the braces at the same level as the case statement. The code in between should only be indented one level more.

```
switch (state)
{
    case 0:
    {
        println("state 0");
        break;
    }
    default:
    {
        break;
    }
}
```

**Comment by codecadwallader** [comment]
Most indentation actually comes from Visual Studios native formatting,
which we invoke. If you run Edit->Advanced->Format Document do you see the
same behavior?

**Comment by jschroed** [comment]
Yes. It appears that Format Document has the same behavior.

**Comment by jschroed** [comment]
It looks changing the format options works to change this behavior:
Tools -> Options -> Text Editor -> C# -> Formatting -> Indentation
Uncheck: Indent case contents

A side effect of this is that if there is a case statement without braces, it is not indented properly. I can live with this though.

**Comment by codecadwallader** [comment]
Cool, glad to hear you have an approach that works for you.
