### ISSUE TITLE
vb.net Reorganize and Regions

### ISSUE THREAD

**Issue by Acronda** [codecadwallader/codemaid#298]
### Environment
- Visual Studio version: Visual Studio Enterprise 2015 - Update 2
- CodeMaid version: 10.1
- Code language: VB.NET
### Description

When reorganizing code (for the Active Document) and you have set an option for Reorganizing > Regions the code will generate C# regions instead of VB regions.
### Steps to recreate
1. Make sure the option Regions > Include access level in regions is checked,  Insert new regions, Remove exising regions 
2. Open a .vb document
3. Select Reogainze Active document from the code maid menu
### Current behavior

The created regions have the C# syntax insead of the VB.NET syntax. One of the classes that should be modified is codemaid / CodeMaid / Logic / Reorganizing / GenerateRegionLogic.cs a check on the code type should be made and the code should be generated as accordingly.
### Expected behavior

Regions in VB.NET are defined as follows:
# Region "name of region"
# End Region

End region cannot be named.

**Comment by codecadwallader** [comment]
Thank you for reporting the issue, I have reproduced it.  We recently enabled support for VB reorganization, but we did not intend to enable region support for VB as that would require updates in a handful of other areas as well.  At a minimum we should make sure that region logic is bypassed during reorganization for VB.

**Comment by codecadwallader** [comment]
I've made several updates to more fully provide region support for VB.  This should resolve your original issue as well as a few others related to VB region support.

The CI channel where we normally test is currently being upgraded for VS2017 support, but this will be present in the next release.
