### ISSUE TITLE
Docked spade gone after entering VS to full screen.

### ISSUE THREAD

**Issue by zer09** [codecadwallader/codemaid#304]
### Environment
- Visual Studio version: VS2013
- CodeMaid version: 10.1.93
- Code language: C#
### Description

Docked spade gone after re-entering to full screen and unable to invoke from menu CodeMaid->Spade.
### Steps to recreate
1. Open solution file(VS is on full screen)
2. Exit full screen then
3. Enter to full screen again
   now the docked spade is gone and unable to invoke it through the menu
### Current behavior

Unable to invoke spade after re-entering full screen
### Expected behavior

The CodeMade Spade should still be accessible. 

If i remember it correctly i face this issue after upgrading to the version 10.1. 

Thanks

**Comment by codecadwallader** [comment]
This behavior was a deliberate pull request recently submitted by a user, please see #199

**Comment by zer09** [comment]
Thanks, I get it.

But if i want to show the spade while on full screen using the VS menu CodeMaid->Spade or using the shortcut CTRL+M,. it doesn't show up, while other tool window is shown if invoked.

**Comment by codecadwallader** [comment]
That's a good point.  It looks like the way the code in that pull request is written it will always hide the tool window when in full screen mode, even when invoked inside full screen mode.  I'll mark it as a bug and feel free to take a look into the code if you'd like to speed it along.

**Comment by zer09** [comment]
I don't have experience developing VS extension, but I will try to look at it. It will be a good start learning creating VS extension.

**Comment by codecadwallader** [comment]
Sounds great, good luck.  Here is some helpful starting information:
http://www.codemaid.net/contribute/
https://github.com/codecadwallader/codemaid/blob/master/CONTRIBUTING.md

If you have any questions please just ask. :)

**Comment by codecadwallader** [comment]
@iouri-s An issue came up with the pull request you made for hiding Spade while in full screen mode.  Any interest in taking a look to improve it?

**Comment by iouri-s** [comment]
Sure,
I will take a look. Thanks for looping me in!
Iouri

**Comment by codecadwallader** [comment]
Much appreciated. :)

**Comment by iouri-s** [comment]
I looked at this and talked to some folks, and will have a fix available soon. It may be that the fix is to simply revert my commit.
It turns out that VS persists the state (shown or hidden) for each tool window for each [window layout mode] (https://blogs.msdn.microsoft.com/zainnab/2010/11/21/window-layouts-the-four-modes/), so even though the spade shows in fullscreen mode, it won't show up again once closed. So the only inconvenience is the window's original state. If there is no clean and easy fix for that, I'll just revert my commit pure and simple.

**Comment by codecadwallader** [comment]
Sounds good, thank you!

**Comment by scolestock** [comment]
This still seems to be current behavior (window hidden when in full screen mode)

**Comment by codecadwallader** [comment]
This should(tm) be resolved in the next minor release v10.4

**Comment by JoseManuelGuerreiro** [comment]
Hello Steve,

I don't know what is happening with me but surely I can't find the item to dock CodeMaid in VS, by default I believe is on the right-hand side. I usually auto-hide all the tabs and I really don't know if this, somehow, affects in something. 
"I'm for everything...(Portuguese saying when you don't have a clue about what´s going on)". 
Please, could you help me on this simple matter? 
Thank you very much for the concern.
José Guerreiro

**Comment by JoseManuelGuerreiro** [comment]
Hello Steve,

I don't know what is happening with me but surely I can't find the item to dock CodeMaid in VS, by default I believe is on the right-hand side. I usually auto-hide all the tabs and I really don't know if this, somehow, affects in something.
"I'm for everything...(Portuguese saying when you don't have a clue about what´s going on)".
Please, could you help me on this simple matter?
Thank you very much for the concern.

José Guerreiro

**Comment by codecadwallader** [comment]
CodeMaid Spade's tool window can be docked in Visual Studio by dragging and dropping it near one of the edges of the Visual Studio window, or overlapping with one of the already docked tool windows if you want it to become a tab.  By default it should be docked alongside the Solution Explorer as a separate tab.  Hope it helps!  If you're still having difficulty can you please provide a screenshot?
