### ISSUE TITLE
How do i reinstall codemaid?

### ISSUE THREAD

**Issue by rainbowdesign** [codecadwallader/codemaid#307]
I have some issues with codemaid and want to try if reinstalling helps, but i cannot find a option to uninstall it.

Also i cannot see in the about section which sub version it is, it just says 10.1 where microsoft offers  10.1.93 so i am not sure if they are the same.

**Comment by codecadwallader** [comment]
Tools->Extensions and Updates is where you can perform all Install/Update/Uninstall operations for Visual Studio extensions.

The about dialog is an image that provides the major/minor version only.  There is also a build version number (e.g. .93) that is auto-generated and can be seen through the Visual Studio About dialog.
