### ISSUE TITLE
Cleanup remove the namespaces used in comment only

### ISSUE THREAD

**Issue by heku** [codecadwallader/codemaid#309]
### Environment
- Visual Studio version: 2015 Community Update 2
- CodeMaid version: 10.1
- Code language: C#

### Description
The cleanup removed the namespaces used in comment only, see below example.

### Steps to recreate

File A
```C#
public class EvaluationEngine
{
    public Task<string> EvaluateAsync(IEnumerable<string> sentences, IProgress<EvaluatingProgress> progress, CancellationToken token)
    {
        throw new NotImplementedException();
    }
}
```

File B
```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace OralEval.Domain
{
    /// <summary>
    /// <see cref="EvaluationEngine.EvaluateAsync(IEnumerable{string}, IProgress{EvaluatingProgress}, CancellationToken)"/>
    /// </summary>
    public struct EvaluatingProgress
    {
    }
}
```

### Current behavior
Cleanup File B will remove namespaces used in comment only.

```C#
using System;

namespace OralEval.Domain
{
    /// <summary>
    /// <see cref="EvaluationEngine.EvaluateAsync(IEnumerable{string}, IProgress{EvaluatingProgress}, CancellationToken)"/>
    /// </summary>
    public struct EvaluatingProgress
    {
    }
}
````

### Expected behavior

```C#
using System;
using System.Collections.Generic;
using System.Threading;

namespace OralEval.Domain
{
    /// <summary>
    /// <see cref="EvaluationEngine.EvaluateAsync(IEnumerable{string}, IProgress{EvaluatingProgress}, CancellationToken)"/>
    /// </summary>
    public struct EvaluatingProgress
    {
    }
}
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I believe this is the same as #303 which is open and has a workaround listed.

**Comment by codecadwallader** [comment]
Sorry for my previous comment, I misunderstood the issue.

Thanks for reporting the issue.  CodeMaid invokes the native Visual Studio "Remove and Sort Usings" statement, so the behavior you're seeing is really a pass through invocation to VS logic.  If you invoke the "Remove and Sort Usings" command directly through Visual Studio you'll see the same behavior.  I recommend you raise an issue on Microsoft Connect or within the Forums to see if anyone has suggestions.  If you do not want CodeMaid to cleanup using statements you can disable our invocation of the command via CodeMaid->Options->Cleaning->Visual Studio.

**Comment by heku** [comment]
That's alright, I've reported this problem to Visual Studio Team.
