### ISSUE TITLE
Cleanup removes a namespace using used in a documentation comment block.

### ISSUE THREAD

**Issue by emphasis87** [codecadwallader/codemaid#328]
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.1
- Code language: C#

### Description
A namespace using where the namespace is used only in a documentation comment block is being removed when there is no other use of the namespace

[ConsoleApplication1.zip](https://github.com/codecadwallader/codemaid/files/422007/ConsoleApplication1.zip)

```C#
using SomeNamespace;
namespace ConsoleApplication1
{
	/// <summary>
	/// <see cref="SomeClass.SomeProperty"/>
	/// </summary>
	internal class Program
	{
		private static void Main(string[] args)
		{
		}
	}
}
```

```C#
namespace SomeNamespace
{
	public class SomeClass
	{
		public bool SomeProperty { get; set; }
	}
}
```

### Steps to recreate
1. Create a class SomeClass in namespace SomeNamespace

2. Create a documentation comment block from another file referencing this class

```C#
/// <summary>
/// Blah blah <see cref="SomeClass.SomeProperty"/>.
/// </summary>
public bool Property { get; set; }
```

3. Add a using to the SomeNamespace, but nowhere else the namespace must be used in the current document

4. Run **Clean Active Document**

### Current behavior
The `using SomeNamespace;` is removed.
This obviously messes up documentation.

### Expected behavior
The namespace should not be removed.

**Comment by codecadwallader** [comment]
Thanks for reporting this issue, please see #309.
