### ISSUE TITLE
Even with all the "Remove" options disabled, CodeMaid still removes blank lines in SCSS

### ISSUE THREAD

**Issue by jakelauer** [codecadwallader/codemaid#334]
### Environment
- Visual Studio version: 2015 Professional
- CodeMaid version: 10.1
- Code language: SCSS
### Description

Even with all the "Remove" options disabled, CodeMaid still removes blank lines in SCSS. 
### Steps to recreate

Example:

```
    .submission
    {
        overflow: hidden;
        width: 100%;
        margin: 2rem 0;

        background: rgba(245, 245, 245, 0.05);
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.25);
    }

```
### Current behavior

When cleaned up, the above sample's blank line will be removed, even with all of the Remove options disabled
### Expected behavior

It should leave blank lines alone.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  This behavior is done by Visual Studio's native document formatting (Edit->Advanced->Format Document) which CodeMaid invokes as part of its own cleanup.

You can look and see if there are any related configurable settings under Tools->Options->Text Editor->SCSS but I did not see any upon a quick glance.

You can also disable CodeMaid's invocation of the native Format Document behavior, but keep in mind you will lose all the other behaviors that it handles.  That setting it at CodeMaid->Options->Cleaning->Visual Studio->Run format document.
