### ISSUE TITLE
Disable CodeMaid Spade

### ISSUE THREAD

**Issue by adepaoli** [codecadwallader/codemaid#335]
I would like to disble/hide completly Spade (Digging) functionalities and remove the CodeMaid Spade Window.

**Comment by codecadwallader** [comment]
You can close the tool window by clicking the 'X' in the top right corner.

**Comment by zecompadre** [comment]
it starts again when u reopen the project :(

**Comment by dupiesdupreez** [comment]
> it starts again when u reopen the project :(

Any Setting to stop it from opening when you reopen the project?

**Comment by codecadwallader** [comment]
Not currently, but I can add one.

**Comment by dupiesdupreez** [comment]
That would be Great Thanks allot.

**Comment by zuckerthoben** [comment]
I would appreciate the change.

**Comment by codecadwallader** [comment]
This is addressed by #525 which is merged into the mainline and will be present in the next release.

**Comment by dupiesdupreez** [comment]
Awesome, thanks allot for the change.
