### ISSUE TITLE
Not work with files generate by TT Template

### ISSUE THREAD

**Issue by hoanganh9** [codecadwallader/codemaid#338]
### Environment
- Visual Studio version: VS 2015 Community
- CodeMaid version: 10.1
- Code language: C#

### Description
Not work with files generate by TT Template

### Steps to recreate 1
1. Open file generate by TT Template
2. Menu: CodeMaid -> Cleanup Open Code

### Steps to recreate 2
1. Open Solution
2. Menu: CodeMaid -> Cleanup All Code...

### Current behavior
Not work with files generate by TT Template

### Expected behavior
Working with files generate by TT Template

**Comment by codecadwallader** [comment]
Looks like you've already closed this, but for the archives:

CodeMaid excludes T4 generated code by default.  You can change this setting at CodeMaid->Options->Cleaning->File Types->Exclude T4 generated code.
