### ISSUE TITLE
VS hang if it run as administrator

### ISSUE THREAD

**Issue by rvs76** [codecadwallader/codemaid#339]
### Environment
- Visual Studio 2012 Ultimate french
- CodeMaid version:10.1
- Windows 7 sp1 x64 french
- Code language: NA

### Description
VS hang if it run as administrator.

**Comment by codecadwallader** [comment]
Can you please provide some other details, such as the steps to reproduce the hang?

**Comment by rvs76** [comment]
I create a winform C# application, I change requestedExecutionLevel to  requiredAdministrator in app.manifest.  I start the application, VS says it needs to restart with another identification informations. I accept and VS hang at restart.
Try by right click in Windows Start menu and "run as administrator" and VS hang too.

**Comment by codecadwallader** [comment]
Thanks for the additional details, but I have been unable to reproduce it.  A couple things to try:

1.  If you uninstall or disable CodeMaid, do you still see the same behavior?
2.  Are you receiving any warning or error messages related to CodeMaid?

**Comment by rvs76** [comment]
1/ 
I deactivate CodeMaid and no problems.
I reactivate and ... no problems too !
2/
No

Sorry for the inconvenience.

**Comment by codecadwallader** [comment]
No worries, glad to hear you're back in business.
