### ISSUE TITLE
Reorganize breaks code that uses #if directives

### ISSUE THREAD

**Issue by mwnDK1402** [codecadwallader/codemaid#340]
### Environment
- Visual Studio version: 2015 Enterprise
- CodeMaid version: 10.1
- Code language: C#

### Description

#if !SOMETHING

    private void SomeMethod()
    {
    }

#endif

    private void SomeOtherMethod()
    {
    }

### Steps to recreate
1. Tick the "Insert new regions" option
2. Have some method between an #if directive and an #endif directive and have another method outside of the directives
3. Reorganize the code

### Current behavior
CodeMaid will insert a #region directive between the #if and the #endif directive, which causes a compiler error

### Expected behavior
CodeMaid should instead produce something like this:
    #region Private Methods

#if !SOMETHING

    private void SomeMethod()
    {
    }

#endif

    private void SomeOtherMethod()
    {
    }

    #endregion Private Methods

**Comment by codecadwallader** [comment]
CodeMaid does not really support reorganization when preprocessor conditions are present.  By default there is an option at CodeMaid->Options->Reorganizing->General->"Perform reorganization when preprocessor conditionals are present" that defaults to Ask.  We used to never run the operation, but we added it upon user request to be able to override the safety check and do it anyways, and deal with the consequences.  In your scenario, I would recommend going back to the default where it Asks you or flat out turning it off (No).

Hope it helps.
