### ISSUE TITLE
Regions are not visible in CodeMaid Spade using VB .NET

### ISSUE THREAD

**Issue by aeab13** [codecadwallader/codemaid#342]
### Environment
- Visual Studio 2015 Community and Enterprise
- CodeMaid 10.1
- VB .NET
### Description

VB Regions are not visible in Spade.
### Steps to recreate
1. Create an class
2. Add some methods and create the regions
### Current behavior

Regions do not appear in CodeMaid Spade
![image_2016-09-17_22-40-37](https://cloud.githubusercontent.com/assets/16917468/18611422/accdaf36-7d30-11e6-8f76-7926fe7282a9.png)
### Expected behavior

Regions should appear like in C#

NOTE: I've trying to see where is this functionality implemented but I haven't been able to find it. If you can tell me which class is doing this functionality, I'll try to fix it.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue and looking into it.  I think the following is where you'll want to look:

https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Model/CodeModelHelper.cs#L160

I suspect the problem may be that the `RegionPattern` and code within `CodeModelHelper` are explicitly looking for `#region` not `#Region` (i.e. case sensitive matching) as the tags are different between C# and VB.  We may want to review any other places that make the same assumption, e.g. `GenerateRegionLogic`

Links I found (may be others):
https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Model/CodeModelHelper.cs#L149
https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Model/CodeModelHelper.cs#L172
https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Model/CodeModelHelper.cs#L186

https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Logic/Reorganizing/GenerateRegionLogic.cs#L180
https://github.com/codecadwallader/codemaid/blob/0310b779a6a58041c9204bdc991c6db900775fd7/CodeMaid/Logic/Reorganizing/GenerateRegionLogic.cs#L212

**Comment by aeab13** [comment]
Oke! I'll look into it ASAP.
Thank you!

**Comment by codecadwallader** [comment]
Resolved by #368
