### ISSUE TITLE
Specify Order Of Access Modifiers for Reorganize in Options

### ISSUE THREAD

**Issue by MelbourneDeveloper** [codecadwallader/codemaid#344]
Current regions based on access modifiers run from Public to Private. But, currently our code orders these things the other way around, so when applying a reorder, too much code is shifted around unnecessarily.
Could we please get a screen to edit the access modifier order of regions created by Reorganize?

**Comment by codecadwallader** [comment]
Thanks for the suggestion, pull requests welcome!

**Comment by ahalassy** [comment]
I also faced this issue, so I forked and implemented this feature quickly. I intented to create a pull request, but most of the UTs were failing on my side. Despite this can I create a pull request?

**Comment by codecadwallader** [comment]
Cool.  Yes you can create a pull request.  I can take a look at why the UTs are failing and let you know if it's something related to your code.  They currently work on my side, although there are a few that require a second execution to pass depending on the unit test run order.

**Comment by codecadwallader** [comment]
Thanks @Emdot
