### ISSUE TITLE
third-party cleaning with clang-format is not executed

### ISSUE THREAD

**Issue by d0ru** [codecadwallader/codemaid#346]
### Environment
- Visual Studio version: 2015 Update 3
- CodeMaid version: 10.1
- Code language: C/C++

### Description
clang-format plugin for Visual Studio was installed from: http://llvm.org/builds/

### Steps to recreate
1. Open CodeMaid options, Third Party tab
2. Add this line for code format:

`clang-format -fallback-style=none -style=file -i "$(FileName)"`

### Current behavior
Whatever we put on the editbox it is not executed. (ex. echo)

### Expected behavior
CodeMaid should execute the commands that were configured for third-party cleaning.

CodeMaid seems the best tool to automatically format code on [Save]. Maybe I'm missing something obvious to make this work.

Thanks

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  The third party command does not invoke command line actions, but invokes Visual Studio actions (i.e. the same commands you would type into the Command Window (Ctrl+Alt+A).  The given example is ReSharper.ReSharper_SilentCleanupCode but another example would be Edit.Undo which would invoke Visual Studio's undo command the same as if you had clicked it from the Edit menu.

There is a mechanism at Tools->External Tools to create your own command line shortcuts, but I'm not sure if those would be exposed through the Visual Studio commands system.  You may want to ask on the MSDN forums for more help in that regards.

Hope it helps.

**Comment by d0ru** [comment]
Thanks for details on how third party cleaning commands work.

I've put "Tools.ClangFormat" there (after installing the VS extension) and it's executed now.
However, this is incomplete and doesn't have the same effect as running it through External Tools. I suspend that it's cleaning the TMP file copy instead, thus the working directory is not $ProjectDir (required ".clang-format" file is usually located on $ProjectDir).
Is the a way to specify a working directory or startup directory for these commands executed by CodeMaid?

Thanks

**Comment by codecadwallader** [comment]
Commands like Tools.ClangFormat can theoretically accept arguments (https://msdn.microsoft.com/en-us/library/c785s0kz.aspx) but you would want to look into their system if there's a way to specify working/startup directly with them.  I'm not sure if VS would perform the $ProjectDir translation when passing it as an argument or if that would just come through as a string literal.
