### ISSUE TITLE
Format Comments breaks ReSharper code inspection configuration comments

### ISSUE THREAD

**Issue by Kagern** [codecadwallader/codemaid#347]
### Environment
- Visual Studio version: Visual Studio 2015 Professional 14.0.25431.01 Update 3
- CodeMaid version: 10.1.93
- ReSharper version: ReSharper Ultimate 2016.1.2
- Code language: C#
### Description

CodeMaid's 'Format Comments' command concatenates/splits comments used by ReSharper for code inspection configuration, causing them to not be recognized by ReSharper.
### Steps to recreate
1. Add ReSharper code inspection configuration comments in a C# source code file.
   // ReSharper disable UnusedMember.Global
   // ReSharper disable MemberCanBePrivate.Global
   // ReSharper disable UnusedAutoPropertyAccessor.Global
   // ReSharper disable AutoPropertyCanBeMadeGetOnly.Local
2. Run the 'format comment' command on the block comments.
### Current behavior

ReShaper allows the use of comments to enable/disable/configure code inspections in the source code file.  There are inserted with one option per line.  When 'Format Comment' is run on a block of these comments, it concatenates them together based on the 'Wrap comments at column' value.  Doing so causes ReSharper to not recognize them.  _This probably only effects folks who enable the 'Run format comments during cleanup' option, as it is unlikely that anyone would explicitly run the 'Format Comment' command the ReSharper block._
### Expected behavior

Don't break things / do not format comment lines which contain ReSharper code inspection configuration options.

My CheapHack(tm) fix would be to have CodeMaid.Helpers.CodeCommentHelper.IsCommentLine return false if the line starts with "// ReSharper disable" or "// ReSharper enable".

**Comment by codecadwallader** [comment]
Thanks for the suggestion to make an exemption for ReSharper specific comments from comment formatting.

The obvious workaround in the meantime would be to avoid invoking the command on ReSharper specific comments.

Pull requests welcome, or @willemduncan may have input on your suggested CheapHack(tm) as he's written nearly all of the comment formatting functionality.

**Comment by willemduncan** [comment]
Feel closely related to #350, I guess we should start defining an exclusion list for formatting. So far it seems to be as easy as "ignore comments that start with certain keywords when reformatting all comments".
