### ISSUE TITLE
Exception shown in output pane

### ISSUE THREAD

**Issue by kwhitefoot** [codecadwallader/codemaid#348]
### Environment
- Visual studio version: 2015 Enterprise, update 3 
- CodeMaid version: 10.1
- Code language: VB

### Description
[CodeMaid Handled Exception 02:07:27 PM] TryDefault caught an exception on 'System.Func`1[EnvDTE.vsCMAccess]': System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.Exceptions.ThrowEFail()
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.GetDefaultAccessibility(SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.GetAccess(SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeMember.get_Access()
   at EnvDTE80.CodeProperty2.get_Access()
   at SteveCadwallader.CodeMaid.Model.CodeItems.CodeItemProperty.<.ctor>b__4_0()
   at SteveCadwallader.CodeMaid.Model.CodeItems.BaseCodeItemElement.TryDefault[T](Func`1 func)
[CodeMaid Warning 02:07:41 PM] Returned false due to a null input or pattern passed to RegexNullSafe's IsMatch.
[CodeMaid Warning 02:07:41 PM] Returned false due to a null input or pattern passed to RegexNullSafe's IsMatch.
[CodeMaid Warning 02:07:41 PM] Returned false due to a null input or pattern passed to RegexNullSafe's IsMatch.
[CodeMaid Warning 02:07:41 PM] Returned false due to a null input or pattern passed to RegexNullSafe's IsMatch.

### Steps to recreate
1. Start VS with a large VB solution

Sorry I can't be more specific.  All I know is that a small solution with a small VB project doesn't trigger the exception and neither do solutions that consist only of C# or F#.  I have not been able to isolate the cause (haven't tried debugging CodeMaid).  I can't show you the solution in question because apart from it being confidential it is some gigabytes of code and supporting files.

### Current behavior
Unexpected exception.

### Expected behavior
No exception should be thrown (or if it is harmless then it should just not be shown).

**Comment by codecadwallader** [comment]
The call stack indicates there is a particular code element that the VS API is unable to interpret.  Which document do you have open/active when this error occurs?  Specifically it looks like it is a property whose access level (i.e. public, private) cannot be determined.

`EnvDTE80.CodeProperty2.get_Access()`

**Comment by kwhitefoot** [comment]
I was going to say that I would try to find the element but unfortunately the exception seems to have gone away.  I have no idea what changed.  I suppose that the difference is probably which code file was opened but I didn't notice which files were open.

Could it be anything to do with F#?

If it happens again I'll try harder to record all the information.

**Comment by codecadwallader** [comment]
F# does not utilize that CodeModel API, so no I do not think it was related to any F# files.

It isn't a catastrophic exception, it would really just prevent that file from fully rendering in Spade and cleanup from occurring.  We'll close this issue for now, but feel free to comment to reopen if you do find a code sample that exhibits the issue.
