### ISSUE TITLE
Mark a Class or Region of Code as Never Cleaned \ Reordered

### ISSUE THREAD

**Issue by phil000** [codecadwallader/codemaid#353]
Is there any way to mark a class or block of code as something that should never be cleaned up\reordered? 

We clean up all of our code creating regions and putting stuff in member type and alphabetical order. However, there are occasions where various types require (or benefit from) a specific layout and we are trying to prevent this from changing inadvertantly.

e.g. These constants benefit from being in an order that is not alphabetical as the ID's are sequential. 

    internal static class Rule
	{
		public const string ActionMustHaveHttpMethod = "VAPI0001";

		public const string ActionMustReturnIHttpActionResult = "VAPI0002";

		public const string ActionMustHaveSwaggerResponse = "VAPI0003";

		public const string ControllerMustHaveSwaggerResponseRemoveDefaults = "VAPI0004";
	}

**Comment by phil000** [comment]
sorry, seems like a duplicate of #317 

This worked.........
/// <Auto-Generated>
/// This is here so CodeMaid doesn't reorganize this document
/// </Auto-Generated>

**Comment by codecadwallader** [comment]
Thanks, and agree.
