### ISSUE TITLE
Error thrown when trying to clean up document in Visual Studio 15 Preview 5

### ISSUE THREAD

**Issue by Reelix** [codecadwallader/codemaid#355]
### Environment
- Visual Studio version: Visual Studio 15 Preview 5
- CodeMaid version: 10.1
- Code language: C#
### Description

Code Maid throws error when attempting to clean up a document
### Steps to recreate

1.) Install Visual Studio 15 Preview 5
2.) Install Code Maid
3.) Restart Visual Studio
4.) Open a .cs file
5.) Control+M, Space (Clean up document)
6.) Notice the error in the Output window
### Current behavior

[CodeMaid Handled Exception 08:24:04 PM] CodeMaid Cleanup for 'Program.cs' was stopped: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.RemoveUnusedUsingStatements(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)
### Expected behavior

Code is successfully cleaned up

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I received an automated e-mail from Microsoft last night stating that they had changed the APIs for Preview 5 and that extensions would all be required to make updates in order to function any longer.  I suspect what you're seeing above is a consequence of that sudden change.

**Comment by mikequinlan** [comment]
I am getting this same error in Visual Studio 2017 RC.

[CodeMaid Handled Exception 11:12:27 PM] CodeMaid Cleanup for ‘program.cs’ was stopped: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at EnvDTE80.DTE2.ExecuteCommand(String CommandName, String CommandArgs)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.UsingStatementCleanupLogic.RemoveUnusedUsingStatements(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClass19_0.<Cleanup>b__0()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
If you go to the command window (Ctrl+Alt+A is the default keybinding for C#), and type Edit.RemoveUnusedUsings what kind of response do you get?  Under the covers that's what CodeMaid is invoking at the call stack you've provided.

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/UsingStatementCleanupLogic.cs#L81

**Comment by mikequinlan** [comment]
>Edit.RemoveUnusedUsings
Command "Edit.RemoveUnusedUsings" is not valid.

When I look at the available commands (Tools->Customize->Commands->Add Command...->Edit, there is an Edit.RemoveAndSort command available but Edit.RemoveUnusedUsings seems to have gone away.
![screen shot 2016-12-06 at 12 08 20 pm](https://cloud.githubusercontent.com/assets/7418798/20939632/c4845296-bbac-11e6-898c-7db623df4703.png)

**Comment by codecadwallader** [comment]
Interesting find.  I'm surprised it doesn't reference using statements at all in the command name.  If you invoke it does it still remove/sort using statements similar to previous Visual Studio editions?

**Comment by mikequinlan** [comment]
I tried it and Edit.RemoveAndSort does remove/sort the usings, just like previous versions of VS.

**Comment by codecadwallader** [comment]
Ok, thanks for confirming.  There used to be two separate commands and we'd allow users to choose neither/either/both that they wanted to run.  Looks like it will have to be an all or nothing going forwards.

**Comment by codecadwallader** [comment]
As a workaround in the meantime, you could try disabling CodeMaid's invocation of those now missing commands at CodeMaid->Options->Cleaning->Visual Studio->"Run remove unused using statements" and "Run sort using statements".

**Comment by mikequinlan** [comment]
I unchecked Remove unused using statements and Sort using statements and have verified that this does resolve the problem. fyi.

**Comment by codecadwallader** [comment]
Great, thanks for confirming.  Adding alternative support for this will certainly be a part of our next release.  If you encounter any other issues as you play around with the VS2017 RC it would be great if you could report those as well!

**Comment by codecadwallader** [comment]
I've got a fix for this up and running locally.  I'm working on getting this published out to the CI channel (waiting on private beta access to VS2017 images).

**Comment by codecadwallader** [comment]
This is now live in our [CI channel](http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/).  Experimentation welcome!

**Comment by mikequinlan** [comment]
This is now working for me. I downloaded the new version from your CI channel, made sure Run and Sort Using Statements was selected, and ran the cleanup on my solution (50+ files). Everything is now working. Thanks for your efforts!

**Comment by codecadwallader** [comment]
Awesome, thanks for confirming!
