### ISSUE TITLE
Codemaid spade takes too long to load on refresh

### ISSUE THREAD

**Issue by rainbowdesign** [codecadwallader/codemaid#357]
### Environment
- Visual Studio version: [2015 Community]
- CodeMaid version: [10.1]
- Code language: [C#]

### Description
I have a file with 4300 lines and when i click refresh or save the file it takes about 60 seconds till i can use the spade again.

### Steps to recreate
Take a big file with many entrys and click on refresh should reproduce it i think.

### Expected behavior
Either think about a way to reduce the time like maybe only comparing the differences between the previous saved file and the new saved file and make that changes in codemaid.

Or change the behavior of the spade so it is still accessible when it is refreshed so i would continue work with it even then.

**Comment by codecadwallader** [comment]
Thanks for making the request.  The current design is based on the EnvDTE APIs that do not provide a level of notification that allow us to update the code model progressively (i.e. one change at a time).  In the future we would like to rewrite to the new Roslyn based APIs that may allow us better capabilities to handle over-sized files.

**Comment by rainbowdesign** [comment]
I see that is unfortunate that you cannot get the response when the process is finished to update the spade. So you could let the old data in place till it is finished.

Then how about a manually entered delay after refresh would that work?
