### ISSUE TITLE
Code must not contain trailing whitespace	

### ISSUE THREAD

**Issue by alexandrius007** [codecadwallader/codemaid#360]
### Environment
- Visual Studio Enterprise 2015
- CodeMaid version: 10.1.93
- Code language: [example C#]
### Description

Afrer  code clean there are spaces in end of comment line
Warning SA1028  Code must not contain trailing whitespace   

```
    /// Acks this instance.**_**
```

For Example:
 /// <summary>

        /// Acks this instance.
        /// </summary>

**Comment by alexandrius007** [comment]
![image](https://cloud.githubusercontent.com/assets/23076423/19724976/ade7ad44-9b8b-11e6-8434-2bb1460621e1.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, but I have been unable to reproduce it.  Can you attach an export of your settings?

**Comment by alexandrius007** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="SteveCadwallader.CodeMaid.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <SteveCadwallader.CodeMaid.Properties.Settings>
            <setting name="Cleaning_ExclusionExpression" serializeAs="String">
                <value>.*\.Designer\.cs||.*\.Designer\.vb||.*\.resx</value>
            </setting>
            <setting name="General_Multithread" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Cleaning_PerformPartialCleanupOnExternal" serializeAs="String">
                <value>1</value>
            </setting>
            <setting name="Formatting_CommentRunDuringCleanup" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Reorganizing_RunAtStartOfCleanup" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Cleaning_UpdateAccessorsToBothBeSingleLineOrMultiLine"
                serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Formatting_CommentXmlAlignParamTags" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Cleaning_RemoveRegions" serializeAs="String">
                <value>2</value>
            </setting>
            <setting name="Reorganizing_RegionsRemoveExistingRegions" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="Formatting_CommentXmlSpaceTags" serializeAs="String">
                <value>True</value>
            </setting>
        </SteveCadwallader.CodeMaid.Properties.Settings>
    </userSettings>
</configuration>

**Comment by alexandrius007** [comment]
[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/556096/CodeMaid.zip)
Attached file

**Comment by codecadwallader** [comment]
Sorry that this slipped off my radar for so long.  I am able to reproduce the issue by running a comment format with your set of settings included.  @willemduncan would you like to take a look?  It looks like the trailing space is being inserted.

**Comment by alexandrius007** [comment]
I inserted animation where You could see trailing whitespace 
![animation](https://cloud.githubusercontent.com/assets/23076423/20829363/685d10b4-b884-11e6-9f29-344d108990f7.gif)

**Comment by willemduncan** [comment]
Ah, located it. It's because of the `Formatting_CommentXmlSpaceTags` set to `true`. This should add space between XML tags and content:

```cs
/// <summary> Like so </summary>
```

In case of multiline XML tags, the erroneous extra space appears.
