### ISSUE TITLE
Feature request - Setting wrapping comment column on-the-fly

### ISSUE THREAD

**Issue by lsmith999999** [codecadwallader/codemaid#364]
Hi there,

First, thanks for a great product. I'm the author of TranSolution (http://www.hexadigm.com) and really appreciate your efforts. Not sure if this is where feature requests go but I've got one that *may* be fairly simple to implement. I'm forever wrapping comments via <Ctrl+M, N> and would like to be able to quickly change the wrapping column on-the-fly, without having to launch settings all the time. It would be nice if you could add, say, a "Prompt each time" checkbox under the "Wrap comments at column" setting. It could be off by default for backwards compatibility but when checked, <Ctrl+M, N> would then display a small dialog with a single field for entering the column on-the-fly (initialized to the last value entered on this dialog which would initially be the "Wrap comments at column" setting itself). This would then override the "Wrap comments at column" setting so once OK is pressed (on this new dialog), wrapping would then use the newly entered column value instead of the one from settings (and the new value will also be used to initialize the same dialog next time I press <Ctrl+M, N>). You could even add (time permitting) a few extra check boxes on this dialog if you want, such as an "Update settings with this new value" check box (if checked then the "Wrap comments at column" setting itself will be updated), a "One time only" check box (if clear, the newly entered value will be used to initialize the same dialog next time but if checked, then it won't), etc. You'ld have to think about some of this of course (I haven't thought through all the details), but it would be a very useful feature (and maybe fairly quick to implement but only you know that of course). As an alternative, if you want to get really fancy (as if you have the time :), you can even consider wrapping all text using the right-most column of the currently selected text block. That is, if I highlight a block of text (normally comments), as currently described here https://msdn.microsoft.com/en-us/library/729s2dhh(v=vs.100).aspx (Google for "How to: Select and Change Text Visual Studio" if the link is now dead - quotes not included of course), in particular a rectangular block of text using "Column (Box) Mode" (search for this in the latter link), it would be nice if I could then format everything in that block using some hot key (or whatever). No column number would then have to be entered since the block itself defines the wrapping area (the right-most column anyway). In any case, some way to quickly set the wrapping column on-the-fly would be very useful. On the surface the first idea above in particular (or some hybrid) hopefully wouldn't take much effort. Thanks very much for your consideration (appreciated).

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I'm glad to hear that you like CodeMaid.  It does sound like a fairly specific feature request for your use case (I haven't heard anyone else mention customizing line lengths on the fly) but we can leave this issue open to see if there's any other interest in it.

**Comment by lsmith999999** [comment]
Ok, thanks for the feedback. I know it ‘s probably a long shot since it’s based on demand but comment blocks aren’t just confined to function headers of course (where the comment width would normally be fixed for all functions). Often people are commenting the code itself and may not want specific comments to extend as far over as the comments in the function header. Or sometimes just the opposite occurs. Code code can extend far to the right on occasion (naturally) so if you’re writing a line of code that starts at, say, column 60, and you place comments just above it, when you format those comments then there’s not much space to work with if the comments column is set to, say 80 (but may even be less than 60!). That leaves just 20 (or 21?) characters to work with so the formatted comments will be very narrow (and can extend vertically down for some distance if the comments are long). To circumvent it of course you need to go into the CodeMaid settings and update the comments width (and then restore it to the default value when done). I do this so frequently that it’s very annoying, though still much better than manually formatting the comments myself (and I do greatly appreciate the product notwithstanding this situation). It’s just very inflexible but it’s meant to be constructive, not critical [Smile] . Anyway, I understand that features are normally implemented based on demand (for any product including my own), but since you’ve already coded this feature and it probably would be relatively simple to implement this (presumably you can just call your “Wrap()” function, passing in the comments column that can now be entered in the pop up dialog previously discussed), it’s really a matter of making an existing feature better (by allowing developers to call it on-the-fly, without having to change it in settings each time). Anyway, food for thought. I might just write it myself at some point though I’m not sure if you’ld like me to hand the code off to you (np if I ever decide to tackle it). Anyway, thanks again.

**Comment by willemduncan** [comment]
Would a simple configurable "minimum wrap length" fix this? That would be easy to implement (it's already there, just not configurable).
