### ISSUE TITLE
Request: CodeMaid for VS2017

### ISSUE THREAD

**Issue by 0xFireball** [codecadwallader/codemaid#371]
are there any plans to add VS 2017 RC support? VS2015 will likely not get support for the new .NET Core tooling that ships with VS 2017, so .NET Core developers will have to move to VS 2017 to use the new MSBuild project format, as far as I know.

BTW, CodeMaid is awesome, I can't live without it

**Comment by codecadwallader** [comment]
Yep, we are planning to support it.  We have one known issue with cleanup with a posted workaround (see #355).  As you encounter other issues please report them!

Thanks for the kind comments too, that always helps with motivation. :)

**Comment by codecadwallader** [comment]
I'm going to go ahead and leave this open until the next milestone release to make it easier for other people to find the answer to the same question.

**Comment by codecadwallader** [comment]
I've got a local build of this up and running.  I'm working on getting this out into our CI channel.

**Comment by codecadwallader** [comment]
This is now live in our [CI channel](http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/).  Experimentation welcome!
