### ISSUE TITLE
Is disabling comment formatting possible?

### ISSUE THREAD

**Issue by protoze** [codecadwallader/codemaid#379]
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.1
- Code language: c#

### Description
I'm using a third party library which parses markdown from the method summaries to auto-generate some documentation.  However, Codemaid automatically strips out any whitespace that's required for the markdown.  Is there a way to turn this off?
 
### Steps to recreate
1. Create an empty method with a summary tag.
2. Leave trailing spaces in the summary description.
3. Leave codemaid auto cleanup on save enabled.
4. Save file.

### Current behavior
Trimming the whitespace.

### Expected behavior
There should be a way to turn this off.

**Comment by codecadwallader** [comment]
Yes, you can ask CodeMaid to leave trailing whitespace at:

CodeMaid->Options->Cleaning->Remove->"Remove end of line whitespace".
