### ISSUE TITLE
Duplicated using when Run remove and sort using statements is enabled

### ISSUE THREAD

**Issue by mikequinlan** [codecadwallader/codemaid#380]
### Environment
- Visual Studio version: 2017 RC Community
- CodeMaid version: 10.2.5
- Code language: C#

### Description
In rare cases, a second #using System.Linq statement is added when Run remove and sort using statements is enabled.

### Steps to recreate
The CodeMaid Cleaning/Visual Studio options say to re-insert these using statements

> using System;
> using System.Collections.Generic;
> using System.Linq;
> using System.Text;
> using System.Threading.Tasks;

With the attached file opened in the VS editor, select Cleanup Active Document from the CodeMaid menu.

### Current behavior
The using section at the top of the file changes to

> using System;
> using System.Collections.Generic;
> using System.Globalization;
> using System.Linq;
> using System.Runtime.CompilerServices;
> 
> using System.Linq;

Note the blank line and the second using System.Linq statement at the bottom; these two lines are added.

### Expected behavior
The blank line and second using System.Linq statement should not be added.

I've attached a simple file that (for me) re-creates the problem and an export of my CodeMaid settings.

[CMTest.zip](https://github.com/codecadwallader/codemaid/files/677789/CMTest.zip)

[CodeMaid.zip](https://github.com/codecadwallader/codemaid/files/677791/CodeMaid.zip)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  There are some known limitations with the re-insert using statements logic.  Please see #87 and #293 .  Help would be welcome!
