### ISSUE TITLE
Not accessible from Visual Studio Professional 2017 RC

### ISSUE THREAD

**Issue by tyress** [codecadwallader/codemaid#387]
### Environment
- Visual Studio version: 2017 Professional RC, .NET 4.6.01586
- CodeMaid version: 10.2.7
- Code language: C#

### Description
I downloaded the CodeMaid vsix installer and it prompted me to install on Visual Studio 2017 (I have it for 2015 professional and it works well). Can't seem to get it to show?

### Steps to recreate
1. Install on VS 2017 (version stated)
2. Open VS, no Codemaid toolbar

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Some questions:

- Did the installer report installing successfully?
- Does CodeMaid show up in Tools->Extensions & Updates?  What state is it in?
- To clarify there is no CodeMaid toolbar, but there is a CodeMaid menu.  I assume that's what you're not seeing at all?
- If you uninstall from Tools->Extensions & Updates (if present), restart VS, and install from within Tools->Extensions & Updates does that change the behavior?

**Comment by tyress** [comment]
**Does CodeMaid show up in Tools->Extensions & Updates? What state is it in?**
Sheesh, I found it here and enabled it and it works now. I didn't have to do this for the 2015 version. Thanks

**Comment by codecadwallader** [comment]
Cool, glad it worked out.
