### ISSUE TITLE
Feature Request : Cleanup files in current project.

### ISSUE THREAD

**Issue by mikebarber1** [codecadwallader/codemaid#392]
### Environment
- Visual Studio version: 2012 Pro +
- Code language: c#

### Description
Frequently when working on a project I find myself wanting to use CodeMaid to Cleanup all the files in 1 project but there isn't an option to do that. I can do cleanup on Active, Open, or All. but not All files in one project. Cleanup Open is the closest match but it's tedious because I have to manually open all the files in the project. Cleaning up all is not an option as that would checkout the entire solution and be risky and very messy in source control.

**Comment by codecadwallader** [comment]
It's your lucky day.  Right click on the project in the solution explorer and choose "Cleanup Selected Code" to cleanup any highlighted selection in the Solution Explorer. :)
