### ISSUE TITLE
FeatureRequest: Clear Solution Explorer search query before Find in Solution Explorer

### ISSUE THREAD

**Issue by joeburdick** [codecadwallader/codemaid#393]
### Environment
- Visual Studio version: 2015
- CodeMaid version: 10.2
- Code language: N/A

### Description
Currently, if you have a search query in your Solution Explorer and then use the "Find in Solution Explorer" feature on a file which does not match your search query, it instead opens a file which is currently in the Solution Explorer.

### Steps to recreate
1. Open a file.
2. Enter a search query into Solution Explorer which will not have your open file as a result.
3. Use "Find in Solution Explorer" on your open file.

### Current behavior
A file in your filtered Solution Explorer is opened.

### Expected behavior
The Solution Explorer's search should be cleared, and then the currently open file should be found in Solution Explorer.

Maybe this can be an option in settings?

**Comment by codecadwallader** [comment]
Thanks for the suggestion.

A code starting point for anyone interested in pursuing: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Integration/Commands/FindInSolutionExplorerCommand.cs#L53

**Comment by codecadwallader** [comment]
Thanks for implementing this!
