### ISSUE TITLE
Issue Formatting Headers in VS2017

### ISSUE THREAD

**Issue by RealDotNetDave** [codecadwallader/codemaid#396]
I just installed CodeMaid in VS2017. When I run cleanup, it turns this:

// ***********************************************************************
// Assembly         : dotNetTips.Utility.Standard
// Author           : David McCarter
// Created          : 01-22-2017
//
// Last Modified By : David McCarter
// Last Modified On : 01-22-2017
// ***********************************************************************
// <copyright file="ControlChars.cs" company="dotNetTips.Utility.Standard">
//     Copyright (c) dotNetTips.com - McCarter Consulting. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

Into this:
// *********************************************************************** Assembly : dotNetTips.Utility.Standard Author : David McCarter Created : 01-22-2017
//
// Last Modified By : David McCarter Last Modified On : 01-22-2017 ***********************************************************************
// <copyright file="ControlChars.cs" company="dotNetTips.Utility.Standard">
//     Copyright (c) dotNetTips.com - McCarter Consulting. All rights reserved.
// </copyright>
// <summary>
// </summary>
// ***********************************************************************

I tried changing the wrapping column to 500 but it still messes up the formatting of this header.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Please see #381 for some more information.

**Comment by RoyBradley** [comment]
This is also a problem wit VS 2019

**Comment by codecadwallader** [comment]
@RoyBradley Please take a look at #381 to see if it helps answer your question.
