### ISSUE TITLE
[C#] Allow us to sort usings automatically on save (*without* removing them!)

### ISSUE THREAD

**Issue by BrainSlugs83** [codecadwallader/codemaid#398]
### Environment
- Visual Studio version: 2015 Enterprise, Update 3
- CodeMaid version: 10.2
- Code language: C#

### Description
Codemaid allows you to remove and sort usings on save, but not to just sort them. -- This is very frustrating for us.

(Also, adding back in specific usings is broken, because it does it after the sort, so they come in unsorted and duplicated, etc.)

Please give us a way to automatically reorder our usings on save (without removing them).

(You can do this manually in Visual Studio via, Right-Click, Organize Usings, Sort Usings; or through the Visual Studio command "Edit.SortUsings".)

### Current behavior
It looks like there are already separate keys in the .config file to support this behavior (but no option in the UX), and the keys do not work as anticipated (for example, the below code will still cause usings to be removed on save, which is not what we want):

```
<setting name="Cleaning_SkipRemoveAndSortUsingStatementsDuringAutoCleanupOnSave"
         serializeAs="String">
  <value>False</value>
</setting>
<setting name="Cleaning_SkipRemoveUnusedUsingStatementsDuringAutoCleanupOnSave"
         serializeAs="String">
  <value>True</value>
</setting>
```

### Expected behavior
Give us separate checkboxes in the dialog, one for "Remove usings during cleanup", and one for "Sort usings during cleanup", and make the automatic clean-up on save respect those options.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Starting with VS2017, Visual Studio has gone away from having two separate commands and there is now only combined command that both removes and sorts using statements.  We deliberately changed CodeMaid to follow suit with the 10.2 release last month.

Commit: https://github.com/codecadwallader/codemaid/commit/eb294fc741efe539d45abe41c186869560dd02f6

The setting names changed starting in 10.2 so the artifact you see is from a configuration file created with an older version.

If you would like the older behavior, you may revert to the 10.1 release available in downloads https://github.com/codecadwallader/codemaid/releases/tag/v10.1 or create a fork and unroll the changes in the commit listed above.

Hope it helps.
