### ISSUE TITLE
Detection of XAML Styler 2.4 does not work

### ISSUE THREAD

**Issue by nrusitska** [codecadwallader/codemaid#401]
### Environment
- Visual Studio version: 2015 Enterprise
- CodeMaid version: 10.2
- Code language: C#
- XAML Styler version: 2.4
### Description
The latest version [2.4] of XAML Styler is not detected by Codemaid anymore.

We added CodeMaid and then XAML Styler to a fresh Visual Studio 2015 Enterprise installation. XAML Styler is not detected anymore. Previous versions up to 2.3 of XAML Styler are still detected.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I don't follow/use XAML Styler, but it's possible they may have changed their command names with their latest release.  If you want to reach out to them or dig through their code you may be able to find what the new commands are called and we can make updates (or you can issue a pull request).

The relevant code in our codebase that will need updated: https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/CodeCleanupManager.cs#L481

**Comment by grochocki** [comment]
This issue was just recently reported in [XamlStyler Issues](https://github.com/Xavalon/XamlStyler/issues/115). PR incoming with updated command.

**Comment by codecadwallader** [comment]
Excellent, thank you for addressing this!
