### ISSUE TITLE
Reorganizing active VB.NET document damages code

### ISSUE THREAD

**Issue by 0ndrej** [codecadwallader/codemaid#403]
### Environment
- Visual Studio version: Visual Studio Community 2015 Update 3
- CodeMaid version: 10.2
- Code language: Visual Basic .NET

### Description
Reorganizing VB.NET document where are properties with 2+ attributes (data annotations) damages code.

### Steps to recreate
Create new VB.NET console application, add reference to System.ComponentModel.DataAnnotations and replace Module1.vb with code below. Then do CodeMaid/Reorganize Active Document.
```
Imports System.ComponentModel.DataAnnotations
Module Module1
  Sub Main()

  End Sub
  <Required(ErrorMessage:="Code can not be empty.")>
  <StringLength(25, ErrorMessage:="Code can not exceed 25 characters.")>
  Public Property Code As String
    Get
      Return _code
    End Get
    Set(value As String)
      _code = value
    End Set
  End Property
  Private _code As String
End Module
```

### Current behavior
Attributes are separated from their class member (property).

### Expected behavior
Attributes must move with their class member.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  A few questions:

1.  Does the behavior only happen when there are two attributes present?  In other words does it work as expected with one attribute?
2.  When the issue occurs does one of the attributes move and one get left behind?
3.  Does the order of the attributes matter (i.e. if you reverse them, is the behavior the same)?

**Comment by 0ndrej** [comment]
I tested it more and it happens with any number of attributes applied to class member. Attributes stay at bottom of source file and everything else is sorted as expected.

**Comment by codecadwallader** [comment]
Ok, thanks for confirming.  That reminded me there is an existing issue #333 with some other notes.  Lets close this one in favor of that.

**Comment by 0ndrej** [comment]
By referencing contribution in issue #333 you mean that you will not fix it?

**Comment by codecadwallader** [comment]
Please read the whole thread for context on why contribution was mentioned.  As an open source project contributions are extremely encouraged to expedite specific requests.
