### ISSUE TITLE
Feature request: Remove region name from  #endregion tags

### ISSUE THREAD

**Issue by thomasdon** [codecadwallader/codemaid#405]
### Environment
- Visual Studio version: [example 2015 Community]
- CodeMaid version: [example 10.2]
- Code language: [example C#]

### Description
Replace this text with a short description and code sample.

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong.

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by codecadwallader** [comment]
You can disable CodeMaid's setting of the region name on endregion tags at CodeMaid->Options->Cleaning->Update->"Update #endregion tags with region name"

**Comment by thomasdon** [comment]
Let me clarify: Let's say that I use CodeMaid to put #endregion tags, but later I decide I want to remove the tags, I can't do that in CodeMaid, can I?
Don Thomas

**Comment by codecadwallader** [comment]
Correct, there isn't a command built into CodeMaid that will undo the #endregion tags containing the region names it added.

An easy way to accomplish that would be to perform a find/replace using regular expressions.  Something like:

Find: #endregion.* Replace: #endregion
