### ISSUE TITLE
Visual Studio MPF 11.0 Needed when Updating CodeMaid to 10.2.7 on Visual Studio 2010

### ISSUE THREAD

**Issue by astrohart** [codecadwallader/codemaid#407]
### Environment
- Visual Studio version: 2010
- CodeMaid version: [example 0.8.1
- Code language: C#

### Description
Trying to use the Visual Studio Extension Manager in VS2010 to upgrade the CodeMaid (installed: 0.8.1, new version showing available: 10.2.7, as in the first picture attached).

### Steps to recreate
1. Open Microsoft Visual Studio 2010 the latest service pack.  CodeMaid 0.8.1 should already be installed.
2. Then click the **Tools** Menu, and then click **Extension Manager**.
3. Click **Updates**.
![pic1](https://cloud.githubusercontent.com/assets/8261875/23486466/209991a6-fe95-11e6-845a-ecafb6feee83.png)
4. CodeMaid should be listed as requiring an update.  Click **Update**.
5. The error shows.
![pic2](https://cloud.githubusercontent.com/assets/8261875/23486468/238b0e9e-fe95-11e6-8595-e725089d13a9.png)

### Current behavior
I try searching on the text Visual Studio MPF 11.0 in the **Online Gallery** section of the **Extension Manager**, to no avail.  Google search also comes up empty.

### Expected behavior
If this version of CodeMaid (10.2.7) is not compatible with VS2010, I would expect that code be added to prevent it being displayed in the **Extension Manager** window as being in need of an update.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  CodeMaid v0.8.1 is indeed the last supported version for VS2010 (see https://github.com/codecadwallader/codemaid/blob/master/README.md)

There is code in place within the manifest that tells Visual Studio which versions are supported (see https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/source.extension.vsixmanifest#L16)  That manifest appears to be defined correctly as confirmed by the VS gallery which shows supported versions (see https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid)

I'm sorry to hear that you ran into a time sink and agree that it was misleading for Visual Studio to suggest an upgrade to an unsupported version.
