### ISSUE TITLE
Build progress

### ISSUE THREAD

**Issue by ajtruckle** [codecadwallader/codemaid#410]
2017 rc

Mfc project

Build progress doesn't show any progress

**Comment by codecadwallader** [comment]
Do you have a sample solution that exhibits the issue?

**Comment by ajtruckle** [comment]
I am afraid my project is a bit too big for that. But don’t worry as I don’t need these features myself. I really only  installed the utilities initially for sorting lines of text.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
