### ISSUE TITLE
"Run XAML Styler cleanup" toggle just can't enable!

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [codecadwallader/codemaid#411]
### Environment
- Visual Studio version: 2017 Ent
- CodeMaid version: 10.2
- Code language: C#/UWP

### Description
I install the "XAML Styler", but "Run XAML Styler cleanup" toggle can't switch to enable!

### Steps to recreate
1. Install Xaml Styler/CodeMaid.
2. Install CodeMaid/Xaml Styler.

**Comment by codecadwallader** [comment]
Please see #401 - we think they've changed their command names and just need to know the new information to update accordingly.
