### ISSUE TITLE
Wrap comments that don't have space after comment-symbol

### ISSUE THREAD

**Issue by JVimes** [codecadwallader/codemaid#423]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: 10.3
- Code language: all

### Description
Right now, the wrapping of long comments doesn't work on a line that starts like this:

    //A long comment...

I have to add a space after the `//` to make it work. Same happens in other languages, like PowerShell where `#` is the comment symbol.

Suggest wrapping comments, even if they don't have a space between the comment symbol and the comment text. For example, I'd expect comment formatting to wrap both of these cases:

    //A long comment...

and

    // A long comment...

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  The requirement for a space after the comment prefix is deliberate to avoid wrapping or otherwise formatting commented out code.  Please see #106 for some more history.

Hope it helps.

**Comment by JVimes** [comment]
Ah, thanks for explanation. Wish there were a better way to type/past, then comment and wrap via keyboard without backspacing. I'll think on it.

**Comment by codecadwallader** [comment]
Sure, if you come up with any ideas contributions are welcome. :)
