### ISSUE TITLE
VS2010 Extension manager keeps prompting to update extensions and CodeMaid is showing needing an update.  But, the new version isn't compatible with VS2010.  Need to 'hide' the update or make the latest CodeMaid backwards-compatible.

### ISSUE THREAD

**Issue by astrohart** [codecadwallader/codemaid#425]
### Environment
- Visual Studio version: Microsoft Visual Studio 2010
- CodeMaid version: 0.8.0
- Code language: C#

### Description

I utilize several versions of Visual Studio on the same machine, due to needing support for legacy .csproj and .sln files that I don't want to upgrade to the latest format.  The latest version of CodeMaid, version 10.3.29, is not backwards compatible to Microsoft Visual Studio 2010.  It needs to be, according to software best practices as established by Microsoft.  Because it's screwing up my Extension Manager and annoying me as well. :-)

### Steps to recreate
I recently installed the Productivity Power Tools extension for Visual Studio, from:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerTools

I like this extension and use it heavily.  One of its features is to show a balloon popup from the tray if new extension updates are available:

![fig1](https://cloud.githubusercontent.com/assets/8261875/24518066/6953728e-1535-11e7-8f1f-5b0adaf171c9.png)

When I click on this notification, I get the Extension Manager, already navigated for me to the Updates tab, as shown:

![fig2](https://cloud.githubusercontent.com/assets/8261875/24518101/8533afaa-1535-11e7-9096-2b8527ec7dee.png)

Then, I get the following error:

![fig3](https://cloud.githubusercontent.com/assets/8261875/24518161/d2876c7e-1535-11e7-89e8-41c555167331.png)

I am not sure how to deal with this.  I recommend making all future versions of CodeMaid backwards-compatible.  Microsoft has done this with, e.g., Microsoft Office.  It's a software-development best practice.

Either that, or do you know of a way to hide updates in Extension Manager?

I like to always keep my tools as up to date as possible.

### Expected behavior

All future releases of CodeMaid show as updates in the Visual Studio 2010 Extension Manager and install with no errors.  I am not saying you have to add support for CodeMaid's latest features in VS2010; the .vsix installer file should just be backwards compatible.

**Tip: **  Why not the following (just an idea):  No changes to the CodeMaid software itself.  However, maybe, write logic in the .vsix file to detect Visual Studio 2010 and not throw an error, but just silently "tell Visual Studio, okay, the extension is updated!"  Or, somehow tell Visual Studio 2010 to just remove the update for CodeMaid in the Extension Manager.  I am not sure how that would be implemented, but something to make this notification go away.

**Comment by codecadwallader** [comment]
Please see #407 which I believe you reported previously, I do not have any further ideas about how to address the issue you are seeing.

**Comment by astrohart** [comment]
Well, I don't know what to say Steve obviously the issue isn't fixed because it still is happening.Brian HartOn March 30, 2017 at 5:04 PM Steve Cadwallader <notifications@github.com> wrote:Please see #407 which I believe you reported previously, I do not have any further ideas about how to address the issue you are seeing.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
