### ISSUE TITLE
Feature Request: Insert blank lines before/after single-line fields

### ISSUE THREAD

**Issue by Cophla** [codecadwallader/codemaid#433]
### Environment
- 2017 Community]
- 10.3
- C#

### Description
i want to remove any blank line between class fields or force inserting a blank line between class fields
```
public class TblSurveyCustomer : AGSurveyDb<int>
{
		#region Private Fields

		private static int _listCount = 100; // Code Maid Is Not Adding New Line OR
		private short _countryId; // Removing Blank Lines Between Private Fields

		private string _customerAddress;

		private DateTime _dateAdded;

		private DateTime _dateOfBelonging;

		private DateTime _dateOfBirth;

                #region Private Fields
}
```

### Steps to recreate
1. Mainly With Default Settings

### Current behavior
Some class fields have new line between and some with no blank line between

### Expected behavior
Force blank line or force remove blank line

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  We do not currently have a configuration for inserting/removing blank lines on single line fields.  We do have configuration options for inserting blank lines between multi-line fields (e.g. those with leading comments).

**Comment by codecadwallader** [comment]
The relevant code for anyone interested in pursuing:

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/InsertBlankLinePaddingLogic.cs#L79

https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/InsertBlankLinePaddingLogic.cs#L140

This should be a very straight forward clone of the logic for single-line properties vs. multi-line properties.  Similar to single-line properties, it should be off by default in configuration.

**Comment by Cophla** [comment]
Thanks,
Best wishes and more progress in good

**Comment by codecadwallader** [comment]
Thanks, I appreciate it.  Lets leave this open (edited title) as a feature request for anyone interested in running with it.  It would be a great warming up activity for someone new.
