### ISSUE TITLE
Properties and Methods not being sorted

### ISSUE THREAD

**Issue by edipper** [codecadwallader/codemaid#434]
### Environment
- Visual Studio version: [2015 Professional]
- CodeMaid version: [10.3]
- Code language: [C#]

### Description
When running CodeMaid "Cleanup Active Document" it does not sort the properties and methods

### Steps to recreate
1. Run "Cleanup Active Document"

### Current behavior
It is not sorting methods and properties in alphabetical order and by scope and so on

### Expected behavior
It should be sorting methods and properties in alphabetical order and by scope and so on

**Comment by codecadwallader** [comment]
It sounds like you are talking about our reorganizing feature.  Select "Reorganize Active Document" instead. of "Cleanup Active Document" which is more whitespace oriented.  If you want Cleanup operations to include Reorganization, there is a configuration option for that at CodeMaid->Options->Reorganizing->General->"Run reorganize at startup of cleanup" (off by default).

**Comment by edipper** [comment]
That’s it…thanks.

**Comment by codecadwallader** [comment]
np 👍
