### ISSUE TITLE
CodeMaid / CodeCompare / VS2017 crash

### ISSUE THREAD

**Issue by rtigithub** [codecadwallader/codemaid#435]
### Environment
- Visual Studio version: 2017 Professional version 15.0.26403.3
- CodeMaid version: 10.3.33
- Code language: C#
- Windows Version	10.0.15063 Build 15063
- CodeCompare version: 4.2.221

### Description
If I install Devart CodeCompare and CodeMaid, VS2017 crashes at startup with an unhandled .NET exception.

### Steps to recreate
1. Install CodeCompare
2. Install CodeMaid
3. Launch VS2017

To fix launch devenv in safemode and uninstall CodeMaid.
If I run VS2017 with CodeCompare installed and not CodeMaid, it runs without issue.  If I disable CodeCompare in Extensions dialog and then install CodeMaid, VS2017 runs without issue.  If I re-enable CodeCompare and launch VS2017, it crashes at startup.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Does anyone use CodeCompare that can chime in on this issue?  I'm a Beyond Compare user myself.

**Comment by rtigithub** [comment]
I would love to debug this but I cannot figure out how to catch an exception thrown by devenv at startup.  If I enable CodeCompare and build and launch your source, the experimental instance of VS2017 loads but then I get a System.AccessViolationException with no other details.

**Comment by codecadwallader** [comment]
I appreciate that you're trying to debug it.  If you don't enable CodeCompare, does the experimental instance load successfully?  If so perhaps that AccessViolationException is a clue.  Another option would be to try debugging another open source extension and see if the AccessViolationException is related to CodeCompare+CodeMaid, or CodeCompare+Anything.  Mads Kristensen has dozens and dozens such as https://github.com/madskristensen/SolutionExtensions

**Comment by rtigithub** [comment]
I cleaned all instances of CodeMaid and Codecompare off of my development system.  I then installed Codemaid followed by CodeCompare.  This appears to have solved the problem for today.  Please mark this as resolved.

**Comment by codecadwallader** [comment]
Glad to hear it, thanks for following up.
