### ISSUE TITLE
Modify Reorganize to ignore and/or prioritize certain fields by name.

### ISSUE THREAD

**Issue by necoras** [codecadwallader/codemaid#438]
Would it be possible add the ability to customize Codemaid's Reorganize functionality to group certain fields based on the field's name? My specific use case is that all of my models have an "id" field and I'd like it to be at the top of the file, not somewhere in the middle. I'm sure there are other similar use cases I'm not immediately considering.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  There have been a couple similar requests in the past (see #436 and #317) but we do not yet have a way to annotate code to provide custom instructions to CodeMaid.
