### ISSUE TITLE
Performing unnecessary formatting inside .min file types

### ISSUE THREAD

**Issue by Saif03** [codecadwallader/codemaid#440]
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.3
- Code language: ASP.Net

### Description
I believe CodeMaid should not alter the spacing(s) inside .min file types by default; so they can continue to serve their purpose of staying maximum minified. I didn't knew (by default) it would go on and alter them.

To avoid this in the future I tried adding an exception for *.min.css$ and *.min.js$ file types in the exception list. But that generates some error "parsing *.min.js$ - Quantifier {x,y} following nothing."

What would be the proper exception ? and for the betterment of others this behavior should be added by default.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I agree that minimized files should not be cleaned.  The following two expressions worked for me:

`\.min\.css$`
`\.min\.js$`

I have updated the defaults and it will be present in the next release.  Thanks again for highlighting it.
