### ISSUE TITLE
How to not sort properties in a class?

### ISSUE THREAD

**Issue by pcolmer** [codecadwallader/codemaid#441]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: 10.3
- Code language: C#

### Description
I'm defining some classes for use in a database, e.g.:

    public class Person
    {
        public int ID { get; set; }
        public bool Private { get; set; }
        public Gender Gender { get; set; }
        public List<Name> Names { get; set; }
        public List<Fact> Facts { get; set; }
    }

After reorganising, the properties get sorted:

    public class Person
    {
        public List<Fact> Facts { get; set; }
        public Gender Gender { get; set; }
        public int ID { get; set; }
        public List<Name> Names { get; set; }
        public bool Private { get; set; }
    }

I actually find this harder to read in terms of making sure that all of the properties are present and correct.

Is there a way of stopping this from happening whilst still letting CodeMaid sort enums, methods, etc in alphabetical order?

**Comment by codecadwallader** [comment]
Thanks for the suggestion. There have been a couple similar requests in the past (see #436 and #317) but we do not yet have a way to annotate code to provide custom instructions to CodeMaid.

**Comment by rodolfoperez-making** [comment]
Hi pcolmer,

I had the same issue, and found a solution. It's not so clean, but I managed to keep my "Id" properties at the beginning of the class definition. The tick is, if you enclose a property inside a regions, then won't be sorted

![image](https://user-images.githubusercontent.com/68697726/168180061-aa6a2eff-0d53-4207-a0d5-dbf205f86a5d.png)

Without the region gets shorted alphabetically
![image](https://user-images.githubusercontent.com/68697726/168180158-134800a2-0697-4c93-8684-e28b3f64764a.png)

**Comment by darrenw-npi** [comment]
Good workaround. Annotations would be good though. Maybe something like a [ExcludeFromSorting] attribute...
