### ISSUE TITLE
Error on VS start

### ISSUE THREAD

**Issue by qwertypal** [codecadwallader/codemaid#443]
### Environment
- Visual Studio version: 2012 Prof, update 4
- CodeMaid version: latest
- Code language: C++

### Description
Error on VS start displayed...
Error description in log file:
```
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CodeMaidPackage]</description>
    <guid>{4C82E17D-927E-42D2-8460-B473AC7DF316}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Exception has been thrown by the target of an invocation.</errorinfo>
```

### Steps to recreate
1. Install the plugin
(Note: I do not have administrative privileges on the computer)
2. Start VS

### Current behavior
On VS start CodeMaid menu options are greyed out

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Can you confirm which CodeMaid version you are trying to install and what version of .NET you have installed?  One other user needed to install NET 4.6.2 with the latest release of CodeMaid.

**Comment by codecadwallader** [comment]
See #437

**Comment by qwertypal** [comment]
Thank you for your reply. Without administrative privileges I am unable to update to 4.6.2 at this point. 
I have got the following:
CodeMaid v10.3.29
.NET Framework 4.5.50709
Could I, perhaps, revert to older versions of CodeMaid ?

**Comment by codecadwallader** [comment]
Sorry to hear you do not have administrative privileges, I've been there before.

Yes, old versions are available here on GitHub.  Here is the link for v10.2: https://github.com/codecadwallader/codemaid/releases/tag/v10.2

**Comment by qwertypal** [comment]
Thank you, version 10.2 works!

**Comment by codecadwallader** [comment]
Glad to hear it. :)
