### ISSUE TITLE
Running Integration Tests on Current Build of the Extension

### ISSUE THREAD

**Issue by mlangkabel** [codecadwallader/codemaid#453]
Even though this is not really an issue with CodeMaid, I'll post my question here so others can learn from the answer as well.

I'm currently working on a Visual Studio extension. I was really impressed by the way you guys have set up the CodeMaid project so I was trying to use it as a guidline. However, when I wanted to add some automated integration tests I ran into this issue:

*How do you get the integration tests to use the current build of the extension?*

My own tests seem to be using the version of the extension that is installed for the instance of Visual Studio that is started by the tests. So when I fix some issue inside the extension's code base and I want to re-run my own tests I first need to make a release buid of my extension, close my Visual Studio instance, install that new build, restart Visual Studio and then I can run the tests on the updated extension. Did you figure out a way to make your tests automatically use the current build of the CodeMaid extension?

**Comment by codecadwallader** [comment]
Great question.  When you debug your extension, you would be using the Experimental Instance of Visual Studio (setup by default with Microsoft's templates, or you can explicitly setup by changing the build arguments).  See https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/CodeMaid.csproj.user#L6

You'll want your integration tests to use the Experimental Instance as well.  To do that you can use integration test settings (see https://github.com/codecadwallader/codemaid/blob/master/IntegrationTests.testsettings) and be sure your IDE is pointing to those (see screenshot on http://www.codemaid.net/contribute/ under "Running Integration Tests")

Hope it helps!  As a full disclaimer, the integration tests have not been working for me in VS2017 and I haven't investigated long enough yet to figure it out.

**Comment by mlangkabel** [comment]
Thanks for the quick answer! I've just finished migrating our extension to Visual Studio 2017 today. So I'll definitely look into getting thost tests running on 2017. If I can figure out how to do that I'll tell you :)

**Comment by codecadwallader** [comment]
Perfect, thanks and good luck! :)

**Comment by mlangkabel** [comment]
After performing those three changes you described above our integration tests are now using the current build of the extension. And it works in Visual Studio 2017! 

So I guess that the problems you are experiencing when trying to run those tests for CodeMaid are caused by different parts of the project. I'm sorry that I couldn't help you with that issue.

**Comment by codecadwallader** [comment]
No problem, thank you for confirming and I'm very glad to hear you were able to get it to work! :)

**Comment by mlangkabel** [comment]
@codecadwallader: I think I found the issue with your integration tests: The `CodeMaid.IntegrationTests` project references the wrong version of the `Microsoft.VSSDK.TestHostFramework.dll`. You are shipping and using the version 14.0.0.0 but Visual Studio 2017 requires version 15.0.0.0 of that assembly to run the tests. 

At least that is what caused an issue with my own integration tests at the [Sourcetrail Extension](https://github.com/CoatiSoftware/vs-sourcetrail) project. To solve the issue I ship both versions of the assembly (14 and 15) and use a `<Choose>` condition inside the `csproj` file to choose the correct one depending on the used Visual Studio version.

**Comment by codecadwallader** [comment]
@mlangkabel Great, thank you for following up with that information!  You're right and I've made an update accordingly.  It looks like we still have some other updates to iron out so I've created a separate issue to get that covered, now that the basis is in place.  Thanks again and best of luck on your extension. :)
