### ISSUE TITLE
Codemaid complains file is not part of solution when it clearly is

### ISSUE THREAD

**Issue by dean1012** [codecadwallader/codemaid#454]
### Environment
- Visual Studio version: VS2017 Pro
- CodeMaid version: 10.4
- Code language: C++

### Description
Trying to run cleanup on file in a C++ project in the open solution results in codemaid complaining the file is external and only a partial cleanup can be done.

### Steps to recreate
1. Installed Codemaid for first time on VS2017 Pro
2. Attempted first cleanup

### Current behavior
Fails to do a full cleanup on most files. Some files like main.cpp work

### Expected behavior
All files added to the project should be capable of a full cleanup?

**Comment by dean1012** [comment]
Also I don't think this is related to #389 because as far as I'm aware I have my solution/projects fully opened and not in "lightweight" mode.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  What is the size of your solution?  I believe they were talking about making LSL mode turn on by default if there were >=30 projects in a solution.  The best way to be sure that is not the case is explicitly expand the project within the Solution Explorer, double click on the file then attempt a cleanup.

**Comment by dean1012** [comment]
There are two projects in the solution with only a few files in each. The file in question was open and being edited at the time I tried to format.

**Comment by codecadwallader** [comment]
Ok, so there's a mix of files that are working and not working?  Can you help identify any differences between the files that do work and those that don't (e.g. in different projects, have different extensions, etc.)?

**Comment by dean1012** [comment]
Only had time for a quick test but it looks like files that are header only are affected. I'll test more later. I can also share my code privately if it comes to that.

**Comment by dean1012** [comment]
This issue is no longer relevant to me and has been open a long, long time so closing.
