### ISSUE TITLE
Feature request: Ignore file on automatic cleanup due to specific keyword in the header

### ISSUE THREAD

**Issue by codingdave** [codecadwallader/codemaid#457]
### Description
Hi,

I like to have automatic cleanup on save project wide s.t. team members have the same appearance of code. For sourcecode coming from foreign sources (e.g. google sources) I do not want automatic reformatting (not my code, complicates tracking changes with the origin. maybe read only for us, ...). 
I suggest having a keyword in the header s.t. Codemaid will skip that file if it finds that. This feature can be extended to Something like the feature of modelines in vim (http://vim.wikia.com/wiki/Modeline_magic).

### Steps to recreate
1. Have Codemaid set up to autoformat on save
2. Have foreigncode open that you do now want to change
3. Cntrl+Shift+S (Save all)
4. You will see that the foreign code is being reformatted

### Current behavior
The behavior is generally correct. However I want modularity to exclude individual files from that behavior.

### Expected behavior
It would be great if I could add something like 
// Codemaid: skip
in the header and codemaid would not do cleanup in that file.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  Have you checked out our existing cleanup exclusion options?

At CodeMaid->Options->Cleaning->File Types there is an area where you can specify regular expressions for file paths you would like to ignore.  So as an example, if you have an external project called MyThirdPartyHelpers you can add that to the list and all files within that folder would be ignored.  This has the advantage that you do not have to edit the underlying source files, just CodeMaid's configuration.

Additionally, you can export your settings and add them to source control if you want to share/enforce them across the team.

Hope it helps!

**Comment by codingdave** [comment]
Thank you, I did not realise that option before. This will be helpful for
my needs already. I will test that.

Thanks a lot,
Dave

2017-06-14 13:37 GMT+02:00 Steve Cadwallader <notifications@github.com>:

**Comment by codecadwallader** [comment]
Glad to hear it. :)
