### ISSUE TITLE
Feature request: add option to place 'System' directives first when sorting usings

### ISSUE THREAD

**Issue by hyperquantum** [codecadwallader/codemaid#465]
We use the "solution-specific settings" to make sure all developers commit code that uses the same formatting rules. There is one tiny problem here: we like to use the option to put 'System' usings at the top when sorting usings (both C# and VB), but not all developers have this option enabled, and we have to ask everyone individually to change their settings in the VS options dialog. This means navigating to Tools --> Options --> Text Editor --> C# --> Advanced and enabling the option there. Similar for VB. Developers who work on different projects sometimes need to change the setting regularly, depending on what solution they work on at the time.

This is a request to add the option "Place 'System' directives first when sorting usings" to the CodeMaid settings so that the option can be correctly set for all developers at once in the solution-specific settings.

I guess this would mean that CodeMaid has to implement the 'sort usings' itself instead of asking Visual Studio to do it. But this would also be a requirement for issue #151.

Thank you for this very useful VS extension!

**Comment by codecadwallader** [comment]
Thanks for the suggestion and I'm glad you find CodeMaid useful. :)

Visual Studio has been recently working on supporting more solution-level settings themselves as well.  I'm not sure if they support that specific option yet, but check out https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/ for more information and to see if it might help your scenario.

**Comment by codecadwallader** [comment]
It looks like they might.. I didn't see in the documentation but I did see in the comments:

`dotnet_sort_system_directives_first = true`

**Comment by Eli-Black-Work** [comment]
@hyperquantum Can this be closed? I think the proper solution nowadays is to add a .editorconfig file and configure it with `dotnet_sort_system_directives_first = true`, as mentioned above 🙂

**Comment by hyperquantum** [comment]
> @hyperquantum Can this be closed? I think the proper solution nowadays is to add a .editorconfig file and configure it with `dotnet_sort_system_directives_first = true`, as mentioned above 🙂

Sure. We've been using the .editorconfig solution for years now 🙂

**Comment by Eli-Black-Work** [comment]
Ya, .editorconfig is pretty awesome 🙂
