### ISSUE TITLE
Broken download link on marketplace

### ISSUE THREAD

**Issue by ExQDev** [codecadwallader/codemaid#469]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: latest
- Code language: any

### Description
Can`t post any code, because I even can`t download it. The cycle link on "Download" on marketplace - it just reloads page. Not download link. It  does not work.

### Steps to recreate
1. Goto Marketplace page of CodeMaid
2. Click "Download"
3. ...WTF?

### Current behavior
See description.

### Expected behavior
I want download it!

**Comment by codecadwallader** [comment]
I'm unable to reproduce the issue, it downloads as expected for me using Google Chrome.  What browser are you using?  Have you tried another?

**Comment by ExQDev** [comment]
Oh, I'm using Mozilla Firefox.. When I copy link from button, I'm getting the URL of current page in marketplace.

**Comment by codecadwallader** [comment]
Ok, I see that as well.  Looks like Microsoft is choosing to put the link behind some JavaScript instead.  I don't actually have any control of that page, it's the same for all extensions in the marketplace.  If you'd prefer to download the extension from here we put them all within GitHub releases as well.

**Comment by ExQDev** [comment]
But other extensions well working, I could download any, excluding CodeMaid. Thanks, I have downloaded it with Chrome. Thank you again very much.

**Comment by codecadwallader** [comment]
No problem, glad you've got it now.
