### ISSUE TITLE
Moving a class to a separate file.

### ISSUE THREAD

**Issue by Jammer77** [codecadwallader/codemaid#472]
There is a lack of a feature in moving a class to a separate file.

**Comment by codecadwallader** [comment]
Similar to #471 this is outside our traditional scope but present in other tools like ReSharper.  I'm not opposed to providing the capability, but there isn't very much existing code present to support it.

**Comment by Jammer77** [comment]
![image](https://user-images.githubusercontent.com/26893798/29626267-d990ec6a-8836-11e7-9ee5-00fda25d9d6d.png)

It's a  first draft of  

Is it Ok?

**Comment by codecadwallader** [comment]
To be honest, it looks heavily borrowed from ReSharper's interface.  All 3 of these issues (#471, #472 and #473) are existing capabilities inside ReSharper.  While there is certainly overlap between our tool and theirs, I'm concerned that this is outright copying capabilities from their tool into ours and I'm not comfortable with that.

**Comment by willemduncan** [comment]
Both "Generate interface from class" and "Move class to own file" are already part of the default VS2017 refactors.
