### ISSUE TITLE
Radial progress indicator "load ...  " in Spade Pad

### ISSUE THREAD

**Issue by Jammer77** [codecadwallader/codemaid#475]
Radial progress indicator looks better.

**Comment by Jammer77** [comment]
![image](https://user-images.githubusercontent.com/26893798/29627736-b41f5e8a-883b-11e7-8c64-5af856b0ff8e.png)

**Comment by codecadwallader** [comment]
Thank you for the suggestion.  Where does that image come from and what is its license?

**Comment by Jammer77** [comment]
It' my control, itabsolutly free, and I want insert it to Spade Pad. Can i?

**Comment by Jammer77** [comment]
![default](https://user-images.githubusercontent.com/26893798/29749404-3b660174-8b33-11e7-9eae-d2beff2078aa.png)

**Comment by codecadwallader** [comment]
I'm not sure I understand your comment.  Is this image publicly available somewhere with a clear license associated with it?  Would this be an animated image or static?

**Comment by Jammer77** [comment]
I'v done that. But i can't push or make PR :(
![default](https://user-images.githubusercontent.com/26893798/29759694-818139ce-8bc6-11e7-91f9-ef4653b4d6a7.png)

**Comment by Jammer77** [comment]
![default](https://user-images.githubusercontent.com/26893798/29759755-eed262e6-8bc6-11e7-908f-2226853be1d1.png)

**Comment by Jammer77** [comment]
I pushed my changes, can you see it? Or i have to do something else?

**Comment by Jammer77** [comment]
![image](https://user-images.githubusercontent.com/26893798/29763042-2190066c-8bda-11e7-861d-e1b7b648fbfd.png)

**Comment by Jammer77** [comment]
I made PR, but i don't know how to delete my first test commit from this PR.

**Comment by codecadwallader** [comment]
I can see your pull request, and lets focus comments over there.

**Comment by codecadwallader** [comment]
This is implemented and merged by #477 - thank you so much! :)
