### ISSUE TITLE
Error on trying to open configuration

### ISSUE THREAD

**Issue by kgroener** [codecadwallader/codemaid#48]
Visual studio 2013 (update 4) throws an error when trying to go to the configuration screen
(Codemaid version 0.7.4)

"The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))"

Screenshot:
![error](https://cloud.githubusercontent.com/assets/3479641/5083847/5350f050-6efd-11e4-9a34-76d83a9b4a50.PNG)

**Comment by OmerRaviv** [comment]
@codecadwallader @kgroener I'm trying to fix a similar issue in my own VS extension, could you please let me know whether simply upgrading System.Windows.Interactivity to .NET 4.5 fixed the issue?

**Comment by OmerRaviv** [comment]
@codecadwallader I'm trying to fix a conflict between [OzCode](http://www.oz-code.com) and CodeMaid which appears to be the exact same problem described here. OzCode currently depends on System.Windows.Interactivity 3.5, and so installing OzCode and the latest version of CodeMaid (0.7.6) from the gallery causes an exception and Visual Studio later crashes:

```

[XamlParseException: Could not load file or assembly 'System.Windows.Interactivity, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))]
    System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri):242
    System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri):20
    System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream):231
    System.Windows.Application.LoadComponent(Object component, Uri resourceLocator):336
    DebuggerShared.UI.StatusBarIndicator.InitializeComponent():28
    DebuggerShared.UI.StatusBarIconSpawner.InjectIndicator(DockPanel statusbar):0
    DebuggerShared.UI.StatusBarIconSpawner.Start():20
    DebuggerShared.Services.StartableServicesHandler.Execute(IStartable startableTask):0

[ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))]
    System.AppDomain.nApplyPolicy(AssemblyName an):-1
    System.AppDomain.ApplyPolicy(String assemblyName):34
    Microsoft.VisualStudio.Platform.VsAppDomainManager.MatchAssemblyName(AssemblyName reference, AssemblyName definition):3
    Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(String name):94
    Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(Object sender, ResolveEventArgs args):0
    System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName):43

```

I've tried updating our System.Windows.Interactivity to 4.5 like you have - that solved the problem.
But, I then went back and tested an older version of CodeMaid (0.7.4.2beta) that still used 4.0 against my new OzCode that uses 4.5, and got the same crash.

AFAICT this means that until we find a better solution, any two extension that reference different versions of System.Windows.Interactivity will cause conflicts. That means that even if OzCode and CodeMaid standardize on using 4.5, both extensions are still at risk of crashing when another 3rd party extension is installed that still references System.Windows.Interactivity 4.0 or 3.5.

Do you have any idea how we could reliably solve this?

**Comment by codecadwallader** [comment]
That sounds logical, and I agree with your assessment.  Since Visual Studio loads extensions within its own process, I don't know of a way to isolate extensions so they each use their own third party dependencies.

A couple related links:
1. http://stackoverflow.com/questions/3158928/referencing-2-differents-versions-of-log4net-in-the-same-solution
2. https://msdn.microsoft.com/en-us/library/dd153782%28v=vs.110%29.aspx#avoid_loading_multiple_versions

The first indicates explicitly referencing up/down to a common denominator.  We can't ask all 3rd party extensions to upgrade, nor if we stay on an older version (e.g. 3.5) we would still have the same problem with other extensions that have upgraded to 4.0 or 4.5

The second basically recommends against loading multiple version in the same AppDomain.  It sounds like it works, but is prone to issues as you've encountered above.

Have you looked around Microsoft Connect or opened an issue there to see if the MS team has any thoughts?

**Comment by OmerRaviv** [comment]
I've logged an issue with Connect through the Visual Studio Industry Partners program. That should help get this issue prioritized, but unfortunately also means that the Connect ticket is not public. I'll update here as soon as I hear from them.

The worrying thing is that our automatic error reporting is telling me that this issue may be affecting quite a lot of users and may be related to quite a few other 3rd party extensions.

I've considered trying to somehow tweak the bytecode of the version of System.Windows.Interactivity.dll we deploy, to remove the strong naming and change its name to something like "OzCode.System.Windows.Interactivity", thus preventing any potential conflict. That solution however is fairly involved and I haven't been able to get it to work just yet.

**Comment by codecadwallader** [comment]
Sounds good, thanks for providing the update here.
