### ISSUE TITLE
The shortcut key (Ctrl+ M + SPACE) is not working at all

### ISSUE THREAD

**Issue by davidsmithgf** [codecadwallader/codemaid#481]
### Environment
- Visual Studio version: visual studio 2017 15.3.4
- CodeMaid version: 10.4
- Code language: All language
- OS: Windows 7 x64 SP1

### Description
The shortcut key (Ctrl+ M + SPACE) is not working at all.
Since Ctrl+ SPACE is the OS default input shortcut and the input appear but no cleanup action happend.

### Steps to recreate
1. Open a source file in VS with codemaid;
2. USE Ctrl+ M + SPACE;

### Current behavior
The shortcut key (Ctrl+ M + SPACE) is not working at all.
Since Ctrl+ SPACE is the OS default input shortcut and the input appear but no cleanup action happend.

### Expected behavior
Is anywhere could change shortcut key or change the default cleanup shortup key?

**Comment by codecadwallader** [comment]
It's possible another extension, setting, etc. has replaced that keyboard shortcut.  You can easily reset/change any keyboard shortcuts by going to Tools->Options->Environment->Keyboard.  Search for CodeMaid.CleanupActiveDocument and you can reset the binding in the bottom of that dialog.

Hope it helps!
