### ISSUE TITLE
Icon to Panel is non existent

### ISSUE THREAD

**Issue by bcdiaconu** [codecadwallader/codemaid#482]
### Environment
- Visual Studio version: [example 2015 Pro]
- Visual Studio version: [example 2017 Community]
- CodeMaid version: [example 10.4]
- Code language: [example C#]

### Description
Icon to Panel is non existent

### Steps to recreate
1. Add CodeMaid panel to left docked with other panels
2. Minimize width of the panel until labels change to icons

### Current behavior
There is no icon describing that the tab corresponds to CodeMaid

### Expected behavior
There should be a icon describing that the tab corresponds to CodeMaid

![__codemaidiconmissing](https://user-images.githubusercontent.com/23461852/30510813-15600cd0-9ad4-11e7-9d8f-5b7328c39b9c.png)

Just to make the image more easy to understand, the second onward icons correspond to "Solution Explorer", "File Structure", "Class View", "Team Explorer" and the last one "Toolbox"

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I thought that icons had gone away entirely (they used to be shown side-by-side along with the text).
