### ISSUE TITLE
Feature Request: End Regions in Spade

### ISSUE THREAD

**Issue by dmhitchner** [codecadwallader/codemaid#483]
### Environment
- Visual Studio version: Enterprise 2017
- CodeMaid version: 10.4
- Code language: VB

### Description
First of all I am new to using CodeMaid and so far I find it very useful.  Would it be possible to put an End Region marker in Spade to make it easier to drag routines into the region?

### Steps to recreate
N/A

### Current behavior
When moving routines in Spade the routines will drop outside the region boundaries.

### Expected behavior
Have the routines drop inside the routine boundaries.  Perhaps this could be an optional setting.

**Comment by codecadwallader** [comment]
Thanks for the suggestion, and I'm glad to hear you're finding it useful so far.  A few ideas that may help:

1.  If you drag and drop onto the middle of the region's name - you can drop into the start of a region.
2.  If you drag and drop onto the top of the first member inside the region - you can drop into the start of a region.
3.  If you drag and drop onto the bottom of the last member inside the region - you can drop into the end of a region.

I hope those help.

**Comment by dmhitchner** [comment]
Thanks for the quick response.  The tips help.

**Comment by codecadwallader** [comment]
👍
