### ISSUE TITLE
Not all regions removed

### ISSUE THREAD

**Issue by Stoobs** [codecadwallader/codemaid#485]
### Environment
- Visual Studio version: Visual Studio 2017 Enterprise (15.3.3)
- CodeMaid version: 10.4
- Code language: C#

### Description
The "Remove All Regions" and Code cleanup (if region removing is enabled in settings), will not remove regions if they have a space immediately after the #, eg:

```c#
using System;
using System.Web.UI;

namespace SandBox
{
    public partial class About : Page
    {
        # region BrokenRegion
        //This will stop any regions below from being removed.
        #endregion

        #region PageEvents
        //This region won't be removed.
        protected void Page_Load(object sender, EventArgs e)
        {
            //Stuff
        }

        #endregion

        #region Another uncleanable region
        //This won't get removed either.
        #endregion
    }
}
```

### Steps to recreate
See code above for a direct example - adding a space after the hash/pound symbol will block any regions in that file from being removed.

### Current behavior
Badly formatted regions look valid and function correctly in Visual Studio, but won't be removed by remove all regions or code cleanup (if enabled)

### Expected behavior
All regions in selected documents will be removed.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  In general our stance with code in an invalid state is that all bets are off since there are an infinite number of ways code can be invalid.
