### ISSUE TITLE
Cleanup inserts space inside braces { }

### ISSUE THREAD

**Issue by wildcardjoker** [codecadwallader/codemaid#488]
### Environment
- Visual Studio version: 2017 Professional
- CodeMaid version: 10.4
- Code language: C#

### Description
Code cleanup inserts spaces inside braces when initialising lists (and possibly other situations).

### Steps to recreate
1. Instantiate new list/array/collection
2. `var list = new List<string> {"A,", "B", "C"};`
3. Perform Code cleanup

### Current behavior
Line is modified to `var list = new List<string> { "A,", "B", "C" };`
Additional spaces are added after `{` and before `}`

### Expected behavior
Line should remain as-is, unless specifically requested

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  When you run CodeMaid's cleanup, we start with running the built-in Visual Studio formatting capabilities before adding on our own.  The behavior you're talking about is part of the native formatting and you'll see the same behavior if you invoke it directly via Edit->Advanced->Format Document.

You may be able to configure the behavior through Visual Studio's configuration at Tools->Options->Text Editor->C#->Code Style->Formatting->Spacing.

Hope it helps.

**Comment by wildcardjoker** [comment]
Thanks, you were right!

I couldn't find a specific option for spaces in/around braces, however I disabled all of the formatting options and all is well again.

Thanks for your assistance, this was driving me crazy!

**Comment by codecadwallader** [comment]
Cool, glad to hear it and that sanity is returning :)
