### ISSUE TITLE
plugin load error

### ISSUE THREAD

**Issue by scccboom** [codecadwallader/codemaid#489]
### Environment
- Visual Studio version: 2013 update 5
- CodeMaid version: 10.4.53
- Code language: C#

### Description
Open vs show error dialog and logfile "C:\Users\XXX\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml" write
CreateInstance failed for package [CodeMaidPackage].

Install v10.3.29 not this error.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  What version of the .NET framework do you have installed?  See #437 in case it may be related, although this was an issue with v10.3 which you said was working for you.

**Comment by scccboom** [comment]
@codecadwallader v10.4 is working, but I had to update windows 8.1 to upgrade framework to 4.7.Because NDP462-KB3151802 cannot be installed.

**Comment by codecadwallader** [comment]
Ok, glad to hear you got it working and thanks for providing your solution for anyone else who may run into it!
