### ISSUE TITLE
Decorator and refactoring TS file

### ISSUE THREAD

**Issue by zygimantas** [codecadwallader/codemaid#498]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: 10.4
- Code language: TS

### Description
CodeMaid adds a whitespace in before decorator while refactoring. TSLint fails after refactoring.

### Steps to recreate
1. Create TS file with:
```ts
public constructor(@Optional() @SkipSelf() parentModule: CoreModule) { ... }
```

2. run refactor

### Current behavior
```ts
public constructor([SPACE]@Optional() @SkipSelf() parentModule: CoreModule) { ... }
```

### Expected behavior
```ts
public constructor(@Optional() @SkipSelf() parentModule: CoreModule) { ... }
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  In-line whitespace is usually controlled by Visual Studio.  As part of CodeMaid's cleanup, we invoke Visual Studio's "Format Document" command.  If you invoke that command directly (Edit->Advanced->Format Document) without CodeMaid do you still the same behavior?  Assuming that is the case, you may want to look at Visual Studio's options to see if there's a way you can configure it for your preferences.  Tools->Options->Text Editor->(Language) would be the most likely place to look.  Hope it helps!

**Comment by zygimantas** [comment]
You are right, that's Visual Studio problem.

**Comment by codecadwallader** [comment]
Cool, thanks for confirming and hope you can find a setting that helps.

**Comment by zygimantas** [comment]
No, such setting does not exist. For other who may visit this issue later, my workaround was to put parameters on separate lines, likes this:

```ts
    public constructor(
        @Optional() config: TelemetryOptions,
        public router: Router) {
    }
```
