### ISSUE TITLE
No features for Typescript files in (.NET angular2) web application

### ISSUE THREAD

**Issue by john-fenton** [codecadwallader/codemaid#515]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: example 10.4
- Code language: Typescript

### Description
No code maid for Typescript files

### Current behavior
In my angular2 & .NET web application I have all Codemaid features for my `C#` and `.cshtml` files however zero features for the typescript files?

### Expected behavior
Some sort of typescript support?

### Example TS file
*user.model.ts*
``` 
import { UserDetails } from './user-detail.model';
import { Channel } from './channel.model';

export class User {
	public accesstoken: string;
	public details: UserDetails;
	public subscriptions: Channel[];
	private loaded: boolean;

	constructor(input: any) {
           this.accesstoken = input.token;
           this.details = new UserDetails(input);
	}
}
```

**Comment by codecadwallader** [comment]
TypeScript has some cleaning support but not digging support based on underlying APIs.  See #509 for more information.
