### ISSUE TITLE
Feature suggestion: Identifying Law of Demeter violations?

### ISSUE THREAD

**Issue by BKSpurgeon** [codecadwallader/codemaid#516]
Let's say I have a class: Bicycle. I want to see if there are any Demeter violations associated with this class.

Is it possible for such a feature to be introduced in codemaid, if it is not already introduced so far?

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  No that type of feature does not exist, nor do we currently do those level of analyses of the code.  While anything is possible, it's probably not likely to be added to this tool.
