### ISSUE TITLE
Auto generate private properties

### ISSUE THREAD

**Issue by larini** [codecadwallader/codemaid#518]
Request:

As a suggestion, there should be an option to generate the private readonly properties from the constructor method. Example:

`public MyClass(int a, bool b, string c) { }`

Could generate following:

```
private readonly int a;
private readonly bool b;
private readonly string c;
public MyClass(int a, bool b, string c) {
    this.a = a;
    this.b = b;
    this.c = c;
}

```

**Comment by codecadwallader** [comment]
Thanks for the suggestion.

**Comment by BKSpurgeon** [comment]
This is already available in Visual Studio: from within your constructor right click on the parameter and it will create and initialize the fields.

**Comment by willemduncan** [comment]
Seconded, this is a built in feature (as of VS2017), and it is "auto generating code" rather than cleanup/reorganizing, which would be out of scope for CodeMaid, in my opinion.

**Comment by codecadwallader** [comment]
Yep, I can confirm it is built into VS2017 as well.  Will close.
