### ISSUE TITLE
attributes on same line as fields

### ISSUE THREAD

**Issue by gogirogi** [codecadwallader/codemaid#536]
### Environment
- Visual Studio version: 2015 Community
- CodeMaid version: 10.4
- Code language: C#

### Description
Help please!
How can I set up settings so when I write attribute in front of field on the same line ( [SerializeField] string someItem; ) that it stays on same line after cleaning?

**Comment by codecadwallader** [comment]
Thanks for asking the question.  I'm using default settings and not seeing the attribute get moved during a cleaning operation.  For example with the following line:

`        [Description("Stay")] private int NumberField;`

and invoking Cleanup, the code is unchanged.

Something you can try:

1.  If you invoke Edit->Advanced->Format Document does the attribute still get moved?
2.  If you move that field to an isolated class by itself does the attribute still get moved?

**Comment by gogirogi** [comment]
Thank you
1. Yes! Is that mean that something else is on, beside CodeMaid?
2. There is no option to move field in a refactoring, only to encapsulate it.

**Comment by gogirogi** [comment]
Thank you
1. Yes! 
2. Yes!
Is that mean that something else is on, beside CodeMaid?

**Comment by codecadwallader** [comment]
Part of CodeMaid's cleanup is that it invokes Visual Studio's cleanup (which is Edit->Advanced->Format Document) so yes it is "outside" of CodeMaid, but CodeMaid does deliberately trigger it.

Two things you could do next:

1.  I'm not seeing that behavior by default, so perhaps you have customized a setting within Visual Studio?  Their settings would be under Tools->Options->Text Editor->C#
2.  You can tell CodeMaid not to invoke Visual Studio's cleanup, but you will miss out on other formatting that Visual Studio natively handles (e.g. spaces between method arguments).

Hope that helps!

**Comment by gogirogi** [comment]
Thank you for clearing this up for me!
