### ISSUE TITLE
[Q] Is there any way to keep Enter between using statements? 

### ISSUE THREAD

**Issue by dehghani-mehdi** [codecadwallader/codemaid#540]
Hello,

I like to keep enters between using statements, fox ex.

```cs
using System;
I WANT TO KEEP THIS!
using System.Collections.Generic;
using System.Linq;
using System.Text;
```

Thanks.

**Comment by codecadwallader** [comment]
Yes, part of CodeMaid's cleanup is invoking the native "Remove and Sort Usings".  When you invoke that command and the using statements are not in order, they will be shuffled into order and it may lose whitespace.  If you don't want the using statements to be adjusted, you can disable CodeMaid's invocation via CodeMaid->Options->Cleaning->Visual Studio->Run remove and sort using statements.

Hope it helps!

**Comment by dehghani-mehdi** [comment]
Thanks @codecadwallader, for the answer and CodeMaid.
I don't want to disable `Remove and Sort Usings`, I like this feature a lot!
I want to Remove and Sort Usings, but CodeMaid keep my enters un-touch. of course it would be great to delete more than 1 enters (if any), also use can config this feature too.

**Comment by dehghani-mehdi** [comment]
I'm sorry, seems like CodeMaid keeps empty line, even remove more than 1 empty lines. I'm sure I saw CodeMaid removed the empty lines, then I decided to open this issue. amazing!

Anyway thanks @codecadwallader for your time and the great CodeMaid.

**Comment by codecadwallader** [comment]
You're welcome, I'm glad you're enjoying it. :)

**Comment by dehghani-mehdi** [comment]
Hi again,

Please check this:
![codemaid](https://user-images.githubusercontent.com/9152330/40347872-1399f554-5db7-11e8-8bec-69c738361f3f.gif)

**Comment by codecadwallader** [comment]
If you invoke the native command (Right click in editor window, "Remove and sort usings") do you see the same behavior?  CodeMaid is mostly just invoking the native command for this piece of cleanup.

**Comment by dehghani-mehdi** [comment]
> If you invoke the native command (Right click in editor window, "Remove and sort usings") do you see the same behavior?
Yes
>  CodeMaid is mostly just invoking the native command for this piece of cleanup.
So, you mean it doesn't related to CodeMaid and can not be fixed?

**Comment by codecadwallader** [comment]
That is correct.  Many years ago (VS2005/VS2008) we had our own implementation but Microsoft built their own (I think around VS2010) so we eventually switched over to just invoking theirs and took away our version.

**Comment by dehghani-mehdi** [comment]
I'm sure there is no chance that VS team fix this (let's say) bug. so the only hope is CodeMaid :p

Of course I know this is not huge bug, so is there any chance to fix this?

**Comment by codecadwallader** [comment]
I think the rules around it would be confusing.  Since the sort command is intended to move lines around it would not be clear when the space could be removed and when it would have to remain.. as well as when it applies to the line above and the line below.  Long story short, no I don't think it's something we'd prioritize.

**Comment by dehghani-mehdi** [comment]
Okay man, thanks.
