### ISSUE TITLE
remove and sort namespaces in .XAML files

### ISSUE THREAD

**Issue by Apflkuacha** [codecadwallader/codemaid#551]
### Environment
- Visual Studio version: 2017 Community
- CodeMaid version: 10.4
- Code language: C#

### Description
The function "Remove and sort namespaces" of VisualStudio is not executed at .XAML files when using cleanup active document. This should be done or at least a setting for this would be great.

**Comment by codecadwallader** [comment]
Thanks for the suggestion!

**Comment by FletcherJohnsonZ** [comment]
I am having the same problem.  Any idea if this is or will be addressed?

**Comment by codecadwallader** [comment]
It looks like XAML files have their own IDE command that would need to be invoked.  I believe it is `EditorContextMenus.CodeWindow.RemoveAndSort`.  Some regression testing and language distinction would need added.  Supporting re-insertion of specific namespaces would need some additional consideration. 
 https://github.com/codecadwallader/codemaid/blob/master/CodeMaid/Logic/Cleaning/UsingStatementCleanupLogic.cs is probably the main focus point of where that logic would go.

**Comment by Apflkuacha** [comment]
I was motivated to take a look into that and made my first Pull request :) The UsingStatementCleanupLogic was never executed on XAML files, that's why this filetypes weren't considered. I hope this changes make it into the next release.
