### ISSUE TITLE
Cannot get class info from the .net core project via EnvDTE.Project.CodeModel

### ISSUE THREAD

**Issue by junimnjw** [codecadwallader/codemaid#553]
### Environment
- Visual Studio version: Visual Studio 2017 Professional 
- CodeMaid version: [example 10.2]
- Code language: C#

### Description
Replace this text with a short description and code sample.
I am developing visual studio extension to get class and method information from the destination project. when I selected a net core based project, I cannot get any class info in the project via CodeModel. I think EnvDTE.Project.CodeMode seems to be not fitted to .NET Core Project. 

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong.
I cannot get any class information from the net core project. 

### Expected behavior
Explain what it should be doing after it's fixed.
it should be possible to get some information from the net core project such as Types, Namespaces, Structures, Interfaces, Classes, Enumerations, Variables, Delegates, Properties at design time.

**Comment by codecadwallader** [comment]
The EnvDTE libraries were created by Microsoft, not me (another extension author).  You will want to report the issue to them for help.
