### ISSUE TITLE
VS2015 isn't recognizing explicit interface implementations and is adding explicit access modifiers

### ISSUE THREAD

**Issue by michaelaird** [codecadwallader/codemaid#56]
this

```
Guid IEventBase.Id { get { return _id; } }
```

becomes

```
private Guid IEventBase.Id { get { return _id; } }
```

which is not correct.

**Comment by HeavyStorm** [comment]
Having the same problem here. Wish I'd been fixed.

**Comment by immeraufdemhund** [comment]
I just hit this problem too. Talk about irritating when trying to write a test :)  I ended up having to turn off Auto Clean (my favorite feature). I'm using VS2015 RC, and 0.7.6 beta

**Comment by codecadwallader** [comment]
My apologies, it is an ugly one that I wish there was a quick fix to address. :(

An alternate workaround you could use is to disable inserting explicit access modifiers.  I have been considering making that the default for VS2015 until we can either find a quick solution or the very large rewrite in Roslyn occurs.

**Comment by codecadwallader** [comment]
I've come up with a workaround to address this in the short term for VS2015, without waiting for the Roslyn rewrite.  This fix will be present in the next pre-releases of CodeMaid and the next major release v0.8.0.

**Comment by codecadwallader** [comment]
Note: I did find an issue within the Roslyn repository reporting this but no action was taken.  We have a workaround now.

https://github.com/dotnet/roslyn/issues/2437
