### ISSUE TITLE
Utilize new AsyncPackage base class

### ISSUE THREAD

**Issue by codecadwallader** [codecadwallader/codemaid#563]
Per https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/ there's a new preferred base class for extensions (packages).  This issue is to investigate making the suite of changes needed for it.  Since this was introduced in VS2015, this may require breaking backwards compatibility to VS2012/VS2013.

**Comment by willemduncan** [comment]
That be nice for Roslyn development as well, since it has an `async` entry point as well (and breaks backwards compat anyway).

**Comment by codecadwallader** [comment]
@madskristensen mentioned this on Twitter recently, so giving this issue a bump up as a reminder.  It does indeed mean breaking backwards compatibility, but with VS2019 being announced now too it seems like it is time.  It would also be good to revisit our dependencies and see if we can cut them out (e.g. LanguageService and System.Windows.Interactivity) as we drop older VS version support.

**Comment by codecadwallader** [comment]
Additional link: https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2017

**Comment by codecadwallader** [comment]
@xperiandri cool, thanks for the context. :) I was hoping less but we'll see!

**Comment by codecadwallader** [comment]
Implemented in #625
