### ISSUE TITLE
Format JS object

### ISSUE THREAD

**Issue by Wizard2007** [codecadwallader/codemaid#566]
### Environment
- Visual Studio version: 2015 Enterprise 2017 v. 15.7
- CodeMaid version: 10.5
- Code language: JS

### Description
can I sort in js object methods and fields in case when i have source code like in " Expected behavior" fro source code like in "Current behavior"

### Steps to recreate
Reorganize current document

### Current behavior
```
var contentItemSaleStatisticsVisitor = {
    func3: function (param1, param2) {
        //...
    },

    func1: function (param1, param2) {
        //...
    },
    
    func2: function (param1, param2) {
        //...
    },    
    
    field3: value3,
    field1: value1,
    field2: value2,
};
```
### Expected behavior
```
var contentItemSaleStatisticsVisitor = {
    func1: function (param1, param2) {
        //...
    },

    func2: function (param1, param2) {
        //...
    },
    
    func3: function (param1, param2) {
        //...
    },    
    
    field1: value1,
    field2: value2,
    field3: value3,    
};
```

**Comment by codecadwallader** [comment]
Unfortunately no, reorganization is currently only supported for C# and VB, because those are the only two languages that expose rich code models through the Visual Studio APIs.
