### ISSUE TITLE
Single line property don't reorganized in "single line" while I reorganize current document 

### ISSUE THREAD

**Issue by Wizard2007** [codecadwallader/codemaid#567]
### Environment
- Visual Studio version: 2015 Enterprise 2017 v. 15.7
- CodeMaid version: 10.5
- Code language: C#

### Description
Single line property don't reorganized in "single line"
while I reorganize current document 

### Steps to recreate
Reorganize current document

### Current behavior
```
private int Goo {
get;set;
}
```
### Expected behavior
`private int Goo { get; set; }`

**Comment by codecadwallader** [comment]
You can use the join lines command to merge those lines together, but it's not currently baked into reorganization to auto-merge those lines.  Does that answer your question (not sure if it's a question/request/bug report)?
