### ISSUE TITLE
Feature Request:  Reorganize - Primarily order 

### ISSUE THREAD

**Issue by TonyValenti** [codecadwallader/codemaid#574]
### Environment
- Visual Studio version: [example 2015 Community]
- CodeMaid version: [example 10.2]
- Code language: [example C#]

### Description
Replace this text with a short description and code sample.

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong.

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by codecadwallader** [comment]
See #575
