### ISSUE TITLE
Codemaid is not available in the marketplace nor can it be installed manually

### ISSUE THREAD

**Issue by elieobeid7** [codecadwallader/codemaid#577]
Codemaid is not available in the marketplace

![capture](https://user-images.githubusercontent.com/660142/43369522-b6aa6b38-9378-11e8-9305-fd221e0626ae.PNG)

And if I try to download the extension `.vsix` and install it manually I get

![capturaae](https://user-images.githubusercontent.com/660142/43369535-eec92e5a-9378-11e8-9754-180939f4b11f.PNG)

I'm on windows 10, I have the latest version of vscode

**Comment by eluchsinger** [comment]
Codemaid is not available for Visual Studio Code. It's for Visual Studio.

**Comment by elieobeid7** [comment]
ahh okay sorry for the confusion
