### ISSUE TITLE
Cleanup All Code Status Box

### ISSUE THREAD

**Issue by Woodroff2** [codecadwallader/codemaid#585]
### Environment
- Visual Studio version: 2017 Community on Windows 10
- CodeMaid version: 10.5
- Code language: VB

Just a trivial minor thing really, but when running the cleanup all code function, the label underneath the progress bar isn't sized correctly, and misses the lower half of the text off (See image)

![capture](https://user-images.githubusercontent.com/42910169/44955893-e7baf080-aeb2-11e8-8343-7cd45454b27f.JPG)

Thanks,
James.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I'm not able to reproduce it, but I suspect its related to either font size or DPI settings.  Have you customized the font settings for CodeMaid (CodeMaid->Options) and do you know what DPI your machine is set at?

![image](https://user-images.githubusercontent.com/3823772/45254605-af138f00-b36a-11e8-9372-ea0b5d78fd54.png)

**Comment by Woodroff2** [comment]
Hi,

Sorted! I’m using VS on a Samsung laptop with a screen resolution of 1366x768, DPI/Scaling is set at 100%. I didn’t realise you could change the fonts and don’t recall doing so, however looking the settings it was set to Segue UI – I changed it to Sans Serif and it’s displaying perfectly now.

 

Thanks! :o)
