### ISSUE TITLE
Wrongly shown warning - Remove the field and declare it as a local variable in the relevant methods

### ISSUE THREAD

**Issue by Kadakol** [codecadwallader/codemaid#592]
### Environment
- Visual Studio version: Professional 2017, Version 15.7.5
- CodeMaid version: 10.5.119
- Code language: C#

### Description
First, a code sample.

    public class Sample
    {
        private int _var1;
        private int _var2;

        public void M1()
        {
            _var1 += 0;
        }

        public void M2()
        {
            _var2 = _var2 + 0;
        }
    }

As can be seen from the example, the operations performed on _var1 and _var2 are the same. The only difference is the use of the operator +=.  However, a warning is shown on _var1 as follows:

    Remove the field '_var1' and declare it as a local variable in the relevant methods.

But no such warning is shown on _var2.

Attaching an image of the same below:

![image](https://user-images.githubusercontent.com/6085078/47350354-55291780-d6d3-11e8-85c9-2eaa0e50e6a2.png)

### Current behavior
The warning message is shown only on _var1 and not on _var2. 

### Expected behavior
No warning should be shown.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, however that is a native Visual Studio message (not a part of CodeMaid) so you will want to report it directly to Microsoft for more information.

**Comment by Kadakol** [comment]
Sorry for the late reply. 

I didn't update Visual Studio or CodeMaid, but something's happened and I can't see this message any more. I guess there's no point keeping this issue open then.

Sorry for the trouble.

**Comment by codecadwallader** [comment]
No problem, glad to hear it's no longer an issue for you. 👍
