### ISSUE TITLE
Make naming of #endregion optional

### ISSUE THREAD

**Issue by cbeamond** [codecadwallader/codemaid#595]
### Description
When codemaid cleans a file, it names the #endregion with the same name as #region. When having a lot of regions in a large file, the naming of #endregion ends up filling the file with lots of visual clutter.

Here is a difference between #endregion with names vs without.

It would be awesome to have the option to enable/disable this behaviour inside codemaid.

![image](https://user-images.githubusercontent.com/44617656/47738211-72b92c80-dc51-11e8-921c-f47c8caf3803.png)

![image](https://user-images.githubusercontent.com/44617656/47738261-8c5a7400-dc51-11e8-96b8-0d04b94d46b4.png)

**Comment by codecadwallader** [comment]
Sure, there already is an option to turn that off. :)  CodeMaid->Options->Cleaning->Update->Update #endregion tags with region names.

![image](https://user-images.githubusercontent.com/3823772/47952932-52011780-df6e-11e8-9cde-1bd014750cb3.png)

**Comment by robert-skarzycki** [comment]
@cbeamond, if the answer satisfy you - maybe you can close the issue?

**Comment by cbeamond** [comment]
Closed as answer was provided by @codecadwallader
