### ISSUE TITLE
Is it possible to disable a feature of CodeMaid across all projects?

### ISSUE THREAD

**Issue by GitHubTuna** [codecadwallader/codemaid#596]
### Environment
- Visual Studio version: [example 2017 Professional]
- CodeMaid version: [example 10.5]
- Code language: [example C#]

### Description
Is it possible to do something like what is below that will affect all projects and would not require me to drop in a "GlobalSuppression.CS" into all of my projects with the code below to suppress this behavior?

### Steps to recreate
Within: GlobalSuppression.CS

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "Desired to be removed Everywhere")]

### Current behavior
We don't want to be prompted to update specific types to "Var" in code.

Examples like the one below are reasons for not wanting this behavior all the time:
TYPE name = Function(Params);

### Expected behavior
No green squiggly lines under text that is prompting developers to update specific types to "Var" on the left side of equations.

**Comment by codecadwallader** [comment]
The recommendations to switch to `var` are coming directly from Visual Studio and not CodeMaid.  So you may want to check in the Microsoft docs/forums if there's a way to get that global behavior you're seeking.  One trick I've used in the past is to have a common file in one location, and then link it into multiple projects.  You still have to do it in every project, but then it's at least only in one location for updates.  Hope it helps!

**Comment by GitHubTuna** [comment]
Thank you for the clarification and help with this issue.
