### ISSUE TITLE
It would be great to be able to select which Types we want to re-organize

### ISSUE THREAD

**Issue by portuswebs** [codecadwallader/codemaid#598]
A checkbox in the settings menu on the left of each type should be enough

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  How would that work with unselected types?

**Comment by portuswebs** [comment]
It just wouldn't order the selected types. For example:
I have a file with different variables, methods, and classes, but for some reason, I want only to be sorted automatically the variables and methods, not the classes. So when I save my file and Codemaid organises automatically it, it just do it for the selected types (in this case, variables and methods, not classes) so I can sort manually the classes.

So unselected types won't be automatically sorted, and you can sort them manually.

**Comment by codecadwallader** [comment]
Thanks for the example.  We also sort across types (e.g. putting variables and methods above classes), so I'm trying to picture if there were classes scattered across the file (some at the top, some in the middle, some at the end) and we aren't cleaning them up, where those variables/methods end up?
