### ISSUE TITLE
Adds comment marks after self-closing xml documentation elements.

### ISSUE THREAD

**Issue by Mythilt** [codecadwallader/codemaid#599]
### Environment
- Visual Studio version: 2017 - 15.8.9
- CodeMaid version: 10.5
- Code language: visual basic

### Description
  Comment marks are added to the line after any self-closing xml documentation tags during cleanup, causing potential documentation errors.
  Apparently a similar issue was fixed with regards to C# /// xml-documentation comments in version 0.9.1 or so (issue #215).
  This may be a side-effect of setting the 'Always split all xml tags onto multiple lines' formatting setting.  Considering that self-closing tags have no &lt;/ tagname&gt; to move to the new line, that may be the cause of this problem.

Example 1:
Before cleanup.
''' &lt;summary&gt;
'''   Class SomeService
''' &lt;/summary&gt;
''' &lt;seealso cref="System.ServiceProcess.ServiceBase" /&gt;

After cleanup
''' &lt;summary&gt;
'''   Class SomeService
''' &lt;/summary&gt;
''' &lt;seealso cref="System.ServiceProcess.ServiceBase" /&gt;
'''  &lt;&lt;&lt; Issue is here.

Example 2:
Before cleanup.
''' &lt;summary&gt;
'''   Class SomeService
''' &lt;/summary&gt;
''' &lt;seealso cref="System.ServiceProcess.ServiceBase" /&gt;
''' &lt;remarks&gt;
'''   This is an example.
''' &lt;/remarks&gt;

After cleanup
''' &lt;summary&gt;
'''   Class SomeService
''' &lt;/summary&gt;
''' &lt;seealso cref="System.ServiceProcess.ServiceBase" /&gt;
'''''' &lt;remarks&gt;      &lt;&lt;&lt; Issue is here.
'''   This is an example.
''' &lt;/remarks&gt;

### Steps to recreate
1. Create documentation xml comments with a self closing tag (e.g. &lt;customtag /&gt;
2. Run Codemaid format command.
3. Self - closing document will have ''' added to line after the tag, potentially causing a formatting issue.

### Current behavior
  By adding a new comment line after the self-closing xml tag, any following comment lines may have a formatting issue (if more than three ' characters, visual studio assumes the xml documentation comment is itself, commented out.)

### Expected behavior
  Self-closing xml tags should not add a new comment line after the tag.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  @willemduncan can you please take a look when you have a chance?

**Comment by willemduncan** [comment]
I've reproduced it here as well. Interesting that it doesn't show up in unit tests, but that probably is because we test without comment prefix. A big hole in our tests!
