### ISSUE TITLE
Solution not collapsed at VS startup

### ISSUE THREAD

**Issue by Otiel** [codecadwallader/codemaid#6]
It seems that the option to collapse solutions when they are opened do not work anymore.

When I open a solution, it is collapsed at first, but when the Solution Explorer finishes to load the solution, it takes back its expanded state as it was when I did exit VS.

I'm using VS 2013 and the option "☑Collapse solutions when they are opened" is correctly checked.

**Comment by cooldrl** [comment]
Where is the "Collapse solutions when they are opened" option? I have searched high and low for this as my solutions are collapsing on opened and I want it unchecked.

**Comment by Otiel** [comment]
@cooldrl : CodeMaid → Configuration → Collapsing:

![screenshot](https://cloud.githubusercontent.com/assets/3851902/8412581/f6e50214-1e8a-11e5-9457-69a523839265.png)

**Comment by cooldrl** [comment]
Ah that explains it, I don't have CodeMaid installed. Funny though on some projects on load solution explorer expands to as I last left it, which is what I want, whilst on my latest project on load everything is collapsed in solution explorer. Do you think CodeMaid would fix this with the appropriate option unchecked? Thanks very much for your help and so prompt reply

**Comment by cooldrl** [comment]
Sorted it. When using solution folders but not "Track Active Item In Solution Explorer" then said folders do not expand but on manually expanding stuff underneath is as last left. I am gonna try CodeMaid anyway. Thanks again for help.
