### ISSUE TITLE
Disable var to Explicit Type clean up

### ISSUE THREAD

**Issue by peterneave** [codecadwallader/codemaid#600]
### Environment
- Visual Studio version: VS 2017
- CodeMaid version: 10.2
- Code language: C#

### Description
Question: Is there a way to turn off an individual feature? I would like to disable 'var' from being converted to their explicit types.

`var someString = new string();` is converted to `string someString = new string();` but I would like to disable it.

**Comment by codecadwallader** [comment]
This is actually a feature of Visual Studio natively, and not a part of CodeMaid.  You can take a look at the settings under Tools->Options->Text Editor->C#->Code Style->General such as 'var' preferences and I think that may be what you're looking for.  Hope it helps!

Also similar to #596
