### ISSUE TITLE
Filehelper cvs columns changed after cleaning all files

### ISSUE THREAD

**Issue by HitGub40** [codecadwallader/codemaid#608]
### Environment
- Visual Studio version: 2017 Enterprise newest
- CodeMaid version: [newest]
- Code language: C#

### Description
I use filehelpers 4.5 with C# and a data.csv file, after clean all code the used RcptnRecords.cs columns are messed up  rcptNames = rcptDescr and vv.
### Steps to recreate
1. Its to complicated can i send two zip files so you can see what happens after cleaning all files?
with regards,

using FileHelpers;

namespace wfaRecipePrg
{
    [DelimitedRecord("|")]
    public class RcptnRecords
    {
        internal string rcptName = "";  // changed with
        internal string rcptIngr = "";
        internal string rcptPrep = "";
        internal string rcptDesc = "";   // this column
    }
}

**Comment by codecadwallader** [comment]
Yes, you can attach ZIP files to issues.

**Comment by HitGub40** [comment]
codecadwallander,
Sorry for the trouble, the solution is to make 
public class RcptnRecords
{
internal string rcptName = ""; // changed with
internal string rcptIngr = "";
internal string rcptPrep = "";
internal string rcptDesc = ""; // this columnit 
}
in alphabetical order before cleaning :-)
.........
        internal string aRcptName = "";
        internal string bRcptIngr = "";
        internal string cRcptPrep = "";
        internal string dRcptDesc = "";
.........

**Comment by codecadwallader** [comment]
No problem, glad you found what you needed. :)

**Comment by HitGub40** [comment]
Thanks!

Op za 19 jan. 2019 om 15:14 schreef Steve Cadwallader <
notifications@github.com>:
