### ISSUE TITLE
synchronous auto-load' feature of Visual Studio

### ISSUE THREAD

**Issue by Cataurus** [codecadwallader/codemaid#610]
### Environment
- Visual Studio version: 16.0.0 Preview 1.1
- CodeMaid version: 10.6.144
- Code language: C#

### Description
Extension 'CodeMaid' uses the 'synchronous auto-load' feature of Visual Studio. This feature will no longer be supported in a future Visual Studio 2019 update, at which point this extension will not work. Please contact the extension vendor to get an update. (UI Context: {10534154-102d-46e2-aba8-a6bfa25ba0be} Package Guid: {4c82e17d-927e-42d2-8460-b473ac7df316})

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  This is known and tracking under #563
