### ISSUE TITLE
CodeMaid doesn't support #if preprocessor directive

### ISSUE THREAD

**Issue by dehghani-mehdi** [codecadwallader/codemaid#619]
Hi,

### Environment
- Visual Studio version: 2017 Enterprise 
- CodeMaid version: 10.6.144
- Code language: of course C#!

### Description
CodeMaid removes `using` statements that used in `#if DEBUG` block codes in `Release` mode _and vice versa_

Thanks!

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I believe this is a known limitation with Visual Studio and using preprocessor directives on using statements.  CodeMaid simply invokes Visual Studio's native "Remove and Sort Usings" command, so I believe you will see the same behavior if you invoke that command directly even without using CodeMaid.  Can you please confirm?  If so you may want to see if there are any known workarounds in the Microsoft forums.

**Comment by dehghani-mehdi** [comment]
Yeah, that's true, I didn't find any related issue, so I opened an issue on developercommunity, right here: https://developercommunity.visualstudio.com/content/problem/448920/remove-and-sort-using-command-doesnt-support-if-pr.html

Thanks @codecadwallader.
