### ISSUE TITLE
How can I use macros in File Header

### ISSUE THREAD

**Issue by RafaMa78** [codecadwallader/codemaid#621]
### Environment
- Visual Studio version: 2017 Professional
- CodeMaid version: 10.6
- Code language: C#

### Description
How can I use macros in File Header

### Current behavior
I can´t find any example about using macros in File Header

### Expected behavior
I would appriciate an example, how to use macros and which macros are supportet.

**Comment by codecadwallader** [comment]
Currently the file headers only support static text, but there is a PR in progress to add support for macros - #513

**Comment by RafaMa78** [comment]
Thank you.
