### ISSUE TITLE
Possible issue placing private non-constant fields outside of the Fields region?

### ISSUE THREAD

**Issue by mkamoski** [codecadwallader/codemaid#624]
### Environment
- Visual Studio version: 2015 pro
- CodeMaid version: 10.6
- Code language: C#

### Description
Running cleanup active doc put some of the private non-static fields at the end of the file, not in any region.

### Steps to recreate
In Visual Studio 2019, for the Reorganizing/General, I had these settings...
alphabetize members of the same group = checked
keep members within regions = checked
place explicit interface members = not_checked
primary ordering, type then access = selected
access levels, private to public = selected
run reorganize at start = checked
perform reorganization when preprocessor = ask 
...and running Cleanup Active Document in an "*ascx.cs" file put some of my private non-constant fields at the end of the file outside of any region...
...so changing to this...
access levels, public to private = selected
...and running Cleanup again put the private non-constant fields into the "Fields" region as expected...
...so just FYI.

### Current behavior
It is putting the fields outside a region when they should be in the Fields region.

### Expected behavior
The private non-constant fields should be in the Fields region.

This is JUST a guess as to an issue/bug.

My good/working config is attached, so you can see all the other settings.
[CodeMaid.config.txt](https://github.com/codecadwallader/codemaid/files/2919454/CodeMaid.config.txt)

HTH.

Thanks.

-- Mark Kamoski

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Could you please also attach a minimal code file that exhibits the issue?

**Comment by mkamoski** [comment]
Grrr.... I cannot reproduce it.... tried several times on several candidate files... maybe I was dreaming.... anyway sorry for the trouble...

**Comment by codecadwallader** [comment]
Yeah, ephemeral bugs are frustrating. :(  Lets close the issue for now but of course feel free to reopen if it reoccurs especially if you have any consistency in reproducing it.
