### ISSUE TITLE
CodeMaid throws deprecation warning in VS 2019 RC on startup

### ISSUE THREAD

**Issue by szalkerous** [codecadwallader/codemaid#627]
### Environment
- Visual Studio version: 2019 Professional RC
- CodeMaid version: 10.6.144
- Code language: C# / not applicable

### Description
Visual Studio 2019 RC reports the following:

"One or more of your installed extensions will not be compatible with a future Visual Studio update"

followed by:

"CodeMaid: This extension uses deprecated APIs and will not be compatible with a future Visual Studio update."

and links to the following article for specifics: 

https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  We have already addressed the issue and it is in beta testing now (v11).  :) See #563 .  If you would like to install the beta and help us test it you can find it here: http://vsixgallery.com/extension/4c82e17d-927e-42d2-8460-b473ac7df316/

**Comment by rprouse** [comment]
@codecadwallader I've done a quick test on a medium sized codebase in RC.1 SVC1 and the beta is working fine. I mainly use CodeMaid Spade. So far, no more deprecation warnings and everything is working as expected. As I get down to day-to-day work, I'll report back if I see anything odd, but so far 👍

**Comment by codecadwallader** [comment]
@rprouse That's awesome, thanks for the help testing and feedback! :)

**Comment by yyjdelete** [comment]
@codecadwallader 
When disabled CodeMaid(11.0.174 with VS2019 preview4.2), failed to enable it again 
![image](https://user-images.githubusercontent.com/1819074/54575135-e8ba0680-4a2d-11e9-9d9d-f74f5efd2917.png)

It said that it depends on an disabled products `Visual Studio MPF 15.0`.
Maybe an issue of VS2019, not sure.

**Comment by rprouse** [comment]
I can confirm the MPF issue on re-enabling the extension. I've been running the extension fine, but to test the above issue I disabled the extension then tried to re-enable it. I cannot re-enable because of the above issue.

**Comment by codecadwallader** [comment]
Interesting, I can reproduce it too.  I have heard conflicting information about MPF being required or not so I had left it in since it's been around forever.  We have switched to VS2017/VS2019 with this upcoming v11 release so I'll go ahead and drop it out per that MS engineer's comment.  This is a huge help, thanks @yyjdelete and @rprouse !

**Comment by codecadwallader** [comment]
v11 is now live - thanks again everyone for the help testing it out and if you see any issues please report them as new issues. :)
