### ISSUE TITLE
[Q] How to prevent adding new line for empty blocks

### ISSUE THREAD

**Issue by dehghani-mehdi** [codecadwallader/codemaid#628]
Hello,

I didn't find any related option for this one, so I need help.

I like to tell CodeMaid, hey CodeMaid, please don't touch empty blocks, how I can do that?

Example:

```cs
public void F() { }
```
CodeMaid changes above to:

```cs
public void F()
{
}
```
Which is not my favorite format and I like to keep that as is.

So, please if is there any way to do that, let me know, otherwise having option for that will be great.

Thanks.

**Comment by codecadwallader** [comment]
Thanks for asking the question.  Yes you can configure that option at CodeMaid->Options->Update->"Update single line methods by placing braces on separate lines (SA1502)" 

Hope it helps!

![image](https://user-images.githubusercontent.com/3823772/54121332-154c9d80-43f2-11e9-8235-a3a31726d3f1.png)

**Comment by dehghani-mehdi** [comment]
That's why I love CodeMaid. thanks man, my bad, I'm sorry, I don't know how I did see this option.

**Comment by codecadwallader** [comment]
No problem - glad I could help!  With 160+ options it can be hard to find the right one.

**Comment by dehghani-mehdi** [comment]
@codecadwallader Is there any way to tell CodeMaid convert this:

```
public void F()
{
}
```
To this?
```
public void F() { }
```

**Comment by codecadwallader** [comment]
![image](https://user-images.githubusercontent.com/3823772/58877360-00fe0100-86c0-11e9-82a5-71f5fb24f3ac.png)

You can get part of the way there with Visual Studio's native settings (see screenshot) but I don't see matching settings for closing braces.

**Comment by KaelOrion** [comment]
I have the following code:

 public UserRepository(ILogger<UserRepository> logger, IOptionsMonitor<CacheSettings> cacheSettingsAccessor, IAppCache cache, UserDirectoryContext dbContext) :
            base(logger, cacheSettingsAccessor, cache, dbContext) { }


It is expected to remain like this but CodeMaid in its most recent version it is converting sending the brackets to a new line: 

        public UserRepository(ILogger<UserRepository> logger, IOptionsMonitor<CacheSettings> cacheSettingsAccessor, IAppCache cache, UserDirectoryContext dbContext) :
            base(logger, cacheSettingsAccessor, cache, dbContext)
        { }

The option you mentioned previously "Update single line methods by placing braces on separate lines (SA1502)" only works for single line, on my case my method uses two lines, reason why that settings don't apply. Is there any way to make CodeMaid not change this code keeping the brackets in the same line?

Many thanks
