### ISSUE TITLE
Problem with formatting lists

### ISSUE THREAD

**Issue by bartlomiejwolk** [codecadwallader/codemaid#63]
Hi, this is how CodeMaid formats lists in my code:

![xml_list](https://cloud.githubusercontent.com/assets/325348/5694552/9badd97e-9966-11e4-9e8e-668d1a031e56.png)
Tags inside list are just merged together instead of creating a structure.

And this is my CodeMaid config:
![codemaid_config](https://cloud.githubusercontent.com/assets/325348/5694555/b84aa8d2-9966-11e4-98f2-6965c94a9ddb.png)

Is this an expected behavior?

**Comment by codecadwallader** [comment]
We look for one of several different types of punctuation in order to recognize that the content is intended to be an item within a list.  Currently we don't use an XML tag as the basis for a list item.

Some list indicators that are recognized:
    -
    =
    *
    +
    a:
    1.

Does that help?

**Comment by bartlomiejwolk** [comment]
Yes it does although it would be nice if xml list tags were supported.

**Comment by willemduncan** [comment]
Is there a reason for using this syntax? I don't see Visual Studio recognizing the format (they're not standard XML doc tags).

**Comment by codecadwallader** [comment]
Agreed, added to backlog here: https://trello.com/c/8PjGOadD
