### ISSUE TITLE
Character entities showing in settings dialog

### ISSUE THREAD

**Issue by JVimes** [codecadwallader/codemaid#632]
### Environment
- Visual Studio version: 2019 preview
- CodeMaid version: 11.0.174

### Description
I think these were supposed to render to their actual characters:

![image](https://user-images.githubusercontent.com/6148201/54766484-f358d500-4bc0-11e9-9730-5e03f6d757d2.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  It looks like that was introduced when we internationalized and strings are being encoded in XML.
