### ISSUE TITLE
CodeMaid cant run

### ISSUE THREAD

**Issue by CyberWolf755** [codecadwallader/codemaid#636]
### Environment
- Visual Studio version: VS2017 Enterprise
- CodeMaid version: 11.0.183
- Code language: C#

### Description
ActivityLog data

SetSite failed for package [CodeMaidPackage]Source: 'SteveCadwallader.CodeMaid' Description: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   at SteveCadwallader.CodeMaid.CodeMaidPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

### Steps to recreate
Not sure if this was the cause of the issue
1.Unity sometimes reopens it's VS solution in a new VS window.
2.Edit some files
3.When prompted by VS that files have been edited and need to be reloaded, pressed dont reload all files.

After that point CodeMaid didn't work for me

### Current behaviour
VS had issues of freezing for an hour, and later I was able to run VS, but codemaid is crashing every time its run with the error written above. Uninstalling and reinstalling CodeMaid from VS doesn't help

### Expected behavior
Run properly

**Comment by forest-devil** [comment]
+1 for this, but I don't know what caused the problem, I just started VS and loaded a project in the morning, then it gave me the save error. Even the logs are exactly the same.

**Comment by forest-devil** [comment]
oops this is duplicated to https://github.com/codecadwallader/codemaid/issues/634

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Yep please take a look at #634 and if you think there's a separate issue please just reopen this and let me know!
