### ISSUE TITLE
Spade is not working with Typescript files

### ISSUE THREAD

**Issue by Dia6lo** [codecadwallader/codemaid#64]
So, yeah, it remains empty even after refreshing.
![default](https://cloud.githubusercontent.com/assets/8434406/5766850/97cc6e06-9d58-11e4-8204-01b0aa7f9f27.PNG)

**Comment by codecadwallader** [comment]
That is as expected.  Spade currently supports C#, C++ and VB - those languages which the Visual Studio API exposes a code model out that we can consume and display.  Unfortunately even with the Roslyn compiler in VS2015 that list of supported languages does not appear to be changing anytime soon.
