### ISSUE TITLE
Comment formatting incrementally adds slashes

### ISSUE THREAD

**Issue by willemduncan** [codecadwallader/codemaid#646]
We've tested the v11.0.188 build from the CI. Both issues seem to have resolved, but a new one seems to have arised... 😅

When formatting a comment with at least a section that is multiline, it starts adding backlashes each time is formatted.

For example:

Original comment
```cs
/// <summary> This is a summary. </summary>
/// <param name="param"> This is a multiline comment for the parameter param. It is going to add backlashes. </param>
/// <returns> The returns. </returns>
```

Then, after the first time I format the document:
```cs
/// <summary> This is a summary. </summary>
/// <param name="param">
///     This is a multiline comment for the parameter param. It is going to add backlashes.
/// </param>
///        /// <returns> The returns. </returns>
```

A second time:
```cs
/// <summary> This is a summary. </summary>
/// <param name="param">
///     This is a multiline comment for the parameter param. It is going to add backlashes.
/// </param>
///        /// ///
/// <returns> The returns. </returns>
```

From then on, the line of backlashes will grow each time the document is formated.

Should we keep using this issue or create a new one?

_Originally posted by @Starkie in https://github.com/codecadwallader/codemaid/issues/564#issuecomment-483533240_

**Comment by codecadwallader** [comment]
With the changes from #647 I re-tried the example comment above and I am still seeing the growing lines of slashes.  @willemduncan can you take another a look when you have a chance please? :)

**Comment by willemduncan** [comment]
That is very strange. Thanks for double checking, I will look into it right away.

**Comment by Starkie** [comment]
We have tested it with the current CI build and it seems that this error doesn't happen anymore. 👍

**Comment by willemduncan** [comment]
That's good to hear, sorry for the inconvenience caused in the meantime. Need to get a more serious test suite!

@codecadwallader waiting for your input before closing the issue.

**Comment by codecadwallader** [comment]
Yep it's working for me too (v11.0.190), perhaps I tested it too soon last time.  Thanks @willemduncan ! :)
