### ISSUE TITLE
Support for vNext (.kproj) projects

### ISSUE THREAD

**Issue by djanosik** [codecadwallader/codemaid#65]
It seems CodeMaid is at least partially not working in vNext projects. Cleanup, Spade, etc. does not work. Also Spade throws an exception in "old" projects opened in VS 2015. I will try to provide more details if possible.

**Comment by codecadwallader** [comment]
Thanks for reporting this issue.  Debugged, and no FileCodeModel is being returned which is the basis for many cleanup activities and all of Spade.  Starting in VS2015 they have switched over to utilizing the Roslyn compiler and new APIs.  In other project types the old API is still returning results as expected, but in this area the old API does not appear to be supported.

Resolving this is basically tied to the Roslyn rewrite of CodeMaid, which is a huge effort but on our radar.  There's a card in the backlog to track that effort: https://trello.com/c/L3Peail8

Thanks again for reporting, the heads up about .kproj files not working is good to have.

**Comment by djanosik** [comment]
Good news, it is fixed in VS 2015 CTP5. Everything works, but an exception is still thrown when I first time open Spade.

    Roslyn.Utilities.Contract+ContractFailureException: Unexpected false 
    at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition, String message) 
    at Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource`1.GetTagIntervalTreeForBuffer(ITextBuffer buffer) 
    at Microsoft.CodeAnalysis.Editor.Shared.Tagging.AsynchronousTagger`1.GetTags(NormalizedSnapshotSpanCollection requestedSpans) 
    at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__1.MoveNext()

**Comment by codecadwallader** [comment]
That is very good news, thanks for the update.  I haven't had a clear picture on how much backwards compatibility they intend to maintain.
