### ISSUE TITLE
CodeMaid for VS code

### ISSUE THREAD

**Issue by suchoss** [codecadwallader/codemaid#650]
### Environment
- VS code

### Description
Hello, I was using CodeMaid in Visual Studio and I wonder if there is any plan to do also an extension to VS code?

Many thanks. 

Btw. Great work guys.

**Comment by codecadwallader** [comment]
Thanks for the kind comment and interest. :)  It's definitely a popular request but it's sadly no small feat.  Check out #273 for a lot more information.
