### ISSUE TITLE
Reformat comment without space

### ISSUE THREAD

**Issue by sm-g** [codecadwallader/codemaid#66]
Ctrl+M,N not work on this:
````
/// <summary>
///Set flag.
/// </summary>
````

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  That is expected behavior as we're matching on the presence of a spacer after the XML comment prefix.  There is a card in the backlog to auto-insert that whitespace which would then allow comment formatting to run: https://trello.com/c/Nl9lZBqZ
