### ISSUE TITLE
Question: Is it possible to call Code Maid Clean-Up without the GUI

### ISSUE THREAD

**Issue by WTVIII** [codecadwallader/codemaid#677]
### Environment
- Visual Studio version: 2017 Professional
- CodeMaid version: 11.0
- Code language: VB.NET, C#.NET

### Description
Question: Is it possible to call Code Maid Clean-Up without the GUI

### Steps to recreate
Is it possible to call Code Maid "Cleanup All Code" without the GUI, i.e., from the command line or by incorporating and using a DLL.

### Current behavior
Currently, we run Code Maid manually via GUI from within Visual Studio.

### Expected behavior
Feature request: the ability to run Code Maid with a common configuration over a large set of solutions in an automated way. We have a large code base and would like to be able to periodically run Code Maid over multiple projects/solutions in an automated way using a common configuration.  This will help eliminate "noise" when we do code check-in in source control repositories.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I would love to make that possible, but unfortunately no it is not currently available.  CodeMaid is heavily dependent on the Visual Studio APIs which (as far as I know) are only accessible within the loaded context of a Visual Studio process.

**Comment by WTVIII** [comment]
Thank you very much for your response.  Really appreciate you taking the time.
