### ISSUE TITLE
Unable to Install CodeMaid On VS2017 Professional 15.9.17

### ISSUE THREAD

**Issue by puneethprakash** [codecadwallader/codemaid#689]
### Environment
- Visual Studio version: [2017 Professional 15.9.17]
- CodeMaid version: [11.1.204]
- Code language: [C#]

### Description
When i install It does not get installed telling that it cannot be installed on this version

### Steps to recreate
1. Update VS 2017 to  15.9.17 from an older version (15.9.15) with code maid already installed
2. Code maid disappears 
3. Try to install again by clicking Tools > Extensions and Updates

### Current behavior
Unable to install or carryover from 15.9.15 version of VS2017 to 15.9.17 VS2017

### Expected behavior
Should be able to carryover and install

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been able to reproduce it.  I believe it is an issue with the manifest version.

**Comment by codecadwallader** [comment]
It indeed was an issue with the manifest version.  I was trying to follow advice from https://devblogs.microsoft.com/visualstudio/visual-studio-extensions-and-version-ranges-demystified/ about being more specific on minor version requirements but it did not work as expected.  I switched back to only having a major version requirement.

v11.1.209 is now live in the marketplace.

Apologies for the issue and thanks again for reporting it!
