### ISSUE TITLE
CodeMaid Spade window is empty

### ISSUE THREAD

**Issue by SirMossi** [codecadwallader/codemaid#697]
### Environment
- Visual Studio Professional 2017 (15.9.18)
- CodeMaid version: 11.1.209
- Code language: C#

### Description
When opening a C# file, the CodeMaid Spade window does not show anything. On my previous computer it worked perfectly. Now it show's for a short time the loading animation and then the window keeps clean.
How can I fix this? Can I find any logs, to see what went wrong?

**Comment by spreedated** [comment]
It's hard to tell without a look on the C# you try to display on spade.
Does it work with other files?

**Comment by codecadwallader** [comment]
One common scenario is if the file is not a part of the solution there won't be a code model available for it.  This can happen if you drag and drop a file into Visual Studio, use File->Open to bring up a C# file that is not included, have "Show all files" enabled and select a file that is not included, etc.

It's not the only possibility, but it's definitely one!  The question above about it working with other files is a great question as well. :thumbsup:

**Comment by SirMossi** [comment]
This problem affected all files in a C# solution. Before reinstalling the system all worked fine in the same solution.
But I could fix the problem by uninstalling CodeMaid and deleting the complete extension folder in appdata\local. After reinstalling the extension it worked fine.

So the problem seems to be fixed

**Comment by codecadwallader** [comment]
I'm glad you got it working, thanks for following up with the steps you took.
