### ISSUE TITLE
High memory usage of codemaid

### ISSUE THREAD

**Issue by prebenh** [codecadwallader/codemaid#70]
When I enable codemaid in Visual studio 2013, I experience very slow performance.

Examples: Building with codemaid enabled takes around 6 minutes. 
Memory consumption is **1.400 Mb**

Without codemaid, solution build in 2 minutes and memory consumption is less then **500 Mb.**

I've tried disabling all my plugins like Resharper, vscommands and others. But the only time memory drops is when codemaid is disabled.

I don't use the spade, is their a way to disable more features of codemaid?

**Comment by codecadwallader** [comment]
If you're not utilizing Spade, then CodeMaid is generally very passive.  Do you have automatic cleanup on save enabled?  Otherwise I would not expect you to be tripping any significant CodeMaid events.

**Comment by prebenh** [comment]
Automatic cleanup is enabled, with remove and sort usings, and remove regions.
But not the third party clean up.

Can the automatic clean up have impact on the build. I also disabled the build progress bar. This helps with lower the build time.

**Comment by codecadwallader** [comment]
Running a build will first cause any unsaved files to be saved, and that would trigger automatic cleanup on save for those files.

**Comment by prebenh** [comment]
Same problem exists, when I use save all before build.

**Comment by codecadwallader** [comment]
Do you have any memory profiling tools available?  We're not seeing that kind of memory consumption with other users and we've confirmed with the last major release that we had a flat-line for memory leaks (note: VS consumes memory every time you open a document regardless of closing it.. same behavior w/o CodeMaid).

**Comment by prebenh** [comment]
Disabling Fusion logging solved my issue.

**Comment by codecadwallader** [comment]
Glad to hear you got it resolved, thanks for following up.
