### ISSUE TITLE
CodeMaid for Mac!

### ISSUE THREAD

**Issue by ecollis6** [codecadwallader/codemaid#706]
### Environment
- Visual Studio version: 2019 Mac Community
- CodeMaid version: 10.2
- Code language: C#

### Description
Can you please add Mac support?

### Steps to recreate
1. Install VS on Mac
2. Attempt to install CodeMaid

### Current behavior
It isn't there 😢 

### Expected behavior
It should be there ❤️

**Comment by mstagg** [comment]
I have also experienced this issue and it's affecting my workflow. Please patch soon!

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  There's an existing #466 which has more information.
