### ISSUE TITLE
CodeMaid does not appear in VS 2019 after installing, despite saying 'Enabled'

### ISSUE THREAD

**Issue by atriusfox** [codecadwallader/codemaid#711]
### Environment
Microsoft Visual Studio Professional 2019 Version 16.4.5
CodeMaid 11.1.209

### Description
No CodeMaid options appear within VS 2019.

After adding the extension from Extensions -> Manage Extensions and finding CodeMaid online, CodeMaid shows up as an installed extension that is 'Enabled' however there is no visual change to the IDE.

After searching through the Issues already here I have tried reinstalling VS 2019, Repairing VS 2019, and reinstalling the Extension.

I also have VS 2017, it works fine there, however we need it for 2019.

The options do NOT show in keyboard shortcuts as per this issue:
https://github.com/codecadwallader/codemaid/issues/639

But it does install as opposed to this issue:
https://github.com/codecadwallader/codemaid/issues/688

Thus I felt this was a separate issue somehow.

### Steps to recreate
1. Install VS 2019 Professional and ensure it is fully updated.
2. Go to Extensions -> Manage Extensions -> Online and install CodeMaid
3. Verify CodeMaid shows in Installed Extension list and is Enabled
4. Verify no change to IDE

### Current behavior
No CodeMaid commands are visual options appear post install.

### Expected behavior
CodeMaid commands and toolbar options appear.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I agree a successful installation but no visible options would be a unique issue.  Here's a few things to check:

1.  Have you exited Visual Studio for the installation to happen?  Extensions can only install/update when Visual Studio is closed.  There's a small yellow banner that indicates that but it is easy to miss.

2.  If you go to the Extensions menu.. does CodeMaid or any other extension show up?  Here's a screenshot of what it should normally look like:

![image](https://user-images.githubusercontent.com/3823772/75096149-a29de900-5594-11ea-9084-a3b51d5c00c4.png)

3.  If you go to the Help->About dialog, does CodeMaid show up?

**Comment by atriusfox** [comment]
1. Yes I did this at all attempts.  I was able to install sonarlint successfully.

2. No items showed in the extensions list. I'm unsure if sonarlint should have in hindsight.

3.  I do not recall, I'll have to check my machine on Monday.

I was able to install codemaid successfully on another work machine after I had reported this ( a colleagues machine) and successfully on a home machine.

So it's evidently something specific to my work machine.  Just unsure how to troubleshoot it.

**Comment by atriusfox** [comment]
While I still don't understand exactly what the issue was (what was causing it).

I found this resolved it:

https://developercommunity.visualstudio.com/content/problem/653928/extensions-menu-missing.html

**Comment by codecadwallader** [comment]
Interesting, thank you for commenting back with the fix and glad it's working for you now. :)

**Comment by codecadwallader** [comment]
For the archives (in case that link goes bad).. if the extension menu is not showing up you can reset the toolbars in Visual Studio via Tools->Customize->Commands->Menu Bar->Reset all.
