### ISSUE TITLE
Line spaces added in between enum labels

### ISSUE THREAD

**Issue by chris-thompson-go** [codecadwallader/codemaid#713]
### Environment
- Visual Studio 2019 Pro v16.4.5
- CodeMaid version: 11.1
- Code language: C#

### Description
Line spaces are being added in between enum labels.

### Problem
public enum Colors
{
Blue,
Red,
Yellow,
}

becomes: 

public enum Colors
{
Blue,

Red,

Yellow,
}

Attached are my Code Maid Insert settings.  I'm not sure crossing out "enumerations" would mean line spaces between labels.
 However, (don't have perfect recollection) but I don't remember Code Maid doing this before.
![CodeMaidInsertSettings](https://user-images.githubusercontent.com/16925267/75737931-ca3c3200-5cb5-11ea-9830-ccd4577c77f4.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  You're correct that "enumerations" means before after the enum itself, not the individual components within it.

I believe it is the "single-line fields" option that is influencing the enumeration values.  IIRC the API reports them as the same type of object.  I'm able to reproduce the issue if I enable that setting which is off by default.  Do you see the same?

**Comment by chris-thompson-go** [comment]
Yes sorry, I must have enabled insert-blank-line for single-line fields and did not carefully test that.  I crossed off single-line fields and enabled enumerations.  I guess it is inconsistent for me to want blank lines between fields but not between enum labels.  Thank you!
