### ISSUE TITLE
else statements brackets

### ISSUE THREAD

**Issue by beyaz** [codecadwallader/codemaid#73]
here is my code 

           if (Environment.NewLine == "f")
            {
                Environment.NewLine.ToArray();
            }
            else
                Environment.NewLine.ToArray();

Is there any options for getting these output

           if (Environment.NewLine == "f")
            {
                Environment.NewLine.ToArray();
            }
            else
            {
                Environment.NewLine.ToArray();
            }

**Comment by codecadwallader** [comment]
Not yet, but it is on our backlog to support with the new VS2015 compiler.  Vote/track here: https://trello.com/c/OYUlarhQ
