### ISSUE TITLE
cshtml formatting broken

### ISSUE THREAD

**Issue by spatrick195** [codecadwallader/codemaid#734]
### Environment
- Visual Studio version: Visual Studio 2019 16.6.2
- CodeMaid version: 11.1.209
- Code language: ASP.NET MVC CsHtml

### Description
Note: This is a fresh installation of Visual Studio 2019.

As you can see in the code snippet below, the formatting is broken. It seems to only be C# inserts that are incorrectly formatted. I'll note that the last bracket of the for each statement switches from at the end of the line to a new line, and repeats this process every time the code is formatted.
![ZYdJz0r](https://user-images.githubusercontent.com/37867393/84229028-ae5ded00-ab3c-11ea-87cd-a768a15eca13.gif)

### Steps to recreate
1. Create a model and then a view based on that model
2. Make a for each statement in a html table that would iterate through the model items
3. Turn on 'Format on Save' in the CodeMaid plugin.
4. Save the document.

**### Current behaviour**
Document is being formatted incorrectly. 
**### Expected behaviour**
Document should be formatted with the correct indents.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  The indentation is processed natively by Visual Studio and is invoked by CodeMaid.  If you run Edit->Advanced->Format Document (the native command we invoke as part of our cleanup) are you seeing the same behavior?

**Comment by spatrick195** [comment]
> Thanks for reporting the issue. The indentation is processed natively by Visual Studio and is invoked by CodeMaid. If you run Edit->Advanced->Format Document (the native command we invoke as part of our cleanup) are you seeing the same behavior?

The same issue occurs when following the process you have described.

**Comment by codecadwallader** [comment]
Thanks for confirming the steps.  Since it is a native Visual Studio issue I would recommend using the report a problem feature within the tool: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

**Comment by spatrick195** [comment]
Seems to have resolved itself at this point.
