### ISSUE TITLE
CodeMaid for VS Code

### ISSUE THREAD

**Issue by Alvin-Seville** [codecadwallader/codemaid#742]
Please create `CodeMaid` for `Visual Studio Code`. I use this editor and it would be nice to have `CodeMaid` for it.

**Comment by codecadwallader** [comment]
Thanks for making the request.  There is an existing issue #273 for this request.  If you would like to provide any details on that issue about what features you would like to see that would be helpful.

**Comment by PinkDoc** [comment]
CodeMaid for vscode :)
