### ISSUE TITLE
CodeMaid makes intellisense shows an error in Blazor WebAssembly

### ISSUE THREAD

**Issue by Thibaud-Ier** [codecadwallader/codemaid#743]
### Environment
- Visual Studio version: VS Studio 2019 Community Version 16.7.0 Preview 3.1
- CodeMaid version: 11.1.209
- Code language: C#

### Description
Hello everyone.

I think I found an error with CodeMaid.
I got this error first:
https://stackoverflow.com/questions/62747671/blazor-webassembly-project-intellisense-pops-an-error-the-type-or-namespace-n/62855830#62855830

After deactivating CodeMaid, the error disparears.

### Steps to recreate
1. Create a Blazor WebAssembly project on Visual Studio 2019 with CodeMaid installed.
2. Open the Program.cs file of the project and you will see the error. 

### Current behavior
Intellisense shows an error.

### Expected behavior
No error shown

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have been unable to reproduce it using Preview 3.2.  If you're still able to reproduce it with the latest preview edition, are there any other steps besides opening the Program.cs file that make it appear?

**Comment by Thibaud-Ier** [comment]
It seems fixed now. I don't see it again. Thank you
