### ISSUE TITLE
Codemaid does not comply with StyleCop in using directives ordering

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#75]
I'm using `CodeMaid` and `StyleCop` in simultaneously. Mostly I'm asking `CodeMaid` to make my code comply rules set by `StyleCop`. And it most cases everything goes right as it should be.

However `CodeMaid` rearranges `using` directives alphabetically, while `StyleCop` prefers **System** directives be upper in the list.

As result I'm constantly getting following warning:
```
SA1208 : CSharp.Ordering : System using directives must be placed before all other using directives.	
```

I think it would be no harm, if `CodeMaid` and `StyleCop` will find common ground on this point.

**Comment by codecadwallader** [comment]
Microsoft changed away from that standard starting with Visual Studio 2012 and the introduction of the Windows namespaces, but you can re-enable putting System directives first by changing a setting.  It is located at:

Tools->Options->Text Editor->C#->Advanced->"Place 'System' directives first when sorting usings".  It is off by default now, but used to be on by default in VS2010 and earlier.

**Comment by shytikov** [comment]
Thank you, I was not aware about this switch. And you right, I just switched from `VS2010` to `VS2012`.

:+1:

**Comment by codecadwallader** [comment]
No problem, enjoy. :)
