### ISSUE TITLE
fontsize

### ISSUE THREAD

**Issue by tersonly** [codecadwallader/codemaid#750]
### Environment
- Visual Studio version: [example 2019]
- CodeMaid version: [example 10.2]
- Code language: [example C#]

### Description
How to set the font size of codeMaid separately? Instead of using the font size in vs? Mouse scrolling looks blurry after zooming in

**Comment by codecadwallader** [comment]
Thanks for asking the question.  There is not currently a way to set a separate font size for CodeMaid compared to Visual Studio.

Here's a highly zoomed screenshot example: 
![image](https://user-images.githubusercontent.com/3823772/94681122-e6a65880-02f0-11eb-833b-93e7fd91dd14.png)

**Comment by tersonly** [comment]
thank you
