### ISSUE TITLE
Feature Request: Allow inserting prefix on member access

### ISSUE THREAD

**Issue by Dreamwalker666** [codecadwallader/codemaid#76]
Have an option to inserting the "this", "me" etc prefix If a class member is accessed with out the prefix. I would expect this off by default.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  That feature is available in other tools like ReSharper, and requires a more complex code model that would only be available to tools like CodeMaid starting in Visual Studio 2015.

If you would like to have a card added to the backlog let me know, but to be honest it would be a lot of work for a feature that would be off by default and I wouldn't anticipate it getting prioritized.
