### ISSUE TITLE
How can I format selected lines? 

### ISSUE THREAD

**Issue by fairking** [codecadwallader/codemaid#760]
### Environment
- Visual Studio version: 2019 Community]
- CodeMaid version: 11.1
- Code language: C#

### Description
How can I format selected lines? 
The formatting on save is disabled.
Thanks

![image](https://user-images.githubusercontent.com/13495631/97785709-a4499300-1b9e-11eb-907b-9c7c897e9de4.png)

**Comment by codecadwallader** [comment]
Thanks for asking the question.  Currently there isn't a way to only format a highlighted section of code.  See #542 for more details.
