### ISSUE TITLE
Shared CodeMaid.config file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [codecadwallader/codemaid#764]
Is it currently possible to share a CodeMaid.config file among several .sln files?

Our project structure is like this:

**Main.sln**
- App.csproj
- backend_lib.csproj

**Library.sln**
- backend_lib.csproj

Currently we copy the CodeMaid.config file to both the Main.sln and Library.sln directories, but it seems like it might be nice to instead be able to put something in the .sln file to tell it to use a shared CodeMaid.config file.

I don't think this is a big requirement for us, but I figured I'd ask 🙂

**Comment by codecadwallader** [comment]
Thanks for asking the question.  No, at this time there isn't a way to share a CodeMaid.config file across multiple solution files beyond the direct copy/paste mechanism you're already doing.

The closest workaround would be to have everyone on the team import that as your user settings, which becomes the default for all solutions unless there are solution-specific settings inside the code base.

**Comment by Eli-Black-Work** [comment]
Thanks! 🙂

I think this could also be solved by #710, so I'm closing this for now.

Thanks again 🙂

**Comment by Eli-Black-Work** [comment]
Visual Studio has recently released a new feature, [Filtered Solutions](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019), that fixed this for us.

Steps:
1. Create a solution file (`.sln`) that contains all of your projects.
2. Put your `CodeMaid.config` file next to the solution file.
3. Make some filtered solutions that point to the main solution.
4. The filtered solutions automatically use the main CodeMaid.config file!

Yay! ^_^
