### ISSUE TITLE
Auto Cleanup On Save - Only for some files 

### ISSUE THREAD

**Issue by Timo-Weike** [codecadwallader/codemaid#773]
### Environment
- Visual Studio version: 2019 Professional
- CodeMaid version: 11.1
- Code language: C#

### Description
I like the "Auto Cleanup On Save"-Feature to keep my files organized, but if I work in an old code-base I don't want to update every file where I might only changed one line, but would like to have all new added files auto cleaned on save.

I would propose something like a pragma that could be added to either all new files which should be auto cleanedup on save or to all files that should not auto cleaned on save. I would prefer the first solution.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I'm not against it but here are a couple workarounds that come to mind:

One approach that others have taken is to utilize the ability to exclude different paths in CodeMaid's configuration.  Under CodeMaid->Options->Cleaning->File Types there is the ability to specify file extensions, folders, etc. that should(tm) be skipped.  So for example if there is an old project and you want to ignore everything in its folder it can be specified there.

A second approach is that you can quickly toggle on/off auto cleanup on save via a keyboard shortcut.  The default is `Ctrl+M, '`

**Comment by Timo-Weike** [comment]
Thanks for the quick reply. I think the second approach is not suited for me, since it is quiet error prone and could cause a headache if you forget to turn it off. 

I like the first approach more but would like the option to whitelist files and generally exclude all not whitelisted files.
Maybe a good solution would be to add second list with inclusion regexes.
I don't know how it is now implemented, but I would work like that:

 1. check if the extension of the file is included, if not don't clean up
 2. check if the path matches an exclusion regex, if not clean up else go to 3.
 3. check if the path matches an inclusion regex, if not don't clean up

My scenario is that I am working in an old codebase and extend it, so the new auto cleanable files are spread over the whole project.

If we could agree on how to add this feature I would be willing to help to implement it.

**Comment by codecadwallader** [comment]
I think an inclusions file list to mirror the exclusions file list makes sense and is a good idea. :)  By default it would be blank and that would mean all files are included (same as current behavior).  If someone added entries, then _only_ files meeting that criteria would be cleaned.

The options implementation would pretty well mirror the exclusions, and then the logic that controls whether or not a file is included would fit into the `CodeCleanupAvailabilityLogic.cs` class.  Here's where the exclusions happen for context: https://github.com/codecadwallader/codemaid/blob/dev/CodeMaid/Logic/Cleaning/CodeCleanupAvailabilityLogic.cs#L112

**Comment by Timo-Weike** [comment]
We may also should consider to add a quick action to add a file to the inclusion/exclusion list

**Comment by Timo-Weike** [comment]
@codecadwallader what do you think about my suggestion for an quick action? Or should I simply open a new issue for it?

**Comment by codecadwallader** [comment]
I think a separate issue would make sense. 👍
