### ISSUE TITLE
[Question] Two-line property format

### ISSUE THREAD

**Issue by einsteinsci** [codecadwallader/codemaid#78]
I generally format my properties on two lines (unless I have an explicit getter/setter), the first consisting of the type, and name, the second of the braces and accessors, so they end up looking like this:
```csharp
public int Number
{ get; private set; }
```
The problem I have is that CodeMaid wants to split it up across multiple lines during cleanup, which turns it into this:
```csharp
public int Number
{
    get;
    private set;
}
```
Is there anywhere in the options to prevent this? If not, is there any way to have cleanup ignore properties but still clean the rest of the code?

**Comment by codecadwallader** [comment]
I'm not seeing that behavior with Visual Studio 2015 and CodeMaid v0.7.5 with the default configuration.  Here's the code sample I tested:

    namespace SpecificIssueTesting
    {
        internal class Issue78
        {
            public int Number
            { get; private set; }
        }
    }

A few things to check:
1.  Option under CodeMaid->Configuration->Cleaning->Update->"Update accessors to both be single-line or multi-line (SA1504)".  This is off by default
2.  Run Edit->Advanced->Format Document.  If this causes the formatting above to occur, then it is a Visual Studio setting that is causing the behavior.
3.  Option under Tools->Options->Text Editor->C#->Formatting->Wrapping->"Leave block on single line".  This is on by default.

**Comment by einsteinsci** [comment]
Strangely enough, it started working as expected now. Not sure what I messed with to get it to work, but thanks!

**Comment by codecadwallader** [comment]
All's well that ends well, thanks for following up. :)
