### ISSUE TITLE
Saving an Xaml file with unused namespace(s) causes all namespaces to get mixed up.

### ISSUE THREAD

**Issue by LeoJHarris** [codecadwallader/codemaid#787]
### Environment
- Visual Studio version: Community 16.8.5
- CodeMaid version: 11.2
- Code language: C#

### Description
When saving an XAML file with an unused namespace causes all the namespaces to become mixed up... the unused namespace is actually removed however

### Steps to recreate
Save an XAML file with unused namespace

### Current behavior
Namespaces get all mixed up and leads to incorrectly defined xaml file

### Expected behavior
Should removed unused namespace and Xaml file should still be correctly defined.

Before save (note red arrow pointing to unused namespace)
![before](https://user-images.githubusercontent.com/5468757/108456772-efb2b900-72d5-11eb-88de-933e4b9696c6.PNG)

After save:
![after](https://user-images.githubusercontent.com/5468757/108456846-28529280-72d6-11eb-934d-2abc8909cd33.PNG)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I wasn't able to immediately reproduce it.  Can you please provide a minimal solution that exhibits the bug?

**Comment by DuncanStone** [comment]
I have this too. It happens in a lot of my xaml files but I cant reproduce it in a sample project, even when I copy and paste the repeatably broken files into the test project verbatim.

I am unable to share the affected code sorry.

**Comment by LeoJHarris** [comment]
@codecadwallader I should be able to get a sample project soon.

**Comment by reiseder** [comment]
It seems to have something to do with simultaneously sorting and removing namespaces.

Deleting a namespace when all of them are sorted works correctly. Once a file is "broken" you have to restart Visual Studio to make it work again.

**Comment by fabianoriccardi** [comment]
Just happened, but it is very rare, I can't reproduce it.

**Comment by LeoJHarris** [comment]
@LeoJHarris closing this as no longer appears to be an issue anymore. Using it with VS 2022 community for the last wee while without incident.
