### ISSUE TITLE
Can I exit Spade search, after putting the filter to results of searching with the keyboard? It would be helpful for quickly finding the content and next setting the cursor on an appropriate position in code. (now I'm doing this with the mouse this is a slower option)

### ISSUE THREAD

**Issue by Roland197403** [codecadwallader/codemaid#789]
### Environment
- Visual Studio version: [example 2015 Community]
- CodeMaid version: [example 10.2]
- Code language: [example C#]

### Description
Replace this text with a short description and code sample.

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
Explain what it's doing and why it's wrong.

### Expected behavior
Explain what it should be doing after it's fixed.

**Comment by codecadwallader** [comment]
Thanks for asking the question.  I think this is the same as #732

**Comment by Roland197403** [comment]
Yes, of course, it is the same issue.
