### ISSUE TITLE
Building solutions crashes while CodeMaid is enabled since the latest VS update.

### ISSUE THREAD

**Issue by ldwrs** [codecadwallader/codemaid#792]
### Environment
- Visual Studio version: professional 2019 16.9.0
- CodeMaid version: 11.2.231
- Code language: C#

### Description
Building my solution crashes while CodeMaid is enabled since the latest VS update.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I am unable to reproduce it.  Can you please provide some more information and/or a minimal solution that exhibits the issue?

**Comment by ldwrs** [comment]
After complete uninstalling and reinstalling VS I cannot reproduce it anymore. The problem must have been something specific with my setup...
