### ISSUE TITLE
Warning message output not correct

### ISSUE THREAD

**Issue by Hefaistos68** [codecadwallader/codemaid#799]
![image](https://user-images.githubusercontent.com/8855055/112302540-1d9f6a80-8c93-11eb-8b81-6c29c517727e.png)

### Environment
- Visual Studio version: 2019 Community 16.9.2
- CodeMaid version: 11.2
- Code language: C#

### Expected behavior
Guess the image says all.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, a picture is worth a thousand words.  Reproduced.

**Comment by codecadwallader** [comment]
![image](https://user-images.githubusercontent.com/3823772/114024269-d6dc7380-9841-11eb-9df2-250dc07c5268.png)
