### ISSUE TITLE
Automatic cleanup on save take so long!

### ISSUE THREAD

**Issue by Trxplz0** [codecadwallader/codemaid#80]
Automatic cleanup on save take so long... sometimes up to 6 minutes.

### Current settings ###

- Reorganize disabled
- Code Spade sync disabled
- **Performance Settings:** cache file code models, load models async, multithread operations both checked
- **Cleaning Settings:** Format document checked

### Diagnostics ###

    [CodeMaid Diagnostic 02:32:36 ] WindowEventListener.OnWindowChange raised for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:32:37 ] RunningDocumentTableEventListener.BeforeSave raised for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:32:37 ] CodeCleanupManager.Cleanup started for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:32:37 ] TextEditorEventListener.OnLineChanged raised for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:32:37 ] TextEditorEventListener.OnLineChanged raised for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:33:41 ] CodeCleanupManager.Cleanup completed for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:33:41 ] RunningDocumentTableEventListener.AfterSave raised for 'C:\....\_CreateOrEdit.cshtml'

    [CodeMaid Diagnostic 02:37:45 ] ConfigurationCommand.OnExecute invoked

I'm missing something??

**Comment by codecadwallader** [comment]
That is far longer than the normal experience.  Some things to try:

1)  If you run a manual cleanup, does it take as long?
2)  What version of Visual Studio are you using?
3)  What other extensions do you have enabled?
4)  Is the behavior consistent across all files, or just specifies ones (e.g. CSHTML)?
5)  Can you provide a code sample that exhibits the issue so we can test if it happens in a different environment?

**Comment by Trxplz0** [comment]
Thanks for answering!

I found the problem... **Error Watcher** extension.

I have been using this extension at work and home and i don't know for sure but it is something about project size.

My home projects are small/medium size, even with extension enabled works normally.

**Comment by codecadwallader** [comment]
It looks like it has been renamed to Error Catcher since it was originally released.  Can you make sure you have the latest version?  The Q&A section shows Mads has made some performance improvements to it over time.  https://visualstudiogallery.msdn.microsoft.com/a85f155f-b519-44a8-b56b-07611cf78393

I wasn't able to reproduce it with a large C# project, or a medium HTML project.  I could try to reproduce it a little bit more if you can point me to some code that reproduces the issue?

**Comment by Trxplz0** [comment]
I reinstall **CodeMaid** and **Error Catcher** and it's working as expected (1~4 seconds for large files).

This is strange, the only change i did in the last months was update VS.

Thanks for help anyway...

**Comment by codecadwallader** [comment]
Strange, but glad it is working for you now.

**Comment by codecadwallader** [comment]
Strange, but glad it is working for you now.
