### ISSUE TITLE
CodeMaid not inserting expected blank lines after #region and methods

### ISSUE THREAD

**Issue by jwstemper** [codecadwallader/codemaid#809]
### Environment
- Visual Studio version: 2019 Community 16.9.4
- CodeMaid version: 11.2.231
- Code language: C#

### Description
Cleanup not inserting blank lines after #region and method declarations. I have this enabled in the config.
Also not removing redundant spaces anywhere.
Also not realigning misaligned method declarations.

### Steps to recreate
1. Replace this
2. text with 
3. the steps
4. to recreate

### Current behavior
```          [Key]
                 public int Id {   get; set;              }                 
        [Required]  
        public bool? IsActive       { get; set; }
```

### Expected behavior
```     [Key]
        public int Id { get; set; }                 
        
        [Required]
        public bool? IsActive { get; set; }
```

**Comment by jwstemper** [comment]
Was trying to clean up an autogenerated file.  My mistake

**Comment by codecadwallader** [comment]
Cool, thanks for coming back to clarify. 👍
