### ISSUE TITLE
How to prevent adding new line for empty brackets for methods with more than one line

### ISSUE THREAD

**Issue by ThiagoFerreira84** [codecadwallader/codemaid#812]
### Environment
- Visual Studio version: Microsoft Visual Studio Professional 2019
- CodeMaid version: 11.2
- Code language: C#

### Description
I have the following code:

    public UserRepository(ILogger<UserRepository> logger, IOptionsMonitor<CacheSettings> cacheSettingsAccessor, IAppCache cache, UserDirectoryContext dbContext) :
        base(logger, cacheSettingsAccessor, cache, dbContext) { }
It is expected to remain like this but CodeMaid in its most recent version it is converting sending the brackets to a new line:

public UserRepository(ILogger logger, IOptionsMonitor cacheSettingsAccessor, IAppCache cache, UserDirectoryContext dbContext) :
base(logger, cacheSettingsAccessor, cache, dbContext)
{ }

The option you mentioned previously "Update single line methods by placing braces on separate lines (SA1502)" only works for single line, on my case my method uses two lines, reason why that settings don't apply. Is there any way to make CodeMaid not change this code keeping the brackets in the same line?

Many thanks

### Steps to recreate
1. place the following code on C#:
public UserRepository(ILogger<UserRepository> logger, IOptionsMonitor<CacheSettings> cacheSettingsAccessor, IAppCache cache, UserDirectoryContext dbContext) :
        base(logger, cacheSettingsAccessor, cache, dbContext) { }
2. Run CodeMaid Cleanup 
3. The brackets should remain in the same line, instead of creating a new line

### Current behavior
It is sending the brackets to a new line.

### Expected behavior
Brackets should remain where it is.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  As part of CodeMaid's cleanup, we invoke Visual Studio's cleanup.  The brace movement you are seeing is coming from Visual Studio.  You can change the configuration at Tools->Options->Text Editor->C#->Code Style->Formatting->New Lines->Place open brace on new line for methods and local functions

![image](https://user-images.githubusercontent.com/3823772/118980369-6730cc80-b947-11eb-8ae4-f40bc61d227c.png)

Hope it helps!

**Comment by ThiagoFerreira84** [comment]
Thank you @codecadwallader, I've applied these changes and it is now behaving as expected.
