### ISSUE TITLE
[Feature Request] Wrap code at line

### ISSUE THREAD

**Issue by Panda-Sharp** [codecadwallader/codemaid#814]
### Environment
- Visual Studio version: 2019
- CodeMaid version: 11.2.231
- Code language: C#

### Description
Would be really nice to have an option, like for the comments, to wrap the code at column X
Like [Resharper](https://www.jetbrains.com/help/resharper/Reference__Options__Languages__CSharp__Formatting_Style__Line_Breaks_and_Wrapping.html)
Thanks!

P.S.
I searched in the extension and in the repo but I didn't find anything

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  I believe this is already captured in #640

**Comment by Panda-Sharp** [comment]
> Thanks for the suggestion. I believe this is already captured in #640

@codecadwallader thanks for your reply, I tried to search if there was a similar issue already, but I couldn't find it with my keywords :) You can close this one!
