### ISSUE TITLE
blazor project

### ISSUE THREAD

**Issue by drma-tech** [codecadwallader/codemaid#825]
support C# codes within the razor page of the blazor project. it works with the visual part, but not the code.

**Comment by codecadwallader** [comment]
Thanks for the suggestion.  There may be limitations on how much embedded code is exposed through the API compared to a standard code file (not sure).

**Comment by drma-tech** [comment]
well, I don't know that part. but maybe the new version of visual studio or blazor made it easier.

**Comment by drma-tech** [comment]
@codecadwallader  is it possible today?

**Comment by codecadwallader** [comment]
I'm not sure, I've unfortunately been having a lot of difficulty with the VS2022 debugger for extensions.

**Comment by drma-tech** [comment]
@codecadwallader  what exactly needs to be accessed for this to work? I'm going to open a ticket to microsoft so they can see this.

**Comment by drma-tech** [comment]
@codecadwallader
