### ISSUE TITLE
Out of memory exception with large files (e.g. 3500 lines)

### ISSUE THREAD

**Issue by gdosborne** [codecadwallader/codemaid#83]
Get out of memory exception when processing a file (@3500 lines). This file will run most of the time but occationally get the out of memory exception

CodeMaid Handled Exception 11:28:51 AM] Unable to build code model for 'C:\_Main\_Web\_OptiRampWeb\_OptiRampWeb\OptiRampWeb\VirtualTagServerConfig\Views\VTSHomeView.cs': System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.EditPoint.FindPattern(String Pattern, Int32 vsFindOptionsValue, EditPoint& EndPoint, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.FindMatches(TextDocument textDocument, String patternString)
   at SteveCadwallader.CodeMaid.Model.CodeModelHelper.RetrieveCodeRegions(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Model.CodeModelBuilder.RetrieveAllCodeItems(Document document)
   at SteveCadwallader.CodeMaid.Model.CodeModelManager.BuildCodeItems(CodeModel codeModel)
[CodeMaid Handled Exception 11:28:52 AM] Stopped cleaning 'VTSHomeView.cs': System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CtorCharArray(Char[] value)
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
   at Microsoft.VisualStudio.Text.SnapshotSpan.GetText()
   at Microsoft.VisualStudio.Editor.Implementation.TextDocData.GetLineText(Int32 iStartLine, Int32 iStartIndex, Int32 iEndLine, Int32 iEndIndex, String& pbstrBuf)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.GetSpanText(TextSpan span)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.FindInSpan(TextAddress beginAddr, TextAddress endAddr)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.DoFind(__VSFINDHOW grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.Find(UInt32 grfFindHow, TextSpan[] ptsMatch, UInt32& pgrfResult)
   at EnvDTE.TextDocument.ReplacePattern(String Pattern, String Replace, Int32 vsFindOptionsValue, TextRanges& Tags)
   at SteveCadwallader.CodeMaid.Helpers.TextDocumentHelper.SubstituteAllStringMatches(TextDocument textDocument, String patternString, String replacementString)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.RemoveWhitespaceLogic.RemoveEOLWhitespace(TextDocument textDocument)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.RunCodeCleanupCSharp(Document document, Boolean isAutoSave)
   at SteveCadwallader.CodeMaid.Logic.Cleaning.CodeCleanupManager.<>c__DisplayClassb.<Cleanup>b__9()
   at SteveCadwallader.CodeMaid.Helpers.UndoTransactionHelper.Run(Func`1 undoConditions, Action tryAction, Action`1 catchAction)

**Comment by codecadwallader** [comment]
Can you provide a sample file and some machine specs?  We have tested files exceeding 10,000 lines,  and it definitely does cause a temporary spike of memory consumption.

**Comment by gdosborne** [comment]
Will provide on Monday when I get to work

**Comment by codecadwallader** [comment]
I've done some analysis with a 5,000 line file and utilizing the ANTS Memory Profiler.  Similar to the v0.7.0 release, I can still confirm that CodeMaid has zero object growth during cleanup.

I did however find a large amount of growth that can be traced back to Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder.  This an internal MS class that I was unable to decompile or find any insights into as the Visual Studio API's are wrapped through COM.  Unfortunately what I think is happening is a memory leak inside the MS code based on the TextDocument.ReplacePattern calls that CodeMaid is invoking.  As more and more invocations occur, the growth continues.  I could be wrong, but that's what I'm interpreting from the ANTS reports.

In the future (VS2015+) the COM APIs go away and CodeMaid can utilize Roslyn which may bypass the issue.

Open to suggestions/ideas in the interim.

**Comment by gdosborne** [comment]
Windows 8.1 32 bit running in VMWare Player 7.1
4 GB allocated to vm
i5 Processor

Please provide email to send file if you still need it

VS Info pasted below:

***************************
Microsoft Visual Studio Professional 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51641

Installed Version: Professional

LightSwitch for Visual Studio 2013   06177-179-2532583-02274
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06177-179-2532583-02274
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-179-2532583-02274
Microsoft Visual Basic 2013

Visual C# 2013   06177-179-2532583-02274
Microsoft Visual C# 2013

Visual C++ 2013   06177-179-2532583-02274
Microsoft Visual C++ 2013

Visual F# 2013   06177-179-2532583-02274
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-179-2532583-02274
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06177-179-2532583-02274
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   12.4.51016.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

CodeMaid   #114
CodeMaid is an open source Visual Studio extension to cleanup, dig through and simplify our C#, C++, F#, VB, PHP, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Written by Steve Cadwallader, for more information visit http://www.codemaid.net/

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   4.9.14262.0
GhostDoc automatically generates XML documentation comments.

Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

NestIn   1.0
Nest an item inside another item in the solution explorer.

NuGet Package Manager   2.8.50926.663
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.30626
Microsoft Office Developer Tools for Visual Studio 2013 ENU

PowerShell Tools   1.3
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Snippet Designer   1.3.1
Snippet Designer is a Visual Studio plug in which allows you to create and search for snippets inside the IDE

Snippetizer   1.0
Information about my package

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

Text Macros for Visual Studio 2012/2013   1.4
Brings back text-editing macro support in Visual Studio 2012/2013

VisualHG   1.1.6
Mercurial source contol provider.

VSCommands for Visual Studio 2013   12.0
VSCommands for Visual Studio 2013

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by codecadwallader** [comment]
Thanks for the details.  See previous comment https://github.com/codecadwallader/codemaid/issues/83#issuecomment-84375747

**Comment by xmedeko** [comment]
*In the future (VS2015+) the COM APIs go away and CodeMaid can utilize Roslyn which may bypass the issue.*

Can you fix this issue for VS2015? Thanks.

**Comment by codecadwallader** [comment]
@xmedeko Roslyn support is going to be a massive architectural rewrite for CodeMaid.  It's absolutely something we want to do, but it will take a long time to accomplish and has implications for backwards support to VS2012 and VS2013.

**Comment by xmedeko** [comment]
Even big architectural rewrites are sometimes possible to do incrementally, e.g. see [Branch by Abstraction technique](http://martinfowler.com/bliki/BranchByAbstraction.html). (The name is misleading, it's not git branching, but a way to to big rewrites without git branching.)

So maybe it would be possible to create some layer, which call the Roslyn when used in VS2015, or the old COM API when used by older VS? The features for Roslyn (and the layer) could be implemented gradually, one by one, not all at once.

This is a general advice, though. I do not know if it fits to the CodeMain code, too.

**Comment by rainbowdesign** [comment]
I have a file with 1500 lines and codemaid did crash one time and vs (2015) regularly hangs

**Comment by codecadwallader** [comment]
Are you getting an out of memory exception as this issue reports or is it something different?  One known issue that will be resolved with the next release is that enabling multi-threading performance (which is off by default) actually makes things worse for some users.  See #212 for details

**Comment by codecadwallader** [comment]
Glad to hear it.

**Comment by codecadwallader** [comment]
Closing issue as OP believes it is resolved by changes made for #212

**Comment by rainbowdesign** [comment]
I also have a file with about 3500 lines and its a bit frustrating that the spade needs 20 seconds now to refresh. maybe there is a way to tweak the spade refreshing (without porting to the new api)?
I think to improve performance might also make codemaid generally more robust

**Comment by codecadwallader** [comment]
I've taken a look and optimized performance in the past.. always happy to have a fresh set of eyes/hands see if there's more that can be done!

**Comment by rainbowdesign** [comment]
You suggest i look on your code?

Well there is one more problem here: when it loads so long(20 seconds or more) the spade sometimes is blank afterwards.

**Comment by yyjdelete** [comment]
Found `Microsoft.VisualStudio.PlatformUI.RegexFinder.VsRegexFinder` leak with CodeMaid's clean again in Visual Studio 2017 version 15.3.0 Preview 4.
Maybe a issue of VS Preview since not happened in old versions, and will reported to MS latter.

**Comment by TobiasKnauss** [comment]
@yyjdelete The issue on VS developer community that you mentioned was closed and seems not to be reopened again.
@codecadwallader I have told MS in the mentioned issue, that the issue still persists. Recently MS has become much more communicative and they seem to care much more about the users' requests. You may want to open another issue at their page (as they suggested), because you know all the details about the problem. I think they may look into it now.
Currently I don't use CodeMaid because of that bug.
