### ISSUE TITLE
Disable new line after Attribute

### ISSUE THREAD

**Issue by Mythique** [codecadwallader/codemaid#831]
### Environment
- Visual Studio version: 2019 (16.11.0)
- CodeMaid version: 11.2
- Code language: C#

### Description

A new line is added between a member with an attribute and the next member.

Here is what happen after a CodeMaid clean up :

![image](https://user-images.githubusercontent.com/4488088/129361301-02081764-e99b-41da-b940-40a869cbdcd9.png)

Here is what I want to have : 

![image](https://user-images.githubusercontent.com/4488088/129361349-360fee48-f7c4-47fd-908e-b198c33c8cb0.png)

Unfortunately I can't find the option to disable this in CodeMaid. At first I thought it was Visual Studio formatting, but disabling "Run format document" doesn't change the behaviour.

Where can I find the rule regarding my issue?

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I believe the option you want to toggle is at CodeMaid->Options->Cleaning->Insert->Insert blank lines after multi-line fields.

**Comment by Mythique** [comment]
> Thanks for reporting the issue. I believe the option you want to toggle is at CodeMaid->Options->Cleaning->Insert->Insert blank lines after multi-line fields.

Thank you, it was the correct option!
