### ISSUE TITLE
parsing \wwwroot\libs - unrecognized escape sequence

### ISSUE THREAD

**Issue by nankingcigar** [codecadwallader/codemaid#838]
### Environment
- Visual Studio version: 2019 Enterprise
- CodeMaid version: 11.2
- Code language: C#

### Description
parsing \wwwroot\libs - unrecognized escape sequence

### Steps to recreate
1. use CodeMaid 

### Current behavior
popup error parsing \wwwroot\libs - unrecognized escape sequence

### Expected behavior
format curent C# code file

**Comment by nankingcigar** [comment]
Reset code maid setting fix it.

**Comment by codecadwallader** [comment]
Cool, glad you got it fixed.  What I suspect happened was that `\wwwroot\libs` was in one of the file path settings that expect a regular expression like `\\wwwroot\\libs`
