### ISSUE TITLE
Error occurs every time closing Visual Studio 2013

### ISSUE THREAD

**Issue by renkun-ken** [codecadwallader/codemaid#84]
When CodeMaid v0.7.6 is enabled, every time I close Visual Studio 2013 an error message box appears saying *Visual Studio has encountered an unexpected error*.

As long as I disable CodeMaid, the error will not occur.

**Comment by codecadwallader** [comment]
Sorry to hear it, some questions:

1.  If you open Visual Studio, and close it without taking any actions (e.g. not opening any solutions), does the error still happen?
2.  If you enable CodeMaid's diagnostic mode (CodeMaid->Configuration->"Diagnostics mode" at the bottom) and open the Output window - are any details shown when the error occurs?
3.  What other extensions do you have installed?
4.  Have you tried uninstalling and reinstalling CodeMaid?
5.  Try having Visual Studio force a re-merge of all packages at a command line with "devenv /setup"

**Comment by renkun-ken** [comment]
Thanks for you reply!

1. No error occurs if I do nothing (not loading any solution) between open and close.
2. In diagnostic mode, the output looks pretty normal. All messages are about raised events and invoked methods. More exactly, it is closing a solution that triggers the error message box, but the output only shows that `[CodeMaid Diagnostic 06:06:05 PM] SolutionEventListener.OnSolutionClosed raised`.
3. All other extensions are installed along with VS2013 community, e.g. NuGet Manager, they cannot be disabled or uninstalled from the extension manager.
4. I tried but it does not work, all the same.
5. I tried but it does not work, all the same.

**Comment by codecadwallader** [comment]
Thanks for trying those things.  A couple other suggestions:

6.  On solution closed, by default we try to show the start page again.  Try disabling CodeMaid->Configuration->"Show start page when a solution is closed"
7.  Does it always happen with the same solution?  If you create a new project, and close it right away - does the same error still occur?

**Comment by renkun-ken** [comment]
I open two very simple projects and when I close the solutions the error does not occur at all.

I open the error-making solution and close all editor tabs, then no error occurs when I close the solution. If any editor is open when I close the solution, the error will occur. It happens with all types of editors, e.g. C# code editor, XML editor, Form designer.

The same thing does not happen with other solutions.

Then I tried disabling *Show start page when a solution is closed* and the error is magically gone! Thanks for your suggestions! Still don't have a clue about it.

**Comment by codecadwallader** [comment]
That is strange behavior.. but if it's not bothering you anymore yeah we'll close it for now.  Thanks for the details working through it.

**Comment by modyskyline** [comment]
i got this error when installing code Maid , and i dont know why

Searching for applicable products...
Found installed product - Microsoft Visual C++ Express 2010
Found installed product - Microsoft Visual Studio Express 2013 for Windows Desktop
Found installed product - Global Location
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by codecadwallader** [comment]
@modyskyline Please open a separate issue for further help with some additional information shown in the template (e.g. CodeMaid version).
