### ISSUE TITLE
VS2022 Link is dead

### ISSUE THREAD

**Issue by adam-bentley** [codecadwallader/codemaid#857]
The current link found on 
https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid
has a link to the 2022 version. This link doesn't work. I am also not able to find it in the VS2022 Extension manager.

**Comment by codecadwallader** [comment]
I think I just fixed it, sorry about that!

**Comment by helptiger** [comment]
![Bildschirmfoto 2021-11-08 um 20 28 30](https://user-images.githubusercontent.com/10258902/140805329-84cd9200-50c1-497b-a01e-66c71e412612.png)
fixed!

**Comment by adam-bentley** [comment]
Awesome! Thanks :)
