### ISSUE TITLE
v12.0 is not work in vs2019 enterprise

### ISSUE THREAD

**Issue by shelllee** [codecadwallader/codemaid#865]
### Environment
- Visual Studio version: [2019 Enterprise]
- CodeMaid version: [12.0]
- Code language: [C#]

### Description
Load Error

```
  <entry>
    <record>3474</record>
    <time>2021/11/10 03:10:01.638</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CodeMaidPackage]Source: &aposSteveCadwallader.CodeMaid&apos Description: 未能加载文件或程序集“Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
System.IO.FileNotFoundException: 未能加载文件或程序集“Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。
文件名:“Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”
   在 SteveCadwallader.CodeMaid.CodeMaidPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
   在 Microsoft.VisualStudio.Shell.AsyncPackage.&lt&gtc__DisplayClass20_0.&lt&ltMicrosoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gtb__1&gtd.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   在 Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   在 Microsoft.VisualStudio.Services.VsTask.GetResult()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。
</description>
...
  </entry>
```

### Steps to recreate
1. once on opened vs

### Current behavior
emmm

### Expected behavior
emmm

**Comment by vikong** [comment]
In Visual Studio Community 2019 too.

**Comment by eduinovace** [comment]
Same here with visual studio community 2019 version 16.9.4 
This is the activity log:

`<entry>
    <record>2585</record>
    <time>2021/11/10 08:33:16.302</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CodeMaidPackage]</description>
    <guid>{4C82E17D-927E-42D2-8460-B473AC7DF316}</guid>
  </entry>
  <entry>
    <record>2586</record>
    <time>2021/11/10 08:33:16.312</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [CodeMaidPackage]Source: &apos;SteveCadwallader.CodeMaid&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. El sistema no puede encontrar el archivo especificado.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. El sistema no puede encontrar el archivo especificado.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at SteveCadwallader.CodeMaid.CodeMaidPackage.InitializeAsync(CancellationToken cancellationToken, IProgress1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;AVS: El registro del enlace de ensamblado est&#x00E1; desactivado.&#x000D;&#x000A;Para habilitar el registro de errores del enlace de ensamblado, establezca el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.&#x000D;&#x000A;Nota: existe una disminuci&#x00F3;n del rendimiento asociada registro de errores del enlace de ensamblado.&#x000D;&#x000A;Para desactivar esta caracter&#x00ED;stica, elimine el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{4C82E17D-927E-42D2-8460-B473AC7DF316}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>2587</record>
    <time>2021/11/10 08:33:16.313</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CodeMaidPackage]</description>
    <guid>{4C82E17D-927E-42D2-8460-B473AC7DF316}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>`
  
  And the error in visual studio:

![image](https://user-images.githubusercontent.com/93317224/141078315-850707ca-1cc6-42ea-9320-103185bc78f2.png)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I saw someone mention in another issue that upgrading VS2019 to the latest (v16.11) helped them.  Can you give that a try?

**Comment by rickblack** [comment]
> 
> 
> Thanks for reporting the issue. I saw someone mention in another issue that upgrading VS2019 to the latest (v16.11) helped them. Can you give that a try?

Confirming that this worked for me. Went from 16.8.3 to 16.11.6 and I no longer receive this error.

**Comment by vikong** [comment]
The update VS2019 to 16.11 helped me too.

**Comment by shelllee** [comment]
My problem resolved too.

**Comment by shelllee** [comment]
Update VS2019 version to latest should be help.
