### ISSUE TITLE
CodeMaid reorders static new to new static

### ISSUE THREAD

**Issue by codingdave** [codecadwallader/codemaid#867]
### Environment
- Visual Studio version: 2019 Professional
- CodeMaid version: 12.0
- Code language: C#

### Description
Codemaid reoders static new to new static and such conflicts with the microsoft recommendation, default, analyzer and .editorconfig.

### Steps to recreate
Reformat

    public static new App Current => (App)Application.Current;

and CodeMaid will change it to 

    public new static App Current => (App)Application.Current;

### Current behavior
The resort conflicts with the microsoft recommendation, default, analyzer and .editorconfig. So after codemaid is done the analyzer suggest a change in the document pointing to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036.

### Expected behavior
The order should follow Microsofts recommendation.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I am able to reproduce it.

As a workaround you can disable inserting explicit access modifiers on properties at CodeMaid->Options->Cleaning->Insert->Insert explicit access modifiers on->properties.

The way that functionality works is it attempts to set the access modifier if it is not detected.  If the access modifier is already present this is expected to be a no-op, but if it is not present the IDE will insert the access modifier.  It appears this behavior is no longer safe to call as it is having an unexpected side effect (re-ordering other parts of the definition).

**Comment by BlythMeister** [comment]
I have also seen this behaviour on methods (disabling on methods "fixes" this too.

**Comment by BlythMeister** [comment]
Have narrowed this down to this function: https://github.com/codecadwallader/codemaid/blob/83c554d586425b4cdd3906d4d9b71a8f376a4e34/CodeMaidShared/Helpers/TextDocumentHelper.cs#L154-L172

It would appear that it loads the entire file and then searches for the bit with the character (rather than starting at the line/character for which the start position is relevant.

In an older version pre VS2022 support, this function was very different:

```
        internal static string GetTextToFirstMatch(TextPoint startPoint, string matchString)
        {
            var startEditPoint = startPoint.CreateEditPoint();
            var endEditPoint = startEditPoint.CreateEditPoint();
            TextRanges subGroupMatches = null; // Not used - required for FindPattern.

            if (endEditPoint.FindPattern(matchString, StandardFindOptions, ref endEditPoint, ref subGroupMatches))
            {
                return startEditPoint.GetText(endEditPoint);
            }

            return null;
        }
```
and did seem to use the start point.

**Comment by codecadwallader** [comment]
Thank you very much @BlythMeister for chasing this down.  That file did undergo a lot of changes with VS2022 and I agree that methods looks suspiciously incorrect.  I'm reviewing the PR.
