### ISSUE TITLE
Cleanup duplicates reinsert statement

### ISSUE THREAD

**Issue by sm-g** [codecadwallader/codemaid#87]
Reinsert this after cleanup:
```cs
using System;
using Diagnosis.Common;
```

Test file:
```cs
using Diagnosis.Common;
using System;
namespace Diagnosis.Models
{
    internal class Class1 : EntityBase<Guid>
    {
    }
}
```
Become:
```cs
using Diagnosis.Common;
using System;

using System;

namespace Diagnosis.Models
{
    internal class Class1 : EntityBase<Guid>
    {
    }
}
```

**Comment by codecadwallader** [comment]
Thanks for reporting the issue, I have reproduced it.

As a workaround in the meantime, putting the using statements in alphabetical order did not appear to exhibit the issue.

**Comment by codecadwallader** [comment]
A fix has been checked in for this issue.  It will be present in the next release (v0.7.6.1 beta)

**Comment by codecadwallader** [comment]
The v0.7.6.1 beta has been published with this fix.  Please give it a shot and comment to let me know how it goes.  Closing the issue.

**Comment by sm-g** [comment]
No duplicating now, but empty line appears here (when reinsert both of namespaces):

```cs
using System;
using System.Linq;

namespace Entities
{
    internal class Class1
    {
    }
}
```

**Comment by codecadwallader** [comment]
Correct.  If you don't want that behavior, then you'll want to disable the settings at CodeMaid->Configuration->Insert for "Insert blank line padding before namespaces" and "Insert blank line padding after using statement blocks"

**Comment by sm-g** [comment]
Line between namespaces:

```cs
using System;

using System.Linq;
```

**Comment by codecadwallader** [comment]
I looked at this further, but there wasn't a clean way to improve the potential for whitespace to be introduced with the current string matching approach we're using.  In the future, with the Roslyn compiler, we'll be able to switch the implementation over to a more accurate model that can better handle this scenario.
