### ISSUE TITLE
Razor pages are not cleaned up

### ISSUE THREAD

**Issue by scetu** [codecadwallader/codemaid#880]
### Environment
- Visual Studio version: 2022 Community
- CodeMaid version: 12.0.308
- Code language: ASP.NET Razor Pages

### Description
Document cleanup is not working in `.cshtml` file, but works in `.cs` files,

### Steps to recreate
1. Create new project for ASP.NET Core Web App
2. Edit any `.cshtml` page (I've done Index)
3. Try to cleanup active document with Codemaid
4. Nothing happens

### Current behavior
`.cshtml` files are not cleaned up when running Codemaid, but `.cs` files work just fine. This worked in Visual Studio Community 2019 maybe related to issue [#876](https://github.com/codecadwallader/codemaid/issues/876)?

### Expected behavior
`.cshtml` should be cleaned up.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue and doing the research to cross link it.  I am able to reproduce it as well and indeed it is the same issue just with a different language type to add to the enumeration.  Previously it was reported as HTML but now there's a specific Razor option. This is an easy fix and it will be present in the next release.

If you want to try the CI build it will be available at https://www.vsixgallery.com/extension/9079e73d-3fbb-4e07-8dab-f44fa5d8e8b5 shortly.

**Comment by scetu** [comment]
Thank you! Can confirm it is working now. Now just wait for MS to fix IntelliSense in `.cshtml` files, and I will maybe start to use VS2022 again.

**Comment by twojnarowski** [comment]
I can confirm, downloading and installing the 12.0.333 version makes CodeMaid clean up .razor and .cshtml files. Any news on when this will be released as a an official version?

**Comment by codecadwallader** [comment]
Thanks for confirming.  I don't currently have a date set for an official version but will consider it.

**Comment by Number6UK** [comment]
Have just encountered this problem myself with the 12.0.300 release, which is the latest available in the VS Extension Manager (as CodeMaid VS2022).

The the vsixgallery URL mentioned above no longer works. Could the fix be pushed to the official release if possible?
Thanks
