### ISSUE TITLE
Code Cleanup not working in .cshtml files in VS 2022

### ISSUE THREAD

**Issue by paulmeidinger** [codecadwallader/codemaid#891]
### Environment
- Visual Studio version: 2022 Community version 17.0.4
- CodeMaid version: 12.0
- Code language: Razor/HTML

### Description
Cleanup Active Document does not work in a .cshtml file in an ASP.NET Core Web App project.

### Steps to recreate
1. Create a new ASP.NET Core Web App project
2. Open Index.cshtml and make changes that should be cleaned up, such as multiple empty lines at the end of the file
3. Use the Cleanup Active Document command
4. Try the same procedure in the associated .cshtml.cs file

### Current behavior
The .cshtml file is not cleaned up, but the associated .cshtml.cs file is.

### Expected behavior
The .cshtml file should be cleaned up. This works fine in VS 2019.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I believe we already have a fix for this in #880 which will be present in the next release or is available today in the CI builds.  Hope it helps!
