### ISSUE TITLE
CodeMaid remove #endif when use [Obsolete] in #if...#endif

### ISSUE THREAD

**Issue by chechy** [codecadwallader/codemaid#895]
### Environment
- Visual Studio version: [example 2022 Community]
- CodeMaid version: [example 12.0]
- Code language: [example C#]

### Description
when cs code file contains #if NET6_0 [Obsolete] #endif , after save, CodeMaid will remove #endif , this will cause compiler doesnot compile code.

### Steps to recreate
any code, when write this 
#if NET6_0
        [Obsolete]
#endif
save this file (auto run CodeMaid)，#endif will be removed

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  We are aware of it and working on it with Microsoft (bug introduced in latest SDK).  See #879 for more details

**Comment by chechy** [comment]
Thanks, to disable methods can avoid it.
