### ISSUE TITLE
Support for VS Code? 

### ISSUE THREAD

**Issue by fabilo-au** [codecadwallader/codemaid#896]
### Environment
- Visual Studio **Code** version: [1.62.3]
- CodeMaid version: [12.0.300]
- Code language: [nodeJS]

### Description
I cannot get this extension to install for VS Code. I'm assuming it's only supported for VS? If so, is there a chance to get it ported to VS Code? 

### Steps to recreate
1. Download package from: https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid
2. Attempt install via cli: 
`code --install-extension CodeMaid.VS2019.v12.0.300.vsix
Installing extensions...
extension/package.json not found inside zip.
Failed Installing Extensions: file:///home/fabilo/Downloads/CodeMaid.VS2019.v12.0.300.vsix`

### Current behavior
CLI install result: `Failed Installing Extensions: file:///home/fabilo/Downloads/CodeMaid.VS2019.v12.0.300.vsix`

### Expected behavior
Hopefully install in VS Code :)

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Unfortunately you are correct, it is only available for Visual Studio.  There is an issue about adding VSCode support here: #273
