### ISSUE TITLE
CodeMaid does not work as expected with conditional compiler directives 

### ISSUE THREAD

**Issue by rmaclean** [codecadwallader/codemaid#9]
CodeMaid appears to ignore conditional compiler directives outside of methods and could move methods out of or into a conditional compiler directive. This could cause code to break. 
Not sure if there is a good fix for this (there are loads of edge cases), but maybe a warning if CM finds this and informs the user that it may break and lets them choose to continue with that refactoring.

Example, in the image below the Debug method is moved outside of the conditional compiler directives when CM cleans it up.

![clipboard01](https://cloud.githubusercontent.com/assets/1232733/3905894/671d01a2-22ed-11e4-9204-d5e4b624d7c7.jpg)

Sample code from image above:

``` c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
#if DEBUG
            Debug();
#endif
            Always();
        }

#if DEBUG
        private static void Debug()
        {
            Console.WriteLine("BUGS");
        }
#endif

        public static void Always()
        {
            Console.WriteLine("Defect free code");
        }


    }
}
```

**Comment by SovietSam** [comment]
I don't know is it the same issue, but in my case CodeMaid doesn't reorganize or clear file with conditional compiler directives inside methods at all. Was this issue fixed?

**Comment by codecadwallader** [comment]
We deliberately disabled reorganization for any files that contained preprocessor directives, so that is expected behavior.  More details on the Trello card referenced above: https://trello.com/c/Qqd0GLqI

**Comment by GondilOndro** [comment]
I know this is veeery old topic and closed but,,, As I understood CodeMaid should completely ignore files which contain preprocessor directives as e.g. #if. Is this behavior still the same because this is not working for me with CodeMaid 11.1. It completely mess up my code now.

**Comment by codecadwallader** [comment]
@GondilOndro CodeMaid has an option to configure if it always does the cleanup, asks about the cleanup, or always ignores the cleanup.  The default is to ask the user (pop a prompt dialog) but if that option has been changed that may explain why you are not seeing the prompt.  It can be found at CodeMaid->Options->Reorganize->General

![image](https://user-images.githubusercontent.com/3823772/72220386-0c63b580-3548-11ea-868e-293ae45d473d.png)

**Comment by GondilOndro** [comment]
@codecadwallader thank you that is what I was looking for. I had it set to Yes by team settings.

**Comment by Crono1981** [comment]
I'm using 11.1 and still having issues with CodeMaid and preprocessor directives, despite having explicitly set "perform reorganization when processor conditionals are present" setting to "no".

My code:

```cs

        /// <summary>
        /// Gets the current object's data fields.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
#if NETFX || NETSTANDARD1_4_AND_UP
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
#endif
        public IReadOnlyCollection<SqlColumnDescriptor> Fields => Columns;


```

Running cleanup removes the preprocessor block altogether. :|

If I do it this way instead:

```cs
        /// <summary>
        /// Gets the current object's data fields.
        /// </summary>
#if NETFX || NETSTANDARD1_4_AND_UP
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
#else
        [EditorBrowsable(EditorBrowsableState.Never)]
#endif
        public IReadOnlyCollection<SqlColumnDescriptor> Fields => Columns;

```

... then cleanup will remove the line with `#endif` and resulting code won't compile.

The best workaround I've found is to write it like this:

```cs
#if NETFX || NETSTANDARD1_4_AND_UP
        /// <summary>
        /// Gets the current object's data fields.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public IReadOnlyCollection<SqlColumnDescriptor> Fields => Columns;
#else
        /// <summary>
        /// Gets the current object's data fields.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public IReadOnlyCollection<SqlColumnDescriptor> Fields => Columns;
#endif
```

Cleanup will then add a blank line right after `#else` and right before `#endif`, but at least code will still compile.

I tried disabling automatic code reorganization on cleanup but that didn't work either. I'm not sure at this point if it has anything to do with reorganizing at all.

Hope it helps @codecadwallader fixing this, or at least help somebody else in a similar situation looking for a workaround.

**Comment by codecadwallader** [comment]
@Crono1981 Thanks for providing the examples.  I am able to reproduce the issue with your scenario.  It's actually an odd issue with the insert explicit access modifier logic.  We're not correctly detecting the presence of the `public` access modifier in some cases with expression bodied members and so we attempt to set it with the IDE.  While this should(tm) be a no-op (set it to the value it already is) it actually causes the IDE to rewrite the element and I suspect inactive #pragma statements get wiped out in the process.  There is a different issue with the same root cause here: #708 

As a workaround if you disable insertion of explicit access modifiers on properties that would avoid the bug.  Also the workaround you provided where the pragma statements are pulled out of the property definition indeed avoids the bug too.

**Comment by Crono1981** [comment]
Thanks @codecadwallader .

Can I assume that not using expression bodied members would also do the trick? I would gladly go back to using block bodied methods if it means I can still specify the access modifier and not having to duplicate my documentation. Especially if it's just in the very rare cases I want different attribute decorators depending on compiler target. :)

**Comment by codecadwallader** [comment]
@Crono1981 I believe that workaround will work too.  I did a quick test and it seemed to work for me.

**Comment by msgallagher** [comment]
@codecadwallader: I am having this issue again with version 12.0 in visual studio 2022. Do you need an example to reproduce? I had to add my file to the exclude list because none of the workarounds worked :/.

**Comment by codecadwallader** [comment]
@msgallagher I attempted to reproduce it with VS2022 + CodeMaid 12.0 and did not see the issue.  Yes if you can please provide an example that would help to see if I can reproduce it with that code.  Otherwise that may point to a configuration (vs. code) issue.

**Comment by msgallagher** [comment]
> @msgallagher I attempted to reproduce it with VS2022 + CodeMaid 12.0 and did not see the issue. Yes if you can please provide an example that would help to see if I can reproduce it with that code. Otherwise that may point to a configuration (vs. code) issue.

@codecadwallader  - here's the example:

before saving with codemaid:
```
//#define RUN_AZURITE_DEPENDENT_TESTS // uncomment this line if you'd like to run azurite dependent unit tests.
#if RUN_AZURITE_DEPENDENT_TESTS
    [Fact]
#else
    [Fact(Skip = "test only works with azurite running locally")]
#endif
```

after saving with codemaid:

```
#if RUN_AZURITE_DEPENDENT_TESTS
    [Fact]
#else

    [Fact(Skip = "test only works with azurite running locally")]
```

**Comment by codecadwallader** [comment]
Thanks for the code sample.  I am still unable to reproduce it with that example.  Can you include your CodeMaid.config and if possible a minimal solution that exhibits the issue?
