### ISSUE TITLE
Hyperlink in xml doc is formatted incorrectly

### ISSUE THREAD

**Issue by wangzq** [codecadwallader/codemaid#90]
To reproduce, simply type in following xml doc:

    /// <summary>
    /// http://foo
    /// </summary>

After formatting comment it will become:

    /// <summary>
    /// http: //foo
    /// </summary>

**Comment by willemduncan** [comment]
I can confirm this problem, have not had time to check the fix yet.

**Comment by codecadwallader** [comment]
Fix looks logical to me, but will defer to Willem to confirm.

**Comment by willemduncan** [comment]
Added unit tests and fix for this issue, pending the next pull request.
