### ISSUE TITLE
Error when attempting to open settings page.

### ISSUE THREAD

**Issue by Devilcow** [codecadwallader/codemaid#915]
### Environment
- Visual Studio version: VisualStudio 2019 Community 
- CodeMaid version: 12.0
- Code language: C#

### Description
When I try to open the settings page for CodeMaid from the "Extensions" menu item, I get an error "The 'ResourceAssembly' property of the 'Application' type cannot be changed after it has been set."

### Steps to recreate
1. Install latest version of CodeMaid 12.0 at the time of this entry.
2. Select 'Extensions->CodeMaid->Options'
3. I have seen this from trying to select 'Extensions->CodeMaid->About' as well,

### Current behavior
Some of the functionality seems to work form the 'Extensions' menu, but others are throwing exceptions as well. 

### Expected behavior
The options and settings dialog should be displayed.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Some other users have seen this too and it usually is tied to conflicts with other extensions and a mandatory change to extensions that was recently made in the SDK.  Please see #873 or #906 for some more information and workarounds.

**Comment by Devilcow** [comment]
Ahh I see, Thanks! I have just configured CodeMaid with no solution loaded, and will try running it's actions alone on my project. If that doesn't work I'll just ditch SuperCharger since that seems to be what is causing the issue from the posts I read. 
Thanks again! and thanks for such a handy tool!

Cheers!
