### ISSUE TITLE
CodeMaid + CoPilot = Frequent Crashing of Visual Studio 2022

### ISSUE THREAD

**Issue by Vastlee** [codecadwallader/codemaid#918]
### Environment
- Visual Studio version: 2022 Community
- CodeMaid version: 12.0.300
- Code language: C#

### Description
After installing CoPilot, several times per hour when CoPilot tries to make a suggestion, Visual Studio crashes. I can disable CodeMaid and the crashes stop. I can also disable CoPilot & the crashes stop.

### Steps to recreate
1. Install CoPilot & CodeMaid into Visual Studio
2. Start typing code that CoPilot will predict
3. Visual Studio Crashes & Shuts Down

### Current behavior
Crashes & closed Visual Studio

### Expected behavior
Allowing predictions without crashing.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  Do you have any other information or metrics that may be helpful in diagnosis?  My best guess without any other information would be running out of memory.  To check that it could be useful to open the Task Manager and see what is happening when VS crashes.

**Comment by AbstractEyes** [comment]
![image](https://user-images.githubusercontent.com/71285049/174944466-8b54ed7b-a80c-463d-9b8d-dc48bd2b7390.png)
