### ISSUE TITLE
VS 2013 Update4 and TypeScript 1.4 - CodeMaid Spade not showing anything

### ISSUE THREAD

**Issue by squadwuschel** [codecadwallader/codemaid#92]
Hello,

I've installed Newest CodeMaid Version for VS 2013 Update 4 and I've installed TypeScript 1.4 and I would use the CodeMaid Spade to show the current functions and classes, but there is nothing shown when I use it on TpyeScript files is that right ?

**Comment by codecadwallader** [comment]
Correct, unfortunately the Visual Studio API does not expose a model for TypeScript/JavaScript files that we can use for building up the Spade view.  That is currently limited to C#, C++ and VB.
