### ISSUE TITLE
.cshtml razor files are not being formatted when using Clean Up Active Document

### ISSUE THREAD

**Issue by rippo** [codecadwallader/codemaid#921]
I have just downloaded a new version VS2022 and codemaid. I have not downloaded VS2022 before today

### Environment
- Visual Studio version: 2022 Community
- CodeMaid version: 12.0
- Code language: .CSHTML

### Steps to recreate
Open a Razor cshtml page add some blank lines and choose `Clean Up Active Document`

### Current behavior
it appears `.cshtml` RAZOR files are not being formatted when using `Clean Up Active Document`

I have seen this issue and am wondering if it has resurfaced? https://github.com/codecadwallader/codemaid/issues/891 

This works in vs2019 fine

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  This is actually the same issue the fix just hasn't been deployed yet.  We've been dragging feet for a release waiting on some SDK issues to get resolved.  The other issue does link to a CI build that can be used in the interim.

**Comment by rippo** [comment]
Thanks, downloaded from https://www.vsixgallery.com/extension/9079e73d-3fbb-4e07-8dab-f44fa5d8e8b5 and can confirm it all works. Will close
