### ISSUE TITLE
Add Option to Remove Comments

### ISSUE THREAD

**Issue by TheoConfidor** [codecadwallader/codemaid#93]
As a programmer working with large legacy code monster classes, I find that most of the comments in the files are outdated or wrong.

It would be useful to have a option to Delete/Remove all comments during cleanup of a file.

**Comment by codecadwallader** [comment]
There is an existing card in our backlog for this feature.  It hasn't been very popular (1 vote) but feel free to add your own and any other comments/thoughts to it here: https://trello.com/c/L8wrnJnm
