### ISSUE TITLE
Regions orders is inconsistent 

### ISSUE THREAD

**Issue by shytikov** [codecadwallader/codemaid#94]
I've cleaned up the file and currently have following structure of regions:

    namespace ManipulationTool
    {
        public partial class MainControl : PluginBase
        { 
            + Public Constructors
            + Public Properties
            + Public Methods
            + Private Methods
        }
    }

I've added new public function at the end of the MainControl class, like this:

    namespace ManipulationTool
    {
        public partial class MainControl : PluginBase
        { 
            + Public Constructors
            + Public Properties
            + Public Methods
            + Private Methods

            public void Test()
            {
            }
        }
    }
 
Running cleanup once again. After collapsing all regions I see following:

    namespace ManipulationTool
    {
        public partial class MainControl : PluginBase
        { 
            + Private Methods
            + Public Constructors
            + Public Properties
            + Public Methods
        }
    }

Please note, how `Public Methods` region is on a last place now, while Private methods are bubbled up to the top.

It looks like regions follows last entered code, even broking whole sequence of regions.

Interesting fact, that if I will run code clean up once again, the regions order will return to normal. 

            + Public Constructors
            + Public Properties
            + Public Methods
            + Private Methods

I'm using `CodeMaid` version `0.7.6`

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I have reproduced it and am taking a look.

**Comment by codecadwallader** [comment]
I found the source of the issue, and have a tentative fix.  I'm also adding some additional unit tests for this scenario going forwards.

**Comment by codecadwallader** [comment]
I've checked in the fix for this issue, and it will be present in the next release (v0.7.6.1 beta).

**Comment by codecadwallader** [comment]
The v0.7.6.1 beta has been published with this fix.  Please give it a shot and comment to let me know how it goes.  Closing the issue.

**Comment by shytikov** [comment]
It's working! Thank you!

**Comment by codecadwallader** [comment]
Cool, thanks for confirming and the clear bug report. :)
