### ISSUE TITLE
Is there a way to stop code from being pulled out of my regions when I use CodeMaid reorganize

### ISSUE THREAD

**Issue by ghd796** [codecadwallader/codemaid#941]
### Environment
- Visual Studio version: example 2022 Community
- CodeMaid version: 12.0
- Code language: example C#

### Description
Is there a way to stop code from being pulled out of my regions when I use CodeMaid reorganize

**Comment by codecadwallader** [comment]
Yes, there's an option called "Keep members within regions" which can be found in CodeMaid->Options->Reorganizing.  Hope it helps!

**Comment by ghd796** [comment]
> Yes, there's an option called "Keep members within regions" which can be found in CodeMaid->Options->Reorganizing. Hope it helps!
