### ISSUE TITLE
CodeMaid is not handling conditional compilation on 'Cleanup' document

### ISSUE THREAD

**Issue by phil000** [codecadwallader/codemaid#954]
### Environment
- Visual Studio version: **2022 Professional, 17.3.6**
- CodeMaid version: **12.0.300**
- Language: **C#**

### Description
CodeMaid is not handling conditional compilation on 'Cleanup' document.

### Current behavior
Shifts code about inappropriately.

### Expected behavior
Doesn't shift code about inappropriately.

e.g.
Start with:
```
	private const int MaximumInvoicesScheduleDays = 31;
#if (DEBUG)
	private const int MaximumInvoicesExtractDays = 99999;
#else
	// This will be the absolute maximum for extracting invoices
	private const int MaximumInvoicesExtractDays = 183;
#endif
```

**Perform cleanup.**

End up with:
```
	private const int MaximumInvoicesExtractDays = 99999;
	private const int MaximumInvoicesScheduleDays = 31;
#if (DEBUG)
#else
	// This will be the absolute maximum for extracting invoices
	private const int MaximumInvoicesExtractDays = 183;
#endif
```

**Comment by Protiguous** [comment]
Can you test if the `#if (DEBUG)` versus `#if DEBUG` makes a difference with CodeMaid?

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  By default CodeMaid detects preprocessor conditionals and prompts if you want to proceed with a reorganization.  When running a reorganization a box like this should(tm) pop up:

![image](https://user-images.githubusercontent.com/3823772/201104694-cb56a793-6c80-49c9-8c0c-0ac80d656f27.png)

If you're not seeing that prompt, can you check the setting at CodeMaid->Options->Reorganizing->General->Perform reorganization when preprocessor conditionals are present ?

**Comment by phil000** [comment]
Hello,
#if (DEBUG) versus #if DEBUG does the same thing.

That setting is turned on. 

The behavior is unpredictable, as this
```
#if DEBUG
	private int z = 5;
#endif
	private int x = 10;
	private int y = 100;
```

gets cleaned into this:
```
#if DEBUG
	private int x = 10;
	private int y = 100;
	private int z = 5;
#endif
```

**Comment by codecadwallader** [comment]
It sounds like the preprocessor directive detection is failing if you're not seeing the warning prompt.  Do you have a minimal solution that reproduces the issue that you can share?

**Comment by phil000** [comment]
Hi, Please close this case. 
I only raised this issue to see if preprocessor directives _could_ actually be handled better.
This file and most others we have do need to be cleaned, so we've altered the structure to remove preprocessor directives or place them in a file of their own.

**Comment by Pinox** [comment]
> It sounds like the preprocessor directive detection is failing if you're not seeing the warning prompt. Do you have a minimal solution that reproduces the issue that you can share?

I also see this issue.  Although my settings is set to "ask" there is no warning prompt so all conditional statements are reorganized all the time.

In my case it always deletes the " #endif "  statement.

![image](https://user-images.githubusercontent.com/5297255/232495654-dce2b672-a8b4-469a-8968-3df564345cab.png)

**Comment by codecadwallader** [comment]
Thanks for reporting Pinox.  Same ask as above, can you please provide a minimal solution that exhibits the issue?
