### ISSUE TITLE
Assembly attribute causes codemaid to enter infinite loop of saves.

### ISSUE THREAD

**Issue by CaidenKehrer** [codecadwallader/codemaid#955]
### Environment
- Visual Studio version: 2022 Community
- CodeMaid version: example 12.0
- Code language: example C#

### Description
Codemaid doesn't allow users to save when in the cleanup on save mode with the assembly attribute in a file.

### Steps to recreate
1. Create a new c# file
2. Add the following code to the top of the file
[assembly: InternalsVisibleTo("VMTests")]

4. set code maid to cleanup on save
5. save file

### Current behavior
It saves and then makes changes and this makes the file have to save again which then makes changes, and this repeats forever. 

### Expected behavior
It should be saving the file making the changes and then saving if there are new changes. It should not repeat the same changes.

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  I am unable to reproduce it.  There have been some fixes in the latest version of Visual Studio that may be related to this bug.  Can you upgrade to the latest Visual Studio version and see if the issue is still occurring?
