### ISSUE TITLE
Support .editorconfig or delegate formatting to EditorConfig extension

### ISSUE THREAD

**Issue by monoman** [codecadwallader/codemaid#96]
Not sure if EditorConfig extension was to blame on not reloading after changes to root .editorconfig, but seems to have some bad interaction specially in the insert_final_newline handling and doing code cleanup.

See http://editorconfig.org/#supported-properties

Ideally codemaid should support .editorconfig itself, although VS2015 may come up with some kind of embedded support down the road.

**Comment by codecadwallader** [comment]
We had some conversations around EditorConfig a long time ago, and the plan at that time was that as long as EditorConfig modifies the Visual Studio preferences, CodeMaid would respect them as that's how it already works today.  Old links: https://trello.com/c/aST4HF65

Specifically for insert_final_newline, we have very similar settings to insert/remove an empty new line at the end of the file.

I'd be open to reopening or starting a new card in the backlog to see if there's interest in revisiting the topic.  If you're interested, please start a thread on the public Trello backlog here: https://trello.com/b/VVxVhbQv/backlog
