### ISSUE TITLE
Complexity values in Spade differ from the values reported by Visual Studio

### ISSUE THREAD

**Issue by danrg** [codecadwallader/codemaid#97]
Most likely, codemaid uses a different approach to calculate complexity than Visual Studio (VS2012 Professional). The values shown by VS seem to be more accurate than the ones reported by codemaid  (codemaid reports much lower values).
Is it possible for codemaid to display the same complexity values as the values in VS?

I noticed the complexity values reported by this project are in sync with the values from VS: https://codemetricsviewer.wordpress.com/2013/09/19/good-things-come-to-those-who-wait/ , so this could be a starting point.

Thank you,
Dan

**Comment by codecadwallader** [comment]
Thanks for the feedback.  CodeMaid does have its own basic complexity calculation mechanism that predates the other tools you've referenced.  It isn't exact, but it's a very rapid and approximate McCabe complexity calculation based on the number of specific keywords present within a method or property body.  An advantage it has over the mechanism used by VS is that it doesn't require a code compilation to generate metrics.  I also took a brief look at the other tool you mentioned but that doesn't appear to be open source.

Do you have some code samples where CodeMaid was reporting much lower values?

**Comment by danrg** [comment]
Thanks for your quick feedback.
Please check https://gist.github.com/danrg/94050286a3377cdd54fa for a short example.
Adding more linq code in a function seems to increase the difference.

**Comment by codecadwallader** [comment]
Thanks for the code sample, that helps a lot.

So CodeMaid's calculation comes from:
 - 1 for the base path (every method is at least 1)
 - +1 for the if statement
 - +4 for the 4 conditional operators

What isn't counted as our algorithm was built pre-LINQ:
 - +1 for the iteration that occurs within the All method
 - +1 for the implicit test and break if a match is not found that occurs within the All method.  That's my hypothesis based on using ReSharper to generate the equivalent non-LINQ code.  I added that code snippet back to your gist for context.

When I convert the LINQ code to non-LINQ code, I get a matching 8 count from CodeMaid.

Still doing a little more investigation.

**Comment by codecadwallader** [comment]
Added some more code examples to that Gist.  To improve the accuracy is going to require some rewrites, hopefully powered by Roslyn's own analytics so it can still be done without a full compile.

Moved to our backlog to get a sense of public interest.  Please vote/comment further here: https://trello.com/c/wlC1l3RB

Thanks again for highlighting the differences, I really appreciate it.
