### ISSUE TITLE
May i know witch CodeMaid version can support 2022 (ARM 64-bit)  , thank you

### ISSUE THREAD

**Issue by RuiTeemoZhang** [codecadwallader/codemaid#977]
### Environment
- Visual Studio version: Microsoft Visual Studio Professional 2022 (ARM 64-bit) - Current Version 17.4.4
- CodeMaid version: CodeMaid.VS2022.v12.0.300
- Code language: C#

### Description
May i know witch CodeMaid version can support 2022 (ARM 64-bit)  ,thank you

### Expected behavior
2023/2/13 21:41:57 - Microsoft VSIX Installer
2023/2/13 21:41:57 - -------------------------------------------
2023/2/13 21:41:57 - vsixinstaller.exe version:
2023/2/13 21:41:57 - 17.4.2120
2023/2/13 21:41:57 - -------------------------------------------
2023/2/13 21:41:57 - Command line parameters:
2023/2/13 21:41:57 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\CodeMaid.VS2022.v12.0.300.vsix
2023/2/13 21:41:57 - -------------------------------------------
2023/2/13 21:41:57 - Microsoft VSIX Installer
2023/2/13 21:41:57 - -------------------------------------------
2023/2/13 21:41:59 - Initializing Install...
2023/2/13 21:42:00 - 扩展详细信息...
2023/2/13 21:42:00 - 	Identifier         : 9079e73d-3fbb-4e07-8dab-f44fa5d8e8b5
2023/2/13 21:42:00 - 	Name               : CodeMaid VS2022
2023/2/13 21:42:00 - 	Author             : Steve Cadwallader
2023/2/13 21:42:00 - 	Version            : 12.0.300
2023/2/13 21:42:00 - 	Description        : CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
2023/2/13 21:42:00 - 	Locale             : en-US
2023/2/13 21:42:00 - 	MoreInfoURL        : http://www.codemaid.net/
2023/2/13 21:42:00 - 	InstalledByMSI     : False
2023/2/13 21:42:00 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2023/2/13 21:42:00 - 
2023/2/13 21:42:00 - 	SignatureState     : Unsigned
2023/2/13 21:42:00 - 	支持的产品              : 
2023/2/13 21:42:00 - 		Microsoft.VisualStudio.Community
2023/2/13 21:42:00 - 			Version : [17.0,18.0)
2023/2/13 21:42:00 - 			ProductArchitecture : amd64
2023/2/13 21:42:00 - 
2023/2/13 21:42:00 - 	引用                 : 
2023/2/13 21:42:00 - 	系统必备               : 
2023/2/13 21:42:00 - 		-------------------------------------------------------
2023/2/13 21:42:00 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2023/2/13 21:42:00 - 		Name         : Visual Studio core editor
2023/2/13 21:42:00 - 		Version      : [17.0,18.0)
2023/2/13 21:42:00 - 
2023/2/13 21:42:00 - 签名详细信息...
2023/2/13 21:42:00 - 	Extension is not signed.
2023/2/13 21:42:00 - 
2023/2/13 21:42:00 - 正在搜索适用的产品...
2023/2/13 21:42:00 - 找到的已安装产品 - Visual Studio Professional 2022
2023/2/13 21:42:00 - 找到的已安装产品 - ssms
2023/2/13 21:42:00 - 找到的已安装产品 - 全局位置
2023/2/13 21:42:00 - VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上。
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()

**Comment by codecadwallader** [comment]
Thanks for asking the question.  We do not yet have support for ARM, but are tracking it in #963
