### ISSUE TITLE
Empty lines in verbatim strings are removed

### ISSUE THREAD

**Issue by dg9ngf** [codecadwallader/codemaid#98]
In the following code, the empty line is removed:

		Console.Write(@"
	Line 1]

	Line 2");

I'm not sure which CodeMaid setting causes this. Visual Studio 2015 RC's document formatting alone doesn't cause this bug.

**Comment by codecadwallader** [comment]
This is caused by the setting CodeMaid->Configuration->Cleaning->Remove->"Remove multiple consecutive blank lines".

This action runs a basic regular expression replacement across the file, which is agnostic of verbatim strings.

To make the code smarter, requires the new Roslyn APIs in VS2015.  There is a card in our backlog for a very similar issue about removing end of line whitespace in verbatim strings here: https://trello.com/c/DwYkFjjM

**Comment by dg9ngf** [comment]
I should have mentioned that I have disabled this option, and it didn't fix it. That line is still removed. Even if I also disable the option about end-of-line whitespace. So it must be something else. I just don't know what.

**Comment by codecadwallader** [comment]
It is getting incorrectly picked up by the "Remove blank lines after attributes" action.  Reopening issue.

**Comment by dg9ngf** [comment]
Ah, that explains why it only happens with `]` at the end of the line. I could live with temporarily disabling that option.

**Comment by codecadwallader** [comment]
I've improved the matching logic, and added the scenario above to the unit tests.  Thanks for reporting it and the fix will be present in the next release.

**Comment by dg9ngf** [comment]
The code looks good and should handle my case just fine. (I do have an opening bracket there as well, but not at the beginning of the line.) I guess that's about what we can expect with regular expressions instead of a real parser.

**Comment by codecadwallader** [comment]
Glad that it covers your scenario.

Yeah, regular expressions are definitely not the ideal approach but the best that was easily available when we started back in VS2005.  Commercial companies like JetBrains (ReSharper) and Developer Express (CodeRush) built their own C# compilers to have more intelligent logic, but that was far beyond the scope of this tool.

With the new Roslyn compiler available starting in VS2015, there are a *lot* more details available to extensions like CodeMaid.  It's going to be a very big rewrite and we'll still need all the existing logic for backwards compatibility, but it is our future.  https://trello.com/c/L3Peail8
