### ISSUE TITLE
Codemaid places 'private' modifier in front of IEnumerator IEnumerable.GetEnumerator()

### ISSUE THREAD

**Issue by lukaszciastko** [codecadwallader/codemaid#99]
When a class implements IEnumerable<T>, Codemaid places a private modifier in front of IEnumerator IEnumerable.GetEnumerator().

To reproduce, create a new class that implements IEnumerable<T> and press Ctrl+M and space:

    public class MyCollection : IEnumerable<string>
    {
        public IEnumerator<string> GetEnumerator()
        {
            throw new NotImplementedException();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

**Comment by codecadwallader** [comment]
Thanks for reporting the issue.  This is a known, open defect with the VS2015 Preview.  Please see #56 for more details.
